### ISSUE TITLE
Column name character encoding issue

### ISSUE THREAD

**Issue by bruth** [markdirish/node-odbc#100]
I am using this driver with [SQLPad](https://github.com/rickbergfalk/sqlpad) (/cc @rickbergfalk) and observing the column names have a different character encoding (appears to be non-latin), however the record data all is correct (I will follow up with a screenshot to demonstrate).

I don't believe SQLPad is doing anything to cause this issue ([here is the code](https://github.com/rickbergfalk/sqlpad/blob/master/server/drivers/unixodbc/index.js#L107-L119) for setting up a client connection for example). The database being connected to is AWS Athena.

I can provide more details, but I was curious if there was anything obvious that comes to mind or something I can do to help with debugging the cause?

I appreciate the help!

**Comment by markdirish** [comment]
Hmm, I don't have any experience with SQLPad or AWS Athena, but it seems like a strange issue. I notice that SQLPad mentions wankdanker/node-odbc, which is the 1.x version of this package and returned data in a different format. It could be that it is trying to get the column name in a different way than 2.x returns it. Could you just confirm what version of the `odbc` package you are using? And show me what output for the column names you are getting?

All data handled by JavaScript in the package is in UTF-8 or UTF-16, its _possible_ the encoding of the column names isnt the same (though if it is just normal ASCII characters, should work anyways). Also possible that calls to `SQLDescribeCol` are calling the widechar API (`SQLDescribeColW`)...

**Comment by rickbergfalk** [comment]
Not sure if this helps but in SQLPad the column names are being derived from the keys returned in the row objects, not the columns property on the results itself if that makes sense. I intend on changing that at some point. 

@bruth if I made a branch with some changes and additional logging would you be willing to run it against the database you're seeing this in?

**Comment by bruth** [comment]
@markdirish Thanks for the observation and explanation. That sounds like a couple good candidates to test out.

@rickbergfalk Sure that would be helpful. Another team I am working with is actually doing the integration with SQLPad, but I will notify them if you put something to getting. Thanks!

**Comment by ssedano** [comment]
I'm facing the same issue with v2.2.2 (I also tried 2.3.0). Querying through `isql` works fine. Looking at odbc's trace file the main difference seems to be the encoding, but not sure if is a red-herring

### isql (works)
```
UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UCS-2LE'
```

### Node (doesn't work)
```
UNICODE Using encoding ASCII 'ANSI_X3.4-1968' and UNICODE 'UCS-2LE'
```


The code seems to call `SQLDescribeCol.c`

```
[ODBC][83370][1594683904.616360][SQLDescribeCol.c][247]
                Entry:
                        Statement = 0x7f141c002aa0
                        Column Number = 1
                        Column Name = 0x7f141c00cfc0
                        Buffer Length = 0
                        Name Length = 0x7f141c0079f2
                        Data Type = 0x7f141c0079f4
                        Column Size = 0x7f141c0079f8
                        Decimal Digits = 0x7f141c007a00
                        Nullable = 0x7f141c007a10
[ODBC][83370][1594683904.616503][SQLDescribeCol.c][504]
                Exit:[SQL_SUCCESS_WITH_INFO]
                        Column Name = [<B0>r]
                        Data Type = 0x7f141c0079f4 -> 93
                        Column Size = 0x7f141c0079f8 -> 23
                        Decimal Digits = 0x7f141c007a00 -> 3
                        Nullable = 0x7f141c007a10 -> 1
```
