### ISSUE TITLE
Reconnect after disconnecting

### ISSUE THREAD

**Issue by MrTeapot** [markdirish/node-odbc#101]
Hey!

For my REST APIs I like to keep a pool of connections open, and not make a connection on every request.

If the API server would lose connection to the db server (for example, during maintenance) - will a Pool create new connections once it's possible to connect again? And then fill the "pool" again?

**Comment by markdirish** [comment]
Nope, what will happen is that all of your connections in the Pool will eventually timeout. They will no longer be connected, but once you try to use one, it will:
* check out a connection
* see that it isn't connected
* discard that connection
* then make a new connection.

I'm not sure how I would go about implementing an auto-connect or an auto-clean of stale connections in an ODBC way. You could set the connection timeout to 0 and then things will just spin until the system comes back up...

**Comment by MrTeapot** [comment]
What you described sounds good for my use case, it will start to fill the pool again with new connections as I try to use them. Eventually, all the stale connections will be replaced - at the cost of a little slower response time until the pool is full of fresh connections.
