### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by AndyYouens** [markdirish/node-odbc#104]
is there a minimum level of node for this package?

I'm running 8.17 and it doesnt install using npm install odbc

node-pre-gyp ERR! node -v v8.17.0
node-pre-gyp ERR!  -v v0.14.0
node-pre-gyp ERR! not ok

are there any other pre-req's?

**Comment by markdirish** [comment]
It used to work with node 8, but it looks like the latest version of `node-addon-api` requires Node 10 or greater: https://github.com/nodejs/node-addon-api (search for "10.x" in the page). It probable uses stuff from N-API version 5, which requires 10.17+: https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix

What you might be able to do is download version 1.7.1 of `node-addon-api` before trying to install `odbc`:

`npm install node-addon-api@1.7.1`

This package only requires 1.7.1 and above (https://github.com/markdirish/node-odbc/blob/bc0e0fa083c746fc98faca531fb54608f990a72d/package.json#L42), so it should work. But this seems to be another reason that it might be good to rewrite this in C and simply used N-API and no additional dependencies.

**Comment by kadler** [comment]
Another thought is that we should declare our support statement for versions of Node.js and have a clear support policy. Not saying we should drop Node v8 support right now, but we should at least have a defined policy of which we support and when Node versions will be dropped from support.

**Comment by markdirish** [comment]
Will work on Kevin's suggestion, but closing this as the main issue here was solved.
