### ISSUE TITLE
Encoding problem from odbc data 

### ISSUE THREAD

**Issue by cassiolibraga** [markdirish/node-odbc#106]
Hello,

I have recently updated to the current node odbc version (2.3.0). Since then I have a problem with the correct encoding of Brazilian special characters (éãó). The older version of node odbc (<2.0) was working fine.
The database is Microsoft Visual Fox PRO. The DBF file is encoded with WINDOWS 1252.
I am currently able to read the file but the specials characters were not decoded correctly (� got this).

Using node odbc 2.3.0:

[
  { cdp_cod: 1, cdp_des: 'DINHEIRO' },
  { cdp_cod: 10, cdp_des: 'VALE ALIMENTA��O' },
]

Using node odbc 1.4.6:

[
  { cdp_cod: '1', cdp_des: 'DINHEIRO' },
  { cdp_cod: '10', cdp_des: 'VALE ALIMENTAÇÃO' } 
]

**Comment by markdirish** [comment]
Versions 1.x were built with `UNICODE` defined by default, which is an important definition for Windows (especially for extended character sets). Try modifying `binding.gyp` to add `UNICODE` to the defines:

```
'defines' : [
        'NAPI_EXPERIMENTAL', 'UNICODE'
      ],
```

And then run `npm install` when in the `odbc` directory to re-run the build.

**Comment by cassiolibraga** [comment]
I dit it, but, unfortunately, It seems not to work.

**Comment by ezequielmross** [comment]
Did you find a solution? @cassiolibraga

**Comment by manudarp** [comment]
@cassiolibraga @ezequielmross I have an urgent need to find out the solution to this problem, I tried to do everything. Have you found out the solution?

**Comment by mealha** [comment]
I have the same problem, i have tcompiled width UNICODE and widdout and dont work

**Comment by Yuri-Chaves** [comment]
Any solution?
