### ISSUE TITLE
Calling Stored Procedures Issue

### ISSUE THREAD

**Issue by sjmorales** [markdirish/node-odbc#11]
I keep getting Stored Procedure doesn't Exit in DB2.

Create or Replace Function Test() Returns VARCHAR(4000)
Return ('Test');

const connection = await odbc.connect("DSN=MYDSN");
const result = await connection.callProcedure(null, null, 'TEST', [undefined]);
console.log(result);

(node:2235) UnhandledPromiseRejectionWarning: Error: Error: [Node.js::odbc] CallProcedureAsyncWorker::Execute: Stored procedure TEST doesn't exit
    at Object.<anonymous> (.../odbc/lib/Connection.js:114:20)

**Comment by markdirish** [comment]
That's funny, the error should read 'Stored procedure TEST doesn't **exist**'.

We have been noticing in other packages that there is some difficulty resolving the default library/default schema, especially if not defined in the DSN configuration. If you add the schema/library name to the second parameter instead of `null`, does it print the same error?

**Comment by sjmorales** [comment]
Yes.  It does get the same error.  
If I do "values (TEST())", I get a result as expected when I query the stored procedure.

**Comment by sjmorales** [comment]
const connection = await odbc.connect("DSN=MYDSN");
const result = await connection.query("Create or Replace Function Test() Returns CHAR(4) Return 'Test'");
console.log(result);

result = await connection.callProcedure(null, 'PGMSTEVEN', 'TEST', [undefined])
	.catch(error => console.log('Error:',error));
console.log(result);

I updated my test to include the create or replace function right before it calls it with the same error.

[
  statement: "Create or Replace Function Test() Returns CHAR(4) Return 'Test'",
  parameters: [],
  return: undefined,
  count: 0,
  columns: []
]
Error: Error: Error: [Node.js::odbc] CallProcedureAsyncWorker::Execute: Stored procedure PGMSTEVEN.TEST doesn't exit
    at Object.<anonymous> (.../node_modules/odbc/lib/Connection.js:114:20)

**Comment by sjmorales** [comment]
const result3 = await connection.query("Values (TEST())");
console.log(result3);

[
  { '00001': 'Test' },
  statement: 'Values (TEST())',
  parameters: [],
  return: undefined,
  count: -1,
  columns: [ { name: '00001', dataType: 1 } ]
]

**Comment by sjmorales** [comment]
After thinking about things, I noticed that I was calling a function, not a procedure. 
I tried calling this procedure...

Create or Replace Procedure Test2(
  OUT TestData VARCHAR(4))
P1: BEGIN
  SET TestData = 'Test';
END P1;

But it errors out with a core dump.
*** Error in `node': free(): invalid pointer: 0x00007fe6f94f9b88 ***

**Comment by sjmorales** [comment]
Another update.  If I only use numbers in the parameter, it works.  If I use varchar or char, it crashes with a segmentation fault/core dump.

**Comment by sjmorales** [comment]
Just to rule out the ODBC driver, I did a test in ISQL and it worked as it was supposed to...

CREATE VARIABLE X VARCHAR(4);
CALL TEST2(X);
VALUES (X);
//Result : XXXX

**Comment by markdirish** [comment]
Ok, back on this for a bit, I have recreated the issue with a procedure returning a NUMERIC and a VARCHAR, and I am seeing the seg fault. Investigating!

**Comment by sjmorales** [comment]
You would be our hero.   Do you wear an iCape?
________________________________

**Comment by markdirish** [comment]
I think I isolated and fixed the issue, I have a branch with the fixes:

https://github.com/markdirish/node-odbc/tree/callProcedure-segFault

Would you mind pulling and seeing if it fixes the issue? Thanks!

**Comment by markdirish** [comment]
I haven't fixed the return issue yet... it looks in the code that I actually made it just hardcode return undefined! I will take a look into it now

**Comment by sjmorales** [comment]
Testing now...

**Comment by jkdavew** [comment]
Hi Mark - is there, or will there be support for using callProcedure with a stored procedure having CLOB parameters?

As of now it doesn't appear to be working in node (as a side note, I was able to get it to work with the iSQL application).

Thank you

**Comment by markdirish** [comment]
As of this moment there is not support for CLOBs, working with CLOBs/BLOBs was something I wasn't super comfortable with when I first started to work on this package. I'm willing to take a stab at it now, though I probably won't get a chance to work on it until the first week in July.

Quick question: What type of data are you storing in your CLOB field, long text data? I assume developers want the data returned in a long String, but correct me if I'm wrong. My initial thought was to return an ArrayBuffer of byte data, but since the CLOB has character encoding, I assume most people use it for character data.

**Comment by jkdavew** [comment]
Thanks Mark.

Yes a long string is what I was looking to output...specifically a string
of JSON as this would be used for a RESTful service.

Appreciate the work!

**Comment by jkdavew** [comment]
Mark,

One more thing regarding this issue.  Regardless of CLOB support, I seem to be having issues with regular CHAR or VARCHAR data.

My stored procedure calls an RPG program...could there be an issue with that integration?

CREATE OR REPLACE PROCEDURE LIBNAME/STRDPROC(
                IN inRequest CHAR(500),
                OUT otResponse CHAR(500)
            )
        EXTERNAL NAME 'LIBNAME/SRVPGM(PROC_NAME)'
        LANGUAGE Rpgle
        PARAMETER STYLE GENERAL
        NO SQL
        NOT DETERMINISTIC;

The parameters into the service program procedure are blank?!?!?  I'm testing with the branch you mention above:
https://github.com/markdirish/node-odbc/tree/callProcedure-segFault

Thx

**Comment by jkdavew** [comment]
Also getting this sporadically if this helps:

double free or corruption (!prev)
Segmentation fault (core dumped)

**Comment by sjmorales** [comment]
There seems to be an issue with input/output parameters.

If you create a procedure that has an INOUT and an OUT, and just pass the IN to the OUT, the data is lost.  SQL does not appear to be receiving the INOUT data.

If I uncomment the line that sets the OUT value, it does return that value.
Also, if I use IN instead of INOUT, it works (sometimes).

```
  app.get('/testtable', async function (req, res) {
    res.header('Access-Control-Allow-Origin', req.headers.origin);
    res.header(
      'Access-Control-Allow-Headers',
      'Origin, X-Requested-With, Content-Type, Accept'
    );
    const connection = await odbc.connect('DSN=MYDSN');
    const result = await connection
      .callProcedure(null, null, 'TEST3', ['XXX',undefined])
      .catch((error) => console.log('Error:', error));
    res.send(result.parameters[0]);
    console.log(result);
  });
```


```
Create or Replace Procedure Test3(INOUT BOB VARCHAR(4), OUT JOE VARCHAR(4))
language sql
specific test3
BEGIN
  SET JOE = BOB;
--   SET BOB = 'XXX';
  Return 0;
END;
```

**Comment by markdirish** [comment]
> Hi Mark - is there, or will there be support for using callProcedure with a stored procedure having CLOB parameters?

I looked into this more, and it looks like this might actually be an issue with the driver itself, which is returning -99 for for CLOB data type, which then cannot be bound using SQLBindParameter. There might be an option to change to get it to return the correct data, but I will have to do some investigating. Looking through the other issues on here as well.

**Comment by sjmorales** [comment]
If it helps, we were able to get clob data via normal queries.   Ie: values clob("test").  I tested a string length of 34k.  It returns datatype of -1 in this case.
________________________________
