### ISSUE TITLE
Pool keeps adding connections after query

### ISSUE THREAD

**Issue by aboft** [markdirish/node-odbc#119]
Hello all,

Please excuse some of my ignorance as I'm still new with some of this, but I'm coming across a problem where I create a pool and really only query some data, manipulate, and then send it off to another part of my app. I noticed that after the query it will release the connections but keeps adding about 5 idle connections. After each search there's another 4-7 connections added and idle (assuming idle). If I swap over to using only a single connection (without pool) they close just fine. I came across this error because node had a plethora of established connections which caused the error EMFILE.

`async function getCurrentWorkload() {
    const pool = await odbc.pool({connectionString, maxSize: 10})
    //await pool.connect()
    console.log("FETCHING WORKLOADS FOR TECHNICIANS")
    const currentWorkloadDB = await pool.query(`select * from ticket_db;`)
    if (!currentWorkloadDB) {
        await pool.close()
        console.log("ERROR OCCURRED FETCHING WORKLOAD FROM DB")
        return
    }
    const currentWorkload = currentWorkloadDB.map(load => {
        load.ID = load.ID.trim()
        load.Name = load.Name.trim()
        return load
    })
    await pool.close()
    console.log("CLOSED POOL CONNECTION")
    return currentWorkload
}
`

I was testing with pool.close() which according to the docs, I assume should close the pool entirely, which it did close more connections than without pool.close(). It just did not remove them all and would leave about 5 connections idle. On the next search, it would go up to about 23 and when the query was done it would go back to idle connections but this time being 10. The connections just keep going up after each search. I expect to see the same amount of connections being idle each time, not continuous growth. This seems to be adding new idle connections but again, maybe I am doing something wrong.

`$ sudo lsof -i -n -P | grep node | grep 1433
node      15398         43u  IPv4 572779      0t0  TCP 10.0.0.87:37372->192.168.100.16:1433 (ESTABLISHED)
node      15398         45u  IPv4 564010      0t0  TCP 10.0.0.87:37346->192.168.100.16:1433 (ESTABLISHED)
node      15398         47u  IPv4 564028      0t0  TCP 10.0.0.87:37414->192.168.100.16:1433 (ESTABLISHED)
node      15398         49u  IPv4 565026      0t0  TCP 10.0.0.87:37388->192.168.100.16:1433 (ESTABLISHED)
node      15398         55u  IPv4 568816      0t0  TCP 10.0.0.87:37470->192.168.100.16:1433 (ESTABLISHED)
node      15398         57u  IPv4 570670      0t0  TCP 10.0.0.87:37444->192.168.100.16:1433 (ESTABLISHED)
node      15398         59u  IPv4 564055      0t0  TCP 10.0.0.87:37512->192.168.100.16:1433 (ESTABLISHED)
node      15398         61u  IPv4 568822      0t0  TCP 10.0.0.87:37486->192.168.100.16:1433 (ESTABLISHED)
node      15398         69u  IPv4 568780      0t0  TCP 10.0.0.87:37370->192.168.100.16:1433 (ESTABLISHED)
node      15398         83u  IPv4 564041      0t0  TCP 10.0.0.87:37468->192.168.100.16:1433 (ESTABLISHED)

$ sudo lsof -i -n -P | grep node | grep 1433
node      15398         35u  IPv4 564084      0t0  TCP 10.0.0.87:37522->192.168.100.16:1433 (ESTABLISHED)
node      15398         37u  IPv4 564086      0t0  TCP 10.0.0.87:37524->192.168.100.16:1433 (ESTABLISHED)
node      15398         39u  IPv4 564088      0t0  TCP 10.0.0.87:37526->192.168.100.16:1433 (ESTABLISHED)
node      15398         41u  IPv4 572845      0t0  TCP 10.0.0.87:37528->192.168.100.16:1433 (ESTABLISHED)
node      15398         43u  IPv4 572779      0t0  TCP 10.0.0.87:37372->192.168.100.16:1433 (ESTABLISHED)
node      15398         45u  IPv4 564010      0t0  TCP 10.0.0.87:37346->192.168.100.16:1433 (ESTABLISHED)
node      15398         47u  IPv4 564028      0t0  TCP 10.0.0.87:37414->192.168.100.16:1433 (ESTABLISHED)
node      15398         49u  IPv4 565026      0t0  TCP 10.0.0.87:37388->192.168.100.16:1433 (ESTABLISHED)
node      15398         51u  IPv4 564090      0t0  TCP 10.0.0.87:37530->192.168.100.16:1433 (ESTABLISHED)
node      15398         53u  IPv4 565138      0t0  TCP 10.0.0.87:37532->192.168.100.16:1433 (ESTABLISHED)
node      15398         55u  IPv4 568816      0t0  TCP 10.0.0.87:37470->192.168.100.16:1433 (ESTABLISHED)
node      15398         57u  IPv4 570670      0t0  TCP 10.0.0.87:37444->192.168.100.16:1433 (ESTABLISHED)
node      15398         59u  IPv4 564055      0t0  TCP 10.0.0.87:37512->192.168.100.16:1433 (ESTABLISHED)
node      15398         61u  IPv4 568822      0t0  TCP 10.0.0.87:37486->192.168.100.16:1433 (ESTABLISHED)
node      15398         63u  IPv4 568917      0t0  TCP 10.0.0.87:37534->192.168.100.16:1433 (ESTABLISHED)
node      15398         65u  IPv4 564092      0t0  TCP 10.0.0.87:37536->192.168.100.16:1433 (ESTABLISHED)
node      15398         67u  IPv4 568919      0t0  TCP 10.0.0.87:37538->192.168.100.16:1433 (ESTABLISHED)
node      15398         69u  IPv4 568780      0t0  TCP 10.0.0.87:37370->192.168.100.16:1433 (ESTABLISHED)
node      15398         71u  IPv4 565140      0t0  TCP 10.0.0.87:37540->192.168.100.16:1433 (ESTABLISHED)
node      15398         73u  IPv4 565142      0t0  TCP 10.0.0.87:37542->192.168.100.16:1433 (ESTABLISHED)
node      15398         75u  IPv4 572847      0t0  TCP 10.0.0.87:37544->192.168.100.16:1433 (ESTABLISHED)
node      15398         77u  IPv4 570724      0t0  TCP 10.0.0.87:37546->192.168.100.16:1433 (ESTABLISHED)
node      15398         79u  IPv4 568921      0t0  TCP 10.0.0.87:37548->192.168.100.16:1433 (ESTABLISHED)
node      15398         81u  IPv4 564094      0t0  TCP 10.0.0.87:37550->192.168.100.16:1433 (ESTABLISHED)
node      15398         83u  IPv4 564041      0t0  TCP 10.0.0.87:37468->192.168.100.16:1433 (ESTABLISHED)
`

**Comment by markdirish** [comment]
This should be fixed in #142 and in various additional pool fixes since the creation of the issue! Would recommend downloading 2.4.4 (or above) to fix the issue.
