### ISSUE TITLE
multiple statements

### ISSUE THREAD

**Issue by cmdreay** [markdirish/node-odbc#124]
can i query with multiple statements?  just like module 'mysql'

**Comment by markdirish** [comment]
I'm not sure what you mean. Like:

```
const result = connection.query('SELECT * FROM TABLE; SELECT * FROM OTHERTABLE');
```

ODBC does have batch support: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/batches-of-sql-statements?view=sql-server-ver15

Unfortunately this package doesn't yet have support for returning multiple result sets in the result object: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/multiple-results?view=sql-server-ver15

**Comment by cmdreay** [comment]
> I'm not sure what you mean. Like:
> 
> ```
> const result = connection.query('SELECT * FROM TABLE; SELECT * FROM OTHERTABLE');
> ```
> 
> ODBC does have batch support: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/batches-of-sql-statements?view=sql-server-ver15
> 
> Unfortunately this package doesn't yet have support for returning multiple result sets in the result object: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/multiple-results?view=sql-server-ver15

that's what i mean ,thanks
