### ISSUE TITLE
[BUG] Error returning negative smallint columns.

### ISSUE THREAD

**Issue by epligrow** [markdirish/node-odbc#127]
**Describe your system**
* `odbc` Package Version: 2.3
* ODBC Driver: IBM i Access ODBC Driver
* Database OS: DB2
* Node.js Version: v10.16.3
* Node.js OS: IBM i v7.3

**Describe the bug**
While running a select on a smallint column containing negative numbers, the following error appeared. The value of Column 26 in the error shown is -13, but this happens on any negative smallint regardless of column. Current workaround is casting the smallint as a regular int in the query.
![Error Image](https://user-images.githubusercontent.com/38891205/94826132-9d2b3b80-03cc-11eb-8424-dbc9ed0f4c48.jpg)

**Expected behavior**
The select statement should return the negative number, as it is within the limit of a signed smallint. The column returns properly in other ODBC-based database management systems.

**To Reproduce**
Run any select query returning a negative smallint

**Comment by markdirish** [comment]
Hi @epligrow !

Yea, unfortunately SMALLINT fields are binding to an SQLUSMALLINT! I have a big host of changes I am working on now (primarily getting procedures to work more smoothly), and this is one of the main fixes. Will link this issue when it is fixed so you will get an update.

Thanks for the issue!

**Comment by markdirish** [comment]
@epligrow  do you want to see if it is still an issue on the 2.4.0-alpha.0 version? You can download by running `npm install odbc@alpha`. I think the SMALLINT changes are in there.

**Comment by sdepold** [comment]
FWIW: It is still an issue with 2.4.0-alpha.0

**Comment by markdirish** [comment]
@sdepold Going to start testing with BigInts. I wouldn't think that `TODO` message is actually applicable. It binds to `SQL_C_SBIGINT`, which should be just fine for all signed bigint values.

A few questions:

Can you reproduce with a simple query? Or is it when binding parameters?
What Database/Driver are you using?

**Comment by markdirish** [comment]
https://github.com/markdirish/node-odbc/blob/master/src/odbc_connection.cpp#L401-L409

This is likely the culprit. `SQL_BIGINT` binding to `SQL_C_UBIGINT`, and not `SQL_C_SBIGINT` or `SQL_C_BIGINT` (the latter of which I believe is deprecated)

**Comment by markdirish** [comment]
Recreated! Will fix.

**Comment by sdepold** [comment]
Wool Woop. Looking forward to have this fixed in our prod builds :) thanks for your work! Much appreciated.

**Comment by markdirish** [comment]
2.4.0 is now published and this should be fixed. Feel free to open if it still seems broken!
