### ISSUE TITLE
std::bad_alloc with many rows result

### ISSUE THREAD

**Issue by ml60** [markdirish/node-odbc#13]

**Comment by markdirish** [comment]
I have run tests on valgrind and can't find a memory leak anywhere, can you give more information about your issue? std::bad_alloc could be because Node.js doesn't have enough memory available to store all the rows you are returning if you are getting thousands, tens of thousands, hundred of thousands. You might have to run use `LIMIT` in your query or another method of paginating.

**Comment by ml60** [comment]
Hi Mark,

i make a query with 15.000 rows (1kB each)
with odbc 2.0.0-beta.1, i have no problem

i'm using node 12.4.0

best regards
Massimo Lupano


Il giorno mar 18 giu 2019 alle ore 16:34 Mark Irish <
notifications@github.com> ha scritto:

**Comment by markdirish** [comment]
Sorry, I've had a busy couple of weeks. If it works on 2.0.0-beta.1, but not on 2.0.0-4, then hopefully I can track down what changed. I will take a peek and see what I can come up with (and also see if I can replicate the issue)

**Comment by Patcher56** [comment]
I also have the `std::bad_alloc` error.
I am connecting to a IBM iSeries.
When I select data with limit 6, there is no problem, when I select data with limit 7 or higher, I get the `std::bad_alloc` error.
The `isql` command coming with unixodbc queries without any errors.

Using Node v12.1.0 and `odbc` package version `2.1.3`

**Comment by Patcher56** [comment]
Hi Mark,
thanks for your fast answer. Oh I didn't find out the meaning of length -4 - thanks for that.

Yes the `KKNA` column is the one with special characters.

It is only strange that I successfully fetched all of the data with my own odbc implementation (like described [here](http://www.unixodbc.org/doc/ProgrammerManual/Tutorial/). It is just a connection and a query, but no implementation of node-gyp. So maybe some character encoding exists in this implementation.

Anyway it would be not bad to implement an error check for `SQL_NO_TOTAL` to prevent crashes.
