### ISSUE TITLE
Bump `node-addon-api` version to latest

### ISSUE THREAD

**Issue by markdirish** [markdirish/node-odbc#131]
`node-addon-api` is the C++ wrapper for N-API used by this package. The version currently used (`"^1.7.1"`) is a few years out of date and doesn't include the latest N-API code (version 6+ I believe).

The biggest change will be that Napi::BigInt was moved out of `NAPI_EXPERIMENTAL` and into `NAPi_VERSION > 6`. Will need to add `#if` checks in those code for cases where BigInt is used.

Also eed to update to the latest version and ensure that the `node-pre-gyp` build system can handle building multiple napi versions.

**Comment by kadler** [comment]
Does this effect the versions of Node.js that are supported?

**Comment by markdirish** [comment]
So the biggest issue is that node-addon-api only supports 10.x and above. From the [node-addon-api README](https://github.com/nodejs/node-addon-api):

```
node-addon-api is based on N-API and supports using different N-API versions. This allows addons built with it to run with Node.js versions which support the targeted N-API version. However the node-addon-api support model is to support only the active LTS Node.js versions. This means that every year there will be a new major which drops support for the Node.js LTS version which has gone out of service.

The oldest Node.js version supported by the current version of node-addon-api is Node.js 10.x.
```

I know we (IBM) ship nodejs8, but is not longer in LTS from Node.js.

*In an ideal world* I would have infinite time and could rewrite the package in pure N-API, which would mean that we wouldn't need `node-addon-api`, and the versions supported would be everything in the [N-API version matrix](https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix)

**Comment by kadler** [comment]
OK, considering Node.js 8 went EOL last December (so nearly a year ago), I think that's fine to drop it.

**Comment by markdirish** [comment]
2.4.0 is now published and this should be fixed.
