### ISSUE TITLE
[BUG] Error passing long parameters in select statement.

### ISSUE THREAD

**Issue by epligrow** [markdirish/node-odbc#134]
**Describe your system**
* `odbc` Package Version: 2.3.5
* ODBC Driver: IBM i Access ODBC Driver
* Database OS: DB2
* Node.js Version: v10.16.3
* Node.js OS: IBM i v7.3

**Describe the bug**
When executing a select statement with bound parameters in a where clause or case statement, if the parameter is longer than the column being queried a "right truncation error" will be thrown. This happens regardless of data type, as it has been observed to happen with both chars and varchars.

**Expected behavior**
Query should still run, even if it returns nothing. If a hard-coded string longer than the column is used, the query runs as expected. This error only occurs with parameters.

**To Reproduce**
1. Create a statement with a parameter in a where clause or case statement.
2. Pass a parameter longer than the column being interrogated. (For example, passing 'This is a long string' to a char(10).)
3. Execute statement.

**Code**
This uses a system table as an example, but this can happen on any table.
![image](https://user-images.githubusercontent.com/38891205/96597761-d102ce00-12b3-11eb-9fd6-c7051789140a.png)

**Comment by kadler** [comment]
This is not a problem with node-odbc, that's just how ODBC and the IBM i Access ODBC driver works. If you pass a parameter that is too big to fit, the parameter will get truncated and treated as an error. Why do you want to pass oversized parameters? What's the use case here?

**Comment by epligrow** [comment]
I am using this to build a search, and the columns being searched are varying sizes. For example, the search looks for matches in both a 10-character name and a 30-character description.

**Comment by kadler** [comment]
If you want to control the size of your parameters, you should be able to do something like `select * from qsys2.object_tyes where object_type = cast(? as varchar(128))`.

**Comment by epligrow** [comment]
That seems to do the trick! I also found that casting the column itself as a larger varchar fixes this issue and is able to search on the entire string, even if it is longer than the normal length. Thanks for the help!

**Comment by markdirish** [comment]
Looks like this was solved, so going to close!
