### ISSUE TITLE
[BUG] Failed to set ciphers to use, errorSQLState=HY000

### ISSUE THREAD

**Issue by grahamaj** [markdirish/node-odbc#136]
**Describe your system**
* `odbc` Package Version: 2.3.5
* ODBC Driver: unixODBC.x86_64 0:2.3.1-14.el7 unixODBC-devel.x86_64 0:2.3.1-14.el7 mysql-connector-odbc.x86_64 0:8.0.22-1.el7
* Database Name: MySQL
* Database Version: 8.0.22
* Database OS: CentOS 7
* Node.js Versions (nvm not working): 10.21.0 (I have also tested all versions of 10.17.0-10.22.0, 12.19.0, 14.14.0, 15.0.1 with the same result)
* Node.js Versions (scl working): 10.21.0 (I have also tested 10.17.0)
* Node.js OS: CentOS 7

**Describe the bug**
We have a need to build nodejs ourselves, but our build of nodejs is similar to the builds of nodejs available through `nvm`: (`https://github.com/nvm-sh/nvm`). I am not able to get the odbc connection established when using builds of nodejs downloaded via `nvm`. Builds of nodejs distributed by software collections (scl) work just fine.

**Expected behavior**
Connection can be established with various ways of building node

**To Reproduce**
I have created a simple repository that uses `docker` and `docker-compose` to demonstrate the problem: https://github.com/grahamaj/odbc-tester. Within each directory just run `docker-compose build && docker-compose up`.  The `nvm` container will never connect and the `scl` container will connect once the database container is fully initialized.  You can specify any nodejs version in the `nvm` container by modifying it [here](https://github.com/grahamaj/odbc-tester/blob/main/nvm-node/Dockerfile#L4)

**Debug output**
`nvm` container:
```
ODBCConnection::Init
ODBCStatement::Init
[SQLHENV: 0x3063430] ODBC::Connect()
[SQLHENV: 0x3063430] ODBC::ConnectAsyncWorker::Execute()
[SQLHENV: 0x3063430][SQLHDBC: 0x7fcca40008c0] ODBCConnection::ConnectAsyncWorker::Execute(): SQLDriverConnect returned -1
ODBC::GetSQLError : handleType=2, handle=0x7fcca40008c0
ODBC::GetSQLError : called SQLGetDiagField; ret=0, statusRecCount=1
ODBC::GetSQLError : calling SQLGetDiagRec; i=0, statusRecCount=1
ODBC::GetSQLError : errorMessage=[unixODBC][MySQL][ODBC 8.0(w) Driver]SSL connection error: Failed to set ciphers to use, errorSQLState=HY000
Boo!
[SQLHENV: 0x3063430] ODBC::Connect()
[SQLHENV: 0x3063430] ODBC::ConnectAsyncWorker::Execute()
[SQLHENV: 0x3063430][SQLHDBC: 0x7fcc9c0008c0] ODBCConnection::ConnectAsyncWorker::Execute(): SQLDriverConnect returned -1
ODBC::GetSQLError : handleType=2, handle=0x7fcc9c0008c0
ODBC::GetSQLError : called SQLGetDiagField; ret=0, statusRecCount=1
ODBC::GetSQLError : calling SQLGetDiagRec; i=0, statusRecCount=1
ODBC::GetSQLError : errorMessage=[unixODBC][MySQL][ODBC 8.0(w) Driver]SSL connection error: Failed to set ciphers to use, errorSQLState=HY000
Boo!
```
`scl` container:
```
ODBCConnection::Init
ODBCStatement::Init
[SQLHENV: 0x338e1e0] ODBC::Connect()
[SQLHENV: 0x338e1e0] ODBC::ConnectAsyncWorker::Execute()
[SQLHENV: 0x338e1e0][SQLHDBC: 0x7f824c0008c0] ODBC::ConnectAsyncWorker::Execute(): Calling SQLGetInfo(ConnectionHandle = 0x7f824c0008c0, InfoType = 30 (SQL_MAX_COLUMN_NAME_LEN), InfoValuePtr = 0x332e738, BufferLength = 2, StringLengthPtr = 0)
[SQLHENV: 0x338e1e0][SQLHDBC: 0x7f824c0008c0] ODBC::ConnectAsyncWorker::Execute(): SQLGetInfo succeeded: SQLRETURN = 0, InfoValue = 192
[SQLHENV: 0x338e1e0][SQLHDBC: 0x7f824c0008c0] ODBC::ConnectAsyncWorker::Execute(): Calling SQLGetInfo(ConnectionHandle = 0x338e1e0, InfoType = 72 (SQL_TXN_ISOLATION_OPTION), InfoValuePtr = 0x332e73c, BufferLength = 4, StringLengthPtr = 0)
[SQLHENV: 0x338e1e0][SQLHDBC: 0x7f824c0008c0] ODBC::ConnectAsyncWorker::Execute(): SQLGetInfo succeeded: SQLRETURN = 0, InfoValue = 15
[SQLHENV: 0x338e1e0][SQLHDBC: 0x7f824c0008c0] ODBC::ConnectAsyncWorker::OnOk()
Hooray!
```

**Additional context**
Within each container, the command `isql Mydsn` successfully connects to the database

The `ldd` command is my best lead of the difference between the nodejs builds.  It appears that the `scl` distribution of node is dynamically linking in ssl and cryptography libraries.
From the `nvm` container:
```
ldd /root/.nvm/versions/node/v10.21.0/bin/node
        linux-vdso.so.1 =>  (0x00007ffce1dee000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f62debbb000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f62de9b3000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f62de6ac000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f62de3aa000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f62de194000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f62ddf78000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f62ddbaa000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f62dedbf000)
```
From the `scl` container:
```
ldd /opt/rh/rh-nodejs10/root/usr/bin/node
        linux-vdso.so.1 =>  (0x00007ffe50be9000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f4bbcb20000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f4bbc8ae000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4bbc6aa000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f4bbc4a2000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f4bbc19b000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f4bbbe99000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4bbbc83000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4bbba67000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4bbb699000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f4bbb483000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f4bbb236000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f4bbaf4d000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f4bbad49000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f4bbab16000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4bbcf83000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f4bba906000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f4bba702000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f4bba4e8000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f4bba2c1000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f4bba05f000)
```

In our custom build of node 10.17.0 we statically link in `openssl 1.1.1d`.

Is there anyway to get `odbc` to work with statically linked ssl and cryptography libraries? Am I missing something in setting up my system?  Is `odbc` not compatiple with mysql 8.0?

**Comment by kadler** [comment]
This doesn't really have anything to do with odbc/unixodbc/node-odbc as none of these use OpenSSL libraries at all.

The problem is that Node provides its own version of OpenSSL while MySQL dynamically links to a different set of OpenSSL libraries which are not binary compatible. On Linux, as with many platforms which use the ELF executable format, symbols are bound at runtime, so whoever provides the symbol first wins. I suspect in this case, your Node build is providing the various OpenSSL APIs from OpenSSL 1.1.1d which MySQL will then use instead of those provided by the system's OpenSSL 1.0.2k libraries.

You can verify by looking at the symbol table of you node binary and looking for OpenSSL symbols, eg. `nm -DC /path/to/node | grep SSL`

**Comment by grahamaj** [comment]
@kadler Thanks for your insights. I believe that you are correct. The solution doesn't involve node-odbc at all. As such, I will go ahead and close this issue.
