### ISSUE TITLE
[QUESTION] Db2 for i: what determines if column names are lowercase or uppercase?

### ISSUE THREAD

**Issue by MrTeapot** [markdirish/node-odbc#143]
Hey!

I have a table defined like this: 

```
CREATE  TABLE idp_users (
  idp_id VARCHAR(255) NOT NULL DEFAULT '',
  idp_user_id VARCHAR(120) NOT NULL DEFAULT '',
  usr CHAR(60) NOT NULL DEFAULT ''
) RCDFMT idusrrec;
```

I fetch rows using this sql:
```
SELECT * FROM idp_users
  WHERE idp_id = ? 
  AND idp_user_id = ?
```

All returned rows/objects have their fields in uppercase. Like this:

```
{
IDP_ID: 'abc',
IDP_USER_ID: '123',
USR: 'Test'
} 
```

This makes a huge difference in JS where variables are case sensitive. How can I make them lowercase?

**Comment by markdirish** [comment]
You need a delimited identifier!:

**Comment by MrTeapot** [comment]
Thank you, that solved my problem! I'm closing the issue.
