### ISSUE TITLE
Interfaces for connection and pool

### ISSUE THREAD

**Issue by MiniMarker** [markdirish/node-odbc#144]
Hi.

odbc version: 2.3.5

As of today the typings of the connection function parameters is ether and string or an object. 
the docs (links underneath) state that these object has some defined properties, but these are not reflected in any interface in the odbc package.

Connection: https://www.npmjs.com/package/odbc#parameters
Pool: https://www.npmjs.com/package/odbc#parameters-11

![image](https://user-images.githubusercontent.com/24533038/100592946-16290f80-32f8-11eb-9cad-1568afdbc86f.png)

It would been a nice and small feature to help us developers to more easily use this otherwise great library!

Best Regards!

**Comment by markdirish** [comment]
Got and merged in your PR! Going to close this issue, as the change will be included in the next release.

**Comment by MiniMarker** [comment]
Great! ☺️

**Comment by MiniMarker** [comment]
Any time schedule for the next release?
