### ISSUE TITLE
[Not Sure it's Bug] Unable to resolve module `fs` and `child_process` from `node_modules\blah\blah`

### ISSUE THREAD

**Issue by jihoobyeon** [markdirish/node-odbc#151]
Hello, I'm newbie about TypeScript, and I'm working for a Windows app which reads MS Access file, and do something with its data.
This is my App.ts:
```
import React from 'react'
import { Text, View } from 'react-native'
import odbc from 'odbc'

const mdb = odbc.connect('Driver={Microsoft Access Driver (*.mdb)};Dbq=C:\\Users\\myhome\\Desktop\\test.mdb;Uid=Admin;Pwd=;');
// still incomplete
const App = () =>  { return React.createElement(View, null, React.createElement(Text, null, 'Hello, world!\n')); };
export default App;
```
but while running `react-native run-windows` on terminal, there appers so much `Unable to resolve module 'foo'` errors, so I added some modules by `yarn`, but `fs` and `child_process` are deprecated, and assigned as **Security holding package**, so these were empty, thus not helping to solve the error.

I'm working at:
Microsoft **Windows 10**
JetBrains **Webstorm** 2020.3
**TypeScript 4.1.3**
**Node.js 14.15.4** LTS
**npm 6.14.10**
**Yarn 1**.22.10
**React 16.13.1**
**React Native 0.63.4**
**React Native for Windows** 0.63.18
Microsoft **Access 2019**

Is this a bug **OR** I've been working something wrong?

**Comment by worksofliam** [comment]
Hi @jihoobyeon 

This is a non-issue for node-odbc.

You do not use odbc on the frontend as you do with React.

You're better of creating an express app, which uses odbc to call your database. Then your React app would call your API. This is just one way of doing it.

**Comment by jihoobyeon** [comment]
> Hi @jihoobyeon
> 
> This is a non-issue for node-odbc.
> 
> You do not use odbc on the frontend as you do with React.
> 
> You're better of creating an express app, which uses odbc to call your database. Then your React app would call your API. This is just one way of doing it.

Oh, thanks! I didn't new that since I'm noob here;;
