### ISSUE TITLE
Add `queryTimeout` option to queries/callProcedures/Statements

### ISSUE THREAD

**Issue by markdirish** [markdirish/node-odbc#154]
As part of getting cursor support (allowing fetching of chunks of rows instead of all), an options object has been added on functions that generate a statement handle. See this PR: https://github.com/markdirish/node-odbc/pull/152

@worksofbarry has request that a `queryTimeout` option be added that takes advantage of the `SQL_ATTR_QUERY_TIMEOUT` attribute on statements.

Add the option, create tests, ensure it works.

**Comment by markdirish** [comment]
PR here: https://github.com/markdirish/node-odbc/pull/158

Need to figure how best to pass queryOptions to a statement still.

**Comment by markdirish** [comment]
Should be in the published version, but there doesn't appear to be anything in the README about it. Will fix that up before closing this.

**Comment by CWestBlue** [comment]
@markdirish any timline of when this will be live?

**Comment by markdirish** [comment]
Live for calling connection.query: https://github.com/markdirish/node-odbc#querysql-parameters-options-callback

Still not live on explicit statements and for procedures.

**Comment by CWestBlue** [comment]
@markdirish ok cool thanks. Does this also work with pool.query?

**Comment by markdirish** [comment]
Unfortunately not at the moment, **BUT** there is an open PR. I will ping my reviewer on it.
