### ISSUE TITLE
Binding dates

### ISSUE THREAD

**Issue by shup88** [markdirish/node-odbc#170]
On IBM i 

I am attempting to bind dates.  When I don't bind dates and put the dates directly in the SQL string, it runs with no problem.

**The Following is the summary of what I am attempting:**

```
sql= Select * from wtecdlib.date_conv where dc_date between  ?  and  ?  
bindValues=[ '03/09/2021', '03/09/2021' ]

 statement = await connection.createStatement();
 await statement.prepare(sql);
        if (bindValues.length > 0) {
          await statement.bind(bindValues);
        }
 const returnResults = await statement.execute()

```

**The following is the error:** 

Caught:  [Error: [odbc] Error executing the statement] {
  odbcErrors: [
    {
      state: '22018',
      code: 30200,
      message: '[IBM][System i Access ODBC Driver]Column 1: CWBNL0107 - Converted 10 bytes, 5 errors found beginning at offset 0 (scp=1202 tcp=37 siso=1 pad=4 sl=10 tl=10)'
    },
    {
      state: '22018',
      code: 30019,
      message: '[IBM][System i Access ODBC Driver]Error in assignment.'
    }
  ]
}

**Comment by kadler** [comment]
The IBM i Access ODBC driver requires bound DATE fields be in ISO format: yyyy-mm-dd

**Comment by shup88** [comment]
Thanks
