### ISSUE TITLE
Connection is null. What am I doing wrong?

### ISSUE THREAD

**Issue by jihoobyeon** [markdirish/node-odbc#171]
First, sorry for frequent question.

I made a Node.js CLI app which just reads a table from MS Access file.
This is my `index.js`:
```
import odbc from 'odbc';

odbc.connect('Driver={Microsoft Access Driver (*.mdb)};Dbq=/home/myname/Desktop/sample.mdb;Uid=Admin;Pwd=;', (e, c) =>
{
	c.tables(null, null, 'Table', (e, r) =>
	{
		if(e)
		{
			return;
		}

		console.log(r);
	});
});
```
And this is result:
```
file:///home/myname/Desktop/foo/index.js:5
        c.tables(null, null, 'Table', (e, r) =>
          ^

TypeError: Cannot read property 'tables' of null
    at file:///home/myname/Desktop/foo/index.js:5:4
    at /home/myname/Desktop/foo/node_modules/odbc/lib/odbc.js:29:12
```

So I tested with this code:
```
import odbc from 'odbc';

odbc.connect('Driver={Microsoft Access Driver (*.mdb)};Dbq=/home/myname/Desktop/sample.mdb;Uid=Admin;Pwd=;', (e, c) =>
{
	console.log(c);
});
```
And the result is:
```
null
```
And I tested this:
```
import odbc from 'odbc';

odbc.connect('Driver=foo;Dbq=/home/myname/Desktop/sample.mdb;Uid=Admin;Pwd=;', (e, c) =>
{
	console.log(c);
});
```
And the result is also
```
null
```
Of course the driver `foo` doesn't exist.

I'm keeping reading your API docs, but sadly I can't get any clue.

My spec is:
Windows 10
Node.js 14.15.4 LTS
npm 6.14.10
yarn 1.22.10
JetBrains WebStorm 2020.3.1
Microsoft Access 2019

**Comment by markdirish** [comment]
When the callback function is called, the first thing you should do is check if `e` is null or not:
```
import odbc from 'odbc';

odbc.connect('Driver=foo;Dbq=/home/myname/Desktop/sample.mdb;Uid=Admin;Pwd=;', (e, c) =>
{
  if (e) {
    // handle the error
    console.error(e);
    return;
  }
   
  // The rest of the code here, if no error
});
```

In your case, the error should hold information returned from the driver/driver manager to give us better hints as to what is at issue.

**Comment by jihoobyeon** [comment]
I solved it. my MS Office was 32-bit, so MS Access driver wasn't working in 64-bit Node.js
