### ISSUE TITLE
[BUG] Unicode Data Not Returned Correctly

### ISSUE THREAD

**Issue by DavidRusso** [markdirish/node-odbc#174]
**Describe your system**
* `odbc` Package Version: 2.4.0-beta.1
* ODBC Driver: IBM i Access ODBC Driver 13.64.24.00
* Database Name: DB2 for IBM i
* Database Version: 7.2
* Database OS: IBM i 7.2
* Node.js Version: 14.15.1
* Node.js OS: IBM i / Windows

**Describe the bug**
In 2.4.0-beta.1, Unicode data in query results seems to be missing the first character. For example, a result column value like 'Hello, world' is returned as 'ello, world'.

**To Reproduce**
Run this SQL in Run SQL Scripts in IBM i ACS to create a test table:
```
create table yourlib.helloworld (
  hello vargraphic(50) ccsid 1200
);

insert into yourlib.helloworld values
('Hello, world'),
('مرحبا بالعالم'),
('Привет, мир'),
('你好，世界');
```

Then use this Node.js program to query the table:

```
const odbc = require("odbc");

(async () => {
  const connection = await odbc.connect(
    "Driver=IBM i Access ODBC Driver;System=localhost;uid=you;password=yours"
  );
  console.log(await connection.query(
    "select * from yourlib.helloworld"
  ));
})();
```

The output is:

```
[
  { HELLO: 'ello, world' },
  { HELLO: 'رحبا بالعالم' },
  { HELLO: 'ривет, мир' },
  { HELLO: '好，世界' },
  statement: 'select * from yourlib.helloworld',
  parameters: [],
  return: undefined,
  count: -1,
  columns: [
    {
      name: 'HELLO',
      dataType: -9,
      columnSize: 50,
      decimalDigits: 0,
      nullable: true
    }
  ]
]
```

**Additional context**
This problem does not occur in `odbc` version 2.3.6

**Comment by kadler** [comment]
> For example, a result column value like 'Hello, world' is returned as 'ello, world'.

Sounds like it's gone British!

**Comment by markdirish** [comment]
@DavidRusso thanks for the heads up, will investigate and ensure that it is fixed. Seems to be some sort of "off-by-one" error, so hopefully easily found and fixed.

**Comment by markdirish** [comment]
A missing pair of parens here is the culprit: https://github.com/markdirish/node-odbc/blob/ed6da2942b14e04b72df5d86989a7486ed235352/src/odbc_connection.cpp#L2835

Should read:
```
... + (row_index * (data->columns[column_index]->ColumnSize + 1))
```

Will get a PR pushed in the morning.

**Comment by DavidRusso** [comment]
This is working well for me in 2.4.0-beta.2. Thanks!

**Comment by markdirish** [comment]
2.4.0 is now published and this should be fixed. Feel free to open if it still seems broken!
