### ISSUE TITLE
connect() loginTimeout?

### ISSUE THREAD

**Issue by toddaa** [markdirish/node-odbc#185]
Is the `connect()` `loginTimeout` parameter supposed to return after the number of seconds specified?
```
loginTimeout: How long before the connection process will attempt to connect before timing out, in seconds.
```
I am attempting to write in a fallback for two replicated servers.  My primary connection should usually be there, but since I have a DB slave I figured I may as well use it.

I set the `loginTimeout` parameter to 3 seconds at which I'm changing the `connectionString` parameter and connecting to my other server.  So far it's taking well over a minute before the first connection gives up?  Thoughts?

**Comment by markdirish** [comment]
I'm just a little unclear on how you are setting `loginTimeout`. Are you using the connection options property?

```
const myConnectionObject = { connectionString: 'my;connection;string;', loginTimeout: 3 };
const connection1 = await odbc.connect(myConnectionObject);
// connection 1 fails, change connection string
myConnectionObject.connectionString = 'my;OTHER;connection;string;'
const connection2 = await odbc.connect(myConnectionObject);
```

It seems like that should work. [If you turn tracing on through unixODBC (or ODBC Data Source Administrator)](https://github.com/markdirish/node-odbc/tree/2.4.0#debugging) you should be able to see an entry like: 

```
[ODBC][54985][1620656864.803616][SQLAllocHandle.c][377]
		Entry:
			Handle Type = 2
			Input Handle = 0x5de0070
[ODBC][54985][1620656864.803683][SQLAllocHandle.c][493]
		Exit:[SQL_SUCCESS]
			Output Handle = 0x7fb0cc0008c0
[ODBC][54985][1620656864.803735][SQLSetConnectAttr.c][399]
		Entry:
			Connection = 0x7fb0cc0008c0
			Attribute = SQL_ATTR_LOGIN_TIMEOUT
			Value = 0x3
			StrLen = -5
[ODBC][54985][1620656864.803787][SQLSetConnectAttr.c][691]
		Exit:[SQL_SUCCESS]
```
This at least will let you know that it was set correctly before connecting.

---

If you are trying to set the `loginTimeout` property on the connection itself, it looks like it isn't really wired-up to do anything. It gets set to 5, stored internally, but never sent to ODBC. The idea is that it would be read-only, and give you the value that you set when connecting (or that the driver changed it to in the case that you passed a bad value).

**Comment by toddaa** [comment]
Oh gosh...apologies.  I made a rookie mistake and completely misread the document.  I was passing the timeout value to the constructor itself rather than passing a single object with documented `{ connectionString: 'my;connection;string;', loginTimeout: 3 }` format.  Again my apologies.  After seeing my mistake it works and properly times out at the specified number of seconds.
