### ISSUE TITLE
SQL Data Types

### ISSUE THREAD

**Issue by maxpshaw** [markdirish/node-odbc#19]
Hello,

I tested the same query (column discontinued has data type BIT) on both version 1.4.5 and 2.0.0 and it seems v1 can recognize BIT but not v2; any plan to support it in the future?

1.4.5
```
[ { 'product-code': '171ZFS27', discontinued: false },
  { 'product-code': '75131-TRI', discontinued: false },
  { 'product-code': 'X18096-GALV', discontinued: true },
  { 'product-code': 'DS42152', discontinued: false },
  { 'product-code': 'AA76520', discontinued: false },
  { 'product-code': 'X16420-GREE', discontinued: true },
  { 'product-code': 'X16420-WHIT', discontinued: false },
  { 'product-code': '37404-WHIT', discontinued: false },
  { 'product-code': 'D76480', discontinued: false },
  { 'product-code': '173HFX04', discontinued: true } ]
``` 

2.0.0-4
```
[ { 'product-code': '171ZFS27', discontinued: '0' },
  { 'product-code': '75131-TRI', discontinued: '0' },
  { 'product-code': 'X18096-GALV', discontinued: '1' },
  { 'product-code': 'DS42152', discontinued: '0' },
  { 'product-code': 'AA76520', discontinued: '0' },
  { 'product-code': 'X16420-GREE', discontinued: '1' },
  { 'product-code': 'X16420-WHIT', discontinued: '0' },
  { 'product-code': '37404-WHIT', discontinued: '0' },
  { 'product-code': 'D76480', discontinued: '0' },
  { 'product-code': '173HFX04', discontinued: '1' },
  statement: 'SELECT TOP 10 "product-code", "discontinued" FROM pub.product',
  parameters: [],
  return: undefined,
  count: -1,
  columns: [ { name: 'product-code', dataType: 12 },
    { name: 'discontinued', dataType: -7 } ] ]
```

**Comment by markdirish** [comment]
Hi @maxpshaw ,

Sorry for the late response. 2.0.0-4 _does_ recognize SQL_BIT data type in ODBC. The difference is, in 1.4.5, BIT data types are automatically converted to JavaScript boolean values. There are a number of reasons this is problematic, but a two big ones are:

* Not every bit(1) data field is substituting boolean values
* There are bit data fields with size greater than 1 which cannot be converted

The goal of this odbc connector is to make it as generic and opinion-less as possible. To that end, you might have to create a simple parser for your use cases which checks if a columns data type === -7 (which is SQL_BIT), and if it is an you want to convert it to a boolean, then do something like:

```
for (let i = 0; i < result.length; i++) {
  if (result[i].discontinued === '1') {
    result[i].discontinued = true;
  } else {
    result[i].discontinued = false;
  }
}
```
Then the result will look exactly as it does in v 1.4.5. After I get 2.x humming, I would maybe consider adding a option for something like... singleBitAsBool, which converts BIT(1) fields to booleans automatically.

**Comment by RealJavascriptKid** [comment]
Is there any development on this? In our project we are forced to use 1.4.6 because of number of issues that arise due to this.
