### ISSUE TITLE
[BUG] dependency on deprecated version of node-pre-gyp

### ISSUE THREAD

**Issue by jwllms** [markdirish/node-odbc#192]
I'm trying to install node-red-contrib-odbc in node red runing under docker.
It fails with a dependency on deprecated version of node-pre-gyp that seems to be included here...
It probably should be changed to a dependency on @mapbox/node-pre-gyp

**Comment by markdirish** [comment]
2.4.0 is now published and this should be fixed. Feel free to open if it still seems broken!
