### ISSUE TITLE
[BUG] Potential memory leak with callProcedure

### ISSUE THREAD

**Issue by worksofliam** [markdirish/node-odbc#194]
**Describe your system**
* `odbc` Package Version: 2.3.4
* ODBC Driver: IBM i Access ODBC Driver
* Database Name: Db2 for i
* Database Version: 7.3 & 7.4
* Database OS: IBM i
* Node.js Version: 12.13.1
* Node.js OS: Mac and CentOS

**Describe the bug**

Stack memory continues to grow while the heap stays small.

**Expected behavior**

Stack memory to be not so large. Continue to grow and is not being collected, ever.

**To Reproduce**

Repository created here: https://github.com/SeidenGroup/node-odbc-memory-leak

**Additional context**

![image](https://user-images.githubusercontent.com/3708366/120678014-ab52bf80-c465-11eb-8293-3cf0ba512faa.png)
![image](https://user-images.githubusercontent.com/3708366/120678033-b1e13700-c465-11eb-93f6-312fe8cd55d5.png)

**Comment by NattyNarwhal** [comment]
I've generated some results from Valgrind. One instance had a ^C, other segfaulted.
[one without segfault.txt](https://github.com/markdirish/node-odbc/files/6611540/one.without.segfault.txt)
[one with segfault.txt](https://github.com/markdirish/node-odbc/files/6611541/one.with.segfault.txt)

**Comment by kadler** [comment]
What version of the driver? I see a bunch of mismatched free/delete in there coming from the driver, so it shouldn't be the latest version (since those should now be fixed).

**Comment by kadler** [comment]
Also, based on the info given, looks like the stack isn't growing (not sure how it would unless you heavily recursed), but the heap is almost full.

**Comment by kadler** [comment]
I think some of that can be accounted by the fact nothing is closed. The driver will keep around some resources until you explicitly close/free them. I've modified the source to close after so many executions and to use setTimeout and call itself instead of setInterval (since the interval was too short, causing multiple statements to be executed at the same time, making closing cleanly before exiting difficult).

**Comment by kadler** [comment]
The vast majority of the leak appears to come from QueryData::deleteColumns not deleting the boundRow pointers.

I'm not sure the difference between the deleteColumns and clear, but replacing [this loop](https://github.com/markdirish/node-odbc/blob/master/src/odbc.h#L153-L158) with the [this one](https://github.com/markdirish/node-odbc/blob/master/src/odbc.h#L206-L233) got rid of a ~2M/s leak in this case.

There's also some smaller leaks, which are coming from not deleting some local variables or other pointers passed to async worker classes. I'll send a PR in a bit.

**Comment by kadler** [comment]
FYI, while investigating the leak, I found a segfault in the driver caused by inconsistent handling of variable length data compression. This may be the cause of the segfault @NattyNarwhal ran in to in the original Valgrind runs.

I'd recommend setting DEBUG=1024 in the meantime to disable this type of compression.

**Comment by NattyNarwhal** [comment]
Looks a little better: https://gist.githubusercontent.com/NattyNarwhal/6f6dadf854a6f106383c1f071f2ea0cd/raw/1332b41d0c06cb5bc7b2cb5205fb9409b943fff4/gistfile1.txt

**Comment by kadler** [comment]
You'll likely get cleaner results using some of these changes:

```patch
diff --git a/api/db2.js b/api/db2.js
index 02a3e96..afa2125 100644
--- a/api/db2.js
+++ b/api/db2.js
@@ -7,10 +7,17 @@ module.exports = {
   connect: async function(connectionString) {
     connection = await odbc.connect(connectionString);
   },
-
+  close: async function() {
+    try {
+      await connection.rollback();
+    } catch (e) {
+        console.log('db2', e);
+    }
+    await connection.close();
+  },
   callProcedure: async function(schema, name, bindings) {
     const results = await connection.callProcedure(null, schema, name, bindings);
 
     return results;
   }
-}
\ No newline at end of file
+}
diff --git a/api/pricing.js b/api/pricing.js
index ebf6163..7328f10 100644
--- a/api/pricing.js
+++ b/api/pricing.js
@@ -2,6 +2,9 @@
 const db2 = require('./db2');
 const SCHEMA = process.env.APP_LIB;
 module.exports = class {
+  static async close() {
+    await db2.close();
+  }
   static async getPricing() {
     let customer;
     var productsBuffer;
@@ -15,4 +18,4 @@ module.exports = class {
 
     return callResult[0];
   }
-}
\ No newline at end of file
+}
diff --git a/config/db.js b/config/db.js
index 3330bab..2ca9b16 100644
--- a/config/db.js
+++ b/config/db.js
@@ -6,5 +6,6 @@ module.exports = {
     `Password=${process.env.DB2_PASSWORD}`,
     `DBQ=${process.env.DB2_LIBL}`,
     `Naming=1`,
+    'DEBUG=1024',
   ].join(';'),
 };
diff --git a/index.js b/index.js
index d04806a..e0db5e2 100644
--- a/index.js
+++ b/index.js
@@ -8,11 +8,14 @@ let nextMBThreshold = 700;
 
 setInterval(function () {
   var memMB = process.memoryUsage().rss / 1048576;
+  console.log(memMB);
   if (memMB > nextMBThreshold) {
     heapdump.writeSnapshot()
     nextMBThreshold += 100
   }
-}, 60000);
+}, 6000);
+
+let count = 0;
 
 (async () => {
   console.log(`Connecting to database on ${process.env.DB2_SYSTEM}...`);
@@ -25,12 +28,25 @@ setInterval(function () {
     process.exit(1);
   }
 
-  setInterval(async () => {
+  let func = async () => {
     try {
       await pricing.getPricing();
-      console.log('result');
+      console.log('result', count);
+      count++;
     } catch (e) {
       console.error(e);
     }
-  }, 500);
+      if (count >= 30) {
+         try {
+           await pricing.close();
+         } catch (e) {
+           console.log('index', e);
+         }
+         process.exit();
+      }
+    setTimeout(func, 500);
+  };
+
+  await func();
+
 })();
```

**Comment by NattyNarwhal** [comment]
That indeed does look much better: https://gist.github.com/NattyNarwhal/9097d6b384201ad3201ffd8ec61223ac

**Comment by kadler** [comment]
Ahh, the reason I didn't see the `PiSyDES::ebcdicStrLen` conditional jump issue is I suspect due to my systems being at PWDLVL 3 while yours is 0 or 1.

The convertToClientCodePage leak I figured out. It's an issue in the driver when the descriptor gets reset and it doesn't free a pointer before it wipes it out. Nothing you can do there without a driver testfix.

**Comment by worksofliam** [comment]
@kadler Thanks for your work here.

I think the next step for us is to stop using our own pool and try to use the pool class shipped with ODBC (we didn't want it to close the connections when the query is done). It could be that the pool class we're using is shite.

But, since `callProcedure` isn't part of the base pool class, I need to make a fork of your fork to add it the base.

After that, we'll try that out and see if that solves the problem.

**Comment by worksofliam** [comment]
@kadler Your fixes are looking good. As well as that, we had to replace our custom pool class (which re-used connections) with the odbc pool class, which works but is problematic in the fact that it increased our latency times by almost double. 

We also had to make a fork to add `callProcedure` to the pool class. I plan on making the PR when your PR with the fixes have been merged.

Thanks!

**Comment by NattyNarwhal** [comment]
To add: since the leaking is gone or much, much smaller with the node-odbc pool that closes instead of reuses connections, it makes me suspect the resources that get leaked in our previous situation do get freed, but at the connection tear-down time, either by node-odbc/the driver.

Recommendation to merge #197 stands.
