### ISSUE TITLE
Get results as only one array 

### ISSUE THREAD

**Issue by gianluca1606** [markdirish/node-odbc#195]
Hello guys, i am trying to get started with the package on the ibm i and after a few tries i got everything working.

The only problem i have is that the results of a query are inside an array with other objects like count, parameters, return etc..

In this way it is impossible to return only an array with the results of the query. In order to do that i would always have to slice the array by removing these last objects/arrays i do not want to have.

I do not mind getting these other objects and array but it would be good if i could at least get the results alone and not mixed inside the array with other objects..

Am I doing something wrong or maybe someone does have better solution?

**Comment by McPrescott** [comment]
The object returned from query IS an array of the query results with extra properties. The TypeScript definition is:

```ts
class Result<T> extends Array<T> {
    count: number;
    columns: Array<ColumnDefinition>;
    statement: string;
    parameters: Array<number|string>;
    return: number;
}
```

The only objects that are included in the array are the query results. If you're using the console to print I can see how this could be mistaken for extra items in the array. To avoid printing the extra metadata you can iterate over its elements using any typical array iteration method.

**Comment by markdirish** [comment]
Hi @gianluca1606 ,

Sorry for the late response, I have been on vacation. Like @McPrescott noted, the result object returned is a regular old array that can be iterated over like any other, it just has some additional properties, similar to how "vanilla" arrays have a `length` property. In JavaScript, all Arrays are objects, and in addition to having elements of the array, can have additional properties that don't affect iterating over the elements of the array.

Calls to `.length` on the result object will still return 0 if there were no entries in the result set. Iterating over the array will still only touch the objects in the array (the results from the query). All of the other properties will not be accessed, similar to how `.length` is not accessed. I know it is fairly divergent from _most_ uses of arrays, but it is helpful in the sense that all of the following can return information:

```
results.length // (like a normal array)
results[0]     // (like a normal array)
results.count
results.statement
results.parameters
results.return
```
