### ISSUE TITLE
[BUG] odbc-v2.4.0-win32-x64-napi-v6.tar.gz 404 not found

### ISSUE THREAD

**Issue by Tofuburger** [markdirish/node-odbc#213]
**Describe your system**
* `odbc` Package Version: 2.4.0

**Describe the bug**
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.0/odbc-v2.4.0-win32-x64-napi-v6.tar.gz 

**Expected behavior**
No 404 status

**Logs**
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.0/odbc-v2.4.0-win32-x64-napi-v6.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for odbc@2.4.0 and node@14.17.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.0/odbc-v2.4.0-win32-x64-napi-v6.tar.gz 

Is there any reason why this release package is not avaliable here? odbc-v2.4.0-win32-x64-napi-v6.tar.gz

Thanks

**Comment by T-quila** [comment]
The same problem, I'm waiting for an answer.

**Comment by markdirish** [comment]
I am not sure why the GitHub Action didn't upload all of the different Napi versions into the artifacts for the release. I will have to go digging in a little. In the meantime, I will generate those `.tar`s and get them uploaded for you guys.

**Comment by markdirish** [comment]
They should all be available now. Will work on fixing the GitHub Action so that it automatically uploads all of the Napi versions built for the package. Thanks!
