### ISSUE TITLE
Support for m1/arm64

### ISSUE THREAD

**Issue by worksofliam** [markdirish/node-odbc#223]
Trying to get some existing apps to build on the m1 is proving difficult due to required changes to the `binding.gyp` file to work on the m1/arm64:

```
        [ 'OS == "mac"', {
          'include_dirs': [
            '/usr/local/include',
            '/opt/homebrew/include'
          ],
          'libraries' : [
            '-L/usr/local/lib',
            '-L/opt/homebrew/lib',
            '-lodbc'
          ],
          'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS', 'NAPI_EXPERIMENTAL' ]
        }],
```

Might be worth a conditional to check the arch and then add `/opt/homebrew/include` and `-L/opt/homebrew/lib`.

**Comment by kadler** [comment]
> Might be worth a conditional to check the arch and then add /opt/homebrew/include and -L/opt/homebrew/lib.

I know Brew doesn't support installing x86 version on M1 Macs, but undoubtedly someone's going to do it. Considering /opt/homebrew contains only ARM binaries and /usr/local will contain only x86 brew binaries, we should probably conditionalize it so it doesn't accidentally try to link with the wrong library.

Looking at Node.js it appears they use the standard "arm64" as the arch: https://github.com/nodejs/node/blob/master/common.gypi#L521

**Comment by tibbing** [comment]
@markdirish When is this planned to be released?

**Comment by markdirish** [comment]
Should be live now!

**Comment by pdipax** [comment]
Hi, i get the same error with 2.4.2 release with node 14:

../src/odbc.h:36:10: fatal error: 'sql.h' file not found
#include <sql.h>
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/odbc/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pdipax/Documents/Projects/uniongasgpl-api/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/usr/local/bin/node" "/Users/pdipax/Documents/Projects/uniongasgpl-api/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/pdipax/Documents/Projects/uniongasgpl-api/node_modules/odbc/lib/bindings/napi-v6/odbc.node" "--module_name=odbc" "--module_path=/Users/pdipax/Documents/Projects/uniongasgpl-api/node_modules/odbc/lib/bindings/napi-v6" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /Users/pdipax/Documents/Projects/uniongasgpl-api/node_modules/odbc
gyp ERR! node -v v14.18.2
