### ISSUE TITLE
Handling 0 for SQL_MAX_COLUMN_NAME_LEN

### ISSUE THREAD

**Issue by RyanNeeves** [markdirish/node-odbc#226]
Bug Description:

node-odbc uses the value returned by SQLGetInfo (SQL_MAX_COLUMN_NAME_LEN+1) as the ColumnName buffer size when calling SQLDescribeCol.

When SQL_MAX_COLUMN_NAME_LEN is 0, which according the spec occurs "If there is no maximum length or the length is unknown." the wrapper uses a buffer size of 1.

If the SQL_MAX_COLUMN_NAME_LEN is 0 I believe the tool should make some assumptions about the column name length (maybe 128) and use that instead.

**Comment by markdirish** [comment]
Huh. Thought I had a check for that, but must be some other bit of info. Should be a very easy fix, will get something out soon.

**Comment by markdirish** [comment]
Fixed by #227
