### ISSUE TITLE
[BUG] DB2 for i: data->result_set_end_reached even if cursor not at end, depending on fetchsize

### ISSUE THREAD

**Issue by rfx77** [markdirish/node-odbc#241]
ODBC Driver: IBM i Access ODBC river Windows 13.00.24.00

Depending on the fetchsize the cursor returns wit nodata.
It seems that the maximum record count which can be fetched is 4029 on my query. depending on what fetchsize i set, nodata is returned too early.

with fetchsize 40000 it works
with fetchsize 20000 it doesnot work
with fetchsize 2000 it works

in my opinion the calculation of data->result_set_end_reached in odbc_connection.cpp my be the problem. maybe this check is not working if the resultsize is smaller than the expected fetchsize in some occasions: data->row_status_array[data->fetch_size - 1] == SQL_ROW_NOROW

this is my testcode and afterwards you find the resulting output at the bottom is the create table stmt. the table has about 54000 rows.

```

    const con = await odbc.connect({
        connectionString : 'DSN=APP01-TEST;Uid=xxx;Pwd=xxx;Default Collection=TESTLIB3;',
    })
    let cursor;

    console.log('working:')
    cursor = await con.query('select *  from tbzb', {cursor: true, fetchSize:40000})
    do {
        res = await cursor.fetch();
        console.log(res.length ,cursor.noData)
    } while (!cursor.noData)

    console.log('------------------------------')
    console.log('not working:')
    cursor = await con.query('select *  from tbzb', {cursor: true, fetchSize:20000})
    do {
        res = await cursor.fetch();
        console.log(res.length ,cursor.noData)
    } while (!cursor.noData)

    console.log('------------------------------')
    console.log('not working:')
    cursor = await con.query('select *  from tbzb', {cursor: true, fetchSize:2000})
    do {
        res = await cursor.fetch();
        console.log(res.length ,cursor.noData)
    } while (!cursor.noData)


```

this is the reulting putput:

```

working:
4029 false
4029 false
4029 false
4029 false
4029 false
4029 false
4029 false
4029 false
4029 false
4029 false
4029 false
4029 false
4029 false
1905 false
0 true
------------------------------
not working:
4029 true
------------------------------
not working:
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
2000 false
282 true

```

```

CREATE TABLE TESTLIB3.TBZB ( 
	ZBID INTEGER NOT NULL , 
	PVID INTEGER NOT NULL , 
	MAID INTEGER NOT NULL , 
	ZBDATUM DATE NOT NULL , 
	ZBVON TIME DEFAULT NULL , 
	ZBBIS TIME DEFAULT NULL , 
	ZBANZAHL DECIMAL(4, 2) DEFAULT NULL , 
	ZBSUM DECIMAL(4, 2) DEFAULT NULL , 
	ZBANFAHRT DECIMAL(4, 2) DEFAULT NULL , 
	ZBBESCHREIBUNG FOR COLUMN ZBBESCHR   VARCHAR(4000) ALLOCATE(600) CCSID 1141 DEFAULT NULL , 
	ZBLNWBESTAETIGT FOR COLUMN ZBLNWBES   INTEGER DEFAULT NULL , 
	ZBSTATUS INTEGER DEFAULT NULL , 
	ZBPRINTTAG INTEGER DEFAULT NULL , 
	ZBPRINTTIME FOR COLUMN ZBPRINTTI  TIMESTAMP DEFAULT NULL , 
	ZBPRINTTIMEEXP FOR COLUMN ZBPRINTIEX TIMESTAMP DEFAULT NULL , 
	REID INTEGER DEFAULT NULL , 
	CONSTRAINT TESTLIB3.Q_TESTLIB3_TBZB_ZBID_00001 PRIMARY KEY( ZBID ) )   
	  
	RCDFMT TBZB       ; 



```

**Comment by rfx77** [comment]
When i change line 3455 in odbc_connection.cpp from 
`if (data->simple_binding == true || return_code == SQL_NO_DATA || data->row_status_array[data->fetch_size - 1] == SQL_ROW_NOROW)
`
to

`if (data->simple_binding == true || return_code == SQL_NO_DATA)`

it works. 

So it seems that this implementation does not support retrning fewer rows than expected on intermediate fetches. could you fix this please.

**Comment by rfx77** [comment]
Could somwone fix this bug?

**Comment by rfx77** [comment]
Will there be a fix?

**Comment by ErikJansenIRefact** [comment]
Could someone please explain why issues/bugs are closed even when they are not fixed?
That seems strange isn't it?

**Comment by markdirish** [comment]
Stale bot is probably a little aggressive, but the idea is that sometimes issues become "stale" and are no longer valid.

**Comment by tinathelen** [comment]
I also had an issue with the fetchsize.  Initially it was set to 20000 and only retreived 17671 records out of 2 million.   Then I changed it to 10000 and it processed the 2 million records
