### ISSUE TITLE
[BUG] Potential miscounting of stored procedure argument count?

### ISSUE THREAD

**Issue by NattyNarwhal** [markdirish/node-odbc#248]
Unfortunately, it's been a while since the issue initially happened and when I reported this, since we initially tried a lot of workarounds before resorting to making an issue. I suspect there's a deeper underlying issue, so I think this is the right thing to do. I can try to get on another call w/ the user to confirm details I didn't take at the time.

That said, I do have a unixODBC trace; it's quite long though (though the goods are in theory on SQLProcedures/SQLProcedureColumns), and I'm not sure if it'd need sanitization, so ping me if you need it.

**Describe your system**
* `odbc` Package Version: I believe 2.4.0
* ODBC Driver: IBM i Access
* Database Name: DB2
* Database Version: I believe 7.3
* Database OS: IBM i
* Node.js Version: I believe 12 or 14
* Node.js OS: IBM i

**Describe the bug**

Initially, there was confusion because the SP had a different physical vs. SQL name and that caused [confusion](https://github.com/markdirish/node-odbc/blob/eab309f3c1ed7526875d2bcd5f42f4e07940b180/src/odbc_connection.cpp#L1319), but after locating it, it seems there was issues with [argument count](https://github.com/markdirish/node-odbc/blob/eab309f3c1ed7526875d2bcd5f42f4e07940b180/src/odbc_connection.cpp#L1372).

**Expected behavior**

The stored procedure should be called. Also, the stored procedure argument count mismatch error should probably report the balance of arguments, to make it more obvious what the failure mode is.

The same code called from a JDBC client (i.e. DBeaver) seems to work.

**To Reproduce**
1. Connect to database with options '...'
2. Create database table '...'
3. Run query '...'

**Code**

The stored procedure's typical arguments + type signature:

![image](https://user-images.githubusercontent.com/3161292/151882613-bed50d51-0837-48bf-a757-9a250d24a0e1.png)

There are nine inputs and one output, for a total of ten arguments (confirmed with `select * from qsys2.sysparms where specific_name = 'OFTC_PRD'`). The user code (I don't have right now unfortunately) was confirmed to be passing a ten element array

User's code:

![image](https://user-images.githubusercontent.com/3161292/151884166-55855917-1df1-41b5-9a1f-f81925b0b66b.png)

The resulting error that occured was linked above.

**Comment by markdirish** [comment]
Hey @NattyNarwhal ,

I know its been a while, sorry for the delay. I think I have run into a similar issue with @worksofliam in the past. I think it had something to do with the way that the table function/procedure was created. Do you have any information on how it was created? I was never able to recreate it.

If you aren't working on this anymore, feel free to close the issue, but otherwise I will try to recreate and fix (whether it is at the Node.js `odbc` level or the IBM i driver level)
