### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by snotmare** [markdirish/node-odbc#251]
**Describe your system**
* `odbc` Package Version: I installed off master (github:markdirish/node-odbc#master)
* ODBC Driver: IBM i Access ODBC Driver
* Database Name: DB2
* Database Version: Latest version + patches
* Database OS: Power i
* Node.js Version: 14.17.3
* Node.js OS: Windows

**Describe the bug**
I'm attempting to run a stored procedure that accepts 1 in/out parameter. I get this error...
Code: -104
State: 42000
Message: [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token → was not valid. Valid tokens: ( CL END GET SET TAG CALL DROP FREE HOLD LOCK OPEN WITH ALTER

I wonder if this is related to the recent unicode fix that was pushed to master. Maybe there is another place that needs fixed? This screen shot seems to show an issue with the token...
![image](https://user-images.githubusercontent.com/3671002/152578604-46e4aabc-0cb8-4852-8a0d-2edee1a16a86.png)

**Expected behavior**
I should be able to make a stored procedure call. This call works from IBM's sql scripts...
call GPR3025SP('RE')

**Additional context**
I have figured out how I can install npm modules from a branch. If there is something on your team who would like to work directly with me on this, we could carve out some time and I could quickly test a fix.

We can also provide a dbmon trace or comm trace if needed.

Thanks all!

**Comment by snotmare** [comment]
Good morning @markdirish ! 

Yes, I was able to make a successful call after updating to the latest version. Thanks for fixing this issue!

**Comment by markdirish** [comment]
Closing!
