### ISSUE TITLE
[BUG] Cannot compile on M1 Mac: fatal error: 'sql.h' file not found

### ISSUE THREAD

**Issue by lamuertepeluda** [markdirish/node-odbc#252]
Hi there,

we are having troubles installing node-odbc v2.4.1 on a M1 Mac (MacOS Monterey 12.0.1 Chip Apple M1) with Node 16.13.2 (we also tried 14.8).

We keep getting 

```bash
npm ERR! In file included from ../src/odbc.cpp:22:
npm ERR! ../src/odbc.h:32:10: fatal error: 'sql.h' file not found
npm ERR! #include <sql.h>
```

After running `npm i odbc`

We attempted also a solution like https://stackoverflow.com/questions/70611215/get-sql-h-error-on-macos-12-monterey-sqsrv-and-pdo-sqsrv-drive-installation/70645674#70645674 or putting `/opt/homebrew/Cellar/unixodbc/2.3.9_1/include` in the PATH
 but no luck

Full Logs in the attachment

[npm_logs.txt](https://github.com/markdirish/node-odbc/files/8014312/npm_logs.txt)

**Comment by kadler** [comment]
This should have been fixed by #233, but that commit is not in 2.4.1 (nor any other release yet).

**Comment by lamuertepeluda** [comment]
aww pity. Is there any known ETA? e.g. 2.4.2 release?

**Comment by markdirish** [comment]
Hoping to get it out ASAP, I know several people who want the ARM build. Was hoping to get https://github.com/markdirish/node-odbc/pull/236 in there before 2.4.2, but if it is going to hold it up I guess I can spin up a release before that.

I will see how things look EOD and make 2.4.2 release regardless

**Comment by markdirish** [comment]
Should be live now!
