### ISSUE TITLE
[BUG] Pool connections closed by the server are never reinitialized

### ISSUE THREAD

**Issue by smiziara** [markdirish/node-odbc#255]
**Describe your system**
* `odbc` Package Version: latest
* ODBC Driver: Plex
* Database Name: Plex (Postgres based)
* Node.js Version: 12.22
* Node.js OS: Debian

**Describe the bug**
When using pool connections, if the server just end the session, all connections at the freeConnections array will be in an invalid state. They are still marked as "connected" but they cannot be used.
We have only 5 items at freeConnections, all with connected = true, but every usage attempt on any of them raises the error:
```
code: 2208
message: "[DataDirect][ODBC OpenAccess SDK driver][OpenAccess SDK Client]Internal network error, session aborted, connection closed"
state: "08S01"
```

Im describing this as a Pool error, because its "expected" from the pool to manage this, but its actually an error at the connection level, not detecting this.

**Expected behavior**
Errored connections inside a pool should really close, leaving room for opening new connections in their place.

**To Reproduce**
1. Initialize a pool, run some queries
2. Make connections enter in a Closed state (aborting/closing by the server-side)
3. Run a new query

**Comment by victorhtc** [comment]
Same error happening here after upgrading version 2.3.6 to 2.4.1

```
Error: [odbc] Error executing the sql statement
odbcErrors: [{
  state: 08S01,
  code: 50,
  message: [Amazon][Amazon Redshift] (50) The connection has timed out, please reconnect. Current connection status is: [SQLState 08S01] CONNECTION_BAD
}]
```

**Comment by phpdave** [comment]
Same issue for IBM i

odbc Package Version: latest
ODBC Driver: ibm-iaccess IBM i latest rpm at https://public.dhe.ibm.com/software/ibmi/products/odbc/debs/dists/1.1.0/ibmi-acs-1.1.0.list
Database Name: IBM i DB2 for i
Node.js Version: 18
Node.js OS: Debian GNU/Linux 11 (bullseye)

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/5050955/182997933-b06293f4-e629-4ce0-8c76-de1b5ab95808.png">

What's the work-around?  Don't use pools?

Current work around is a reboot on the linux box

**Comment by kadler** [comment]
Looks like the pool does not check if the connection is still connected before handing it back. There is a "connected" attribute which retrieves the SQL_ATTR_CONNECTION_DEAD property which can be used to check this. This is how ODBC driver manager connection pooling checks for usable connections as documented here: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/driver-manager-connection-pooling

**Comment by phpdave** [comment]
Can we re-open this issue still getting that error message
