### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by colinjw1** [markdirish/node-odbc#257]
**Installing odbc 2.4.2 on IBM i**
* `odbc` Package Version: 2.4.2
* ODBC Driver:
* Database Name:
* Database Version:
* Database OS:
* Node.js Version: 12.22.9
* Node.js OS:

**Bug**
On an ibm i server I was running the command 'npm i odbc' and the package was installed with no issue. I then tried to start my server and the application wouldn't work saying it was missing this file node_modules/odbc/lib/bindings/napi-v6/odbc.node. I then reverted to version 2.4.0 and had no issues and that file was included when I installed odbc with npm.

**To Reproduce**
1. ssh into IBM i server
2. run 'npm i odbc'
3. check if odbc.node file was included

**Additional context**
I followed all the steps on the [odbc npm ](https://www.npmjs.com/package/odbc/v/1.4.10)page and ran into this problem right away.

**Comment by markdirish** [comment]
@colinjw1 is this still an issue with 2.4.4? I'm still unclear what was causing the problem, but hopefully it either downloads the prebuilt binary or installs correctly.

**Comment by colinjw1** [comment]
@markdirish it works now. Thanks!

**Comment by markdirish** [comment]
Closing as @colinjw1 indicated it now works.
