### ISSUE TITLE
mac m1 support with 2.4.2 release

### ISSUE THREAD

**Issue by pdipax** [markdirish/node-odbc#259]
Hi, i get the same error with 2.4.2 release with node 14:

../src/odbc.h:36:10: fatal error: 'sql.h' file not found
#include <sql.h>
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/odbc/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pdipax/Documents/Projects/uniongasgpl-api/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/usr/local/bin/node" "/Users/pdipax/Documents/Projects/uniongasgpl-api/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/pdipax/Documents/Projects/uniongasgpl-api/node_modules/odbc/lib/bindings/napi-v6/odbc.node" "--module_name=odbc" "--module_path=/Users/pdipax/Documents/Projects/uniongasgpl-api/node_modules/odbc/lib/bindings/napi-v6" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /Users/pdipax/Documents/Projects/uniongasgpl-api/node_modules/odbc
gyp ERR! node -v v14.18.2

_Originally posted by @pdipax in https://github.com/markdirish/node-odbc/issues/223#issuecomment-1048808931_

**Comment by worksofliam** [comment]
Do you have unixodbc installed? It worked on my m1 just yesterday.

**Comment by pdipax** [comment]
> Do you have unixodbc installed? It worked on my m1 just yesterday.

Yes, i have installed that by homebrew

**Comment by MasterOdin** [comment]
I was running into this issue, and it ended up being that within my `.yarnrc`, I had:
```
arch x64
# other stuff...
target_arch x64
```
so that electron would install cleanly. Removing this got `node-odbc` to install properly on M1, but of course broke electron as we're not using a new enough version of it yet that supports M1.

**Comment by MasterOdin** [comment]
To add to my own issue, since we still need to target x64 architecture for macOS for other reasons, we are having users install a x64 compatible unixodbc as well and it seems to work. We're using [this post](https://medium.com/mkdir-awesome/how-to-install-x86-64-homebrew-packages-on-apple-m1-macbook-54ba295230f) for how to setup a x86_64 compatible homebrew and then using that to install unixodbc.

**Comment by markdirish** [comment]
If you modify the `binding.gyp` arm64 path to:

```
[ 'target_arch=="arm64"', {
  'include_dirs': [
    '/opt/homebrew/include',
    '/usr/local/include',
  ],  
  'libraries' : [
    '-L/opt/homebrew/lib',
    '-L/usr/local/lib',
    '-lodbc',
  ], 
}],...
```

does it just work? I would think it could use that to find a unixodbc x86 installation, even on an arm system.

**Comment by MasterOdin** [comment]
I'd be way more interested if it was possible to go the other way, using a x86 `node-odbc` installation with an arm64 `unixodbc`. However, I think this use case is probably pretty rare, and we're only in this boot as Oracle is dragging their feet on adding arm64 support for their client (https://github.com/oracle/node-oracledb/issues/1349), and I wouldn't expect you to spend any effort this.

**Comment by jmaver-plume** [comment]
Node.js version 14 and less is not supported. When using version 16, it works correctly.

```
// .nvmrc
v14.17.4


// package.json
{
  "dependencies": {
    "odbc": "^2.4.6"
  }
}


// index.js
const odbc = require('odbc')
console.log('test')
```

Running `npm install` and `node index.js` throws the following error.
```
Library not loaded: /usr/local/opt/unixodbc/lib/libodbc.2.dylib
```

Running `npm install --build-from-source` throws the same error as above.
```
#include <sql.h>
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/odbc/src/odbc.o] Error 1
```

**Comment by hnipps** [comment]
> To add to my own issue, since we still need to target x64 architecture for macOS for other reasons, we are having users install a x64 compatible unixodbc as well and it seems to work. We're using [this post](https://medium.com/mkdir-awesome/how-to-install-x86-64-homebrew-packages-on-apple-m1-macbook-54ba295230f) for how to setup a x86_64 compatible homebrew and then using that to install unixodbc.

For the next person who comes here and gets blocked by Medium's paywall. Here's the one-liner I used to install x86_64 Homebrew on an M-series MacBook Pro - https://stackoverflow.com/questions/72970363/how-do-you-install-the-x86-64-version-of-a-brew-package-on-a-m1-mac#comment139851561_72976961
