### ISSUE TITLE
Charset / encoding issue with node-odbc module

### ISSUE THREAD

**Issue by pbuongiovanni** [markdirish/node-odbc#261]
I installed this Node.js module on my development environment (Windows PC) and on the production environment (Linux Ubuntu 21.10 server).
I’m trying to use this module to access an IBM DB2 data source on AS400 system and everything seems to work fine except for one thing: I perform the same query on the two environments and I find a difference on the result strings. The below example is captured from my production environment, where I use the tool “isql” passing the DSN (ARCLINEA). User id and the pwd have been erased.

![image](https://user-images.githubusercontent.com/102793211/161226619-1b404878-aa52-497c-ada5-8c32f74e81be.png)

As you can see the character ° is correctly extracted and displayed.

When I use my Node.js application (API server) and I perform the same query, I obtain the following string:

![image](https://user-images.githubusercontent.com/102793211/161227727-d3e921f6-bdd7-4ce6-b4a6-c5536ffba07c.png)

and a similar issue if I perform the same query with Postman client:

![image](https://user-images.githubusercontent.com/102793211/161227338-c4b86860-d89a-4efd-a59e-1daea22ace77.png)

It seems there is an encoding change if I use the odbc Node.js module. Is it possible? Do anyone know this issue or has anyone already reported such a problem? I tried to search the internet for any posts regarding this problem but found nothing.

Dan Verweire suggested me to use the IBM specific db2 driver based on this odbc package (https://www.npmjs.com/package/ibm_db2). I tried this but I experienced a compatibility error as below:

**Error: The module '\\?\C:\Development\fda-server\node_modules\ibm_db2\build\Release\odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (C:\Development\fda-server\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Development\fda-server\node_modules\ibm_db2\lib\odbc.js:31:31)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)**

Do anyone have an idea to solve this issue?

Thanks in advance

Piergiorgio

**Comment by kadler** [comment]
IIRC, Node.js doesn't call `setlocale()`, so the application and the driver run in the "C" locale, which only supports ASCII characters. You can override this in the IBM i Access driver using the CCSID connection string keyword, eg. `CCSID=1208`.

**Comment by pbuongiovanni** [comment]
Thank you very much @kadler and @markdirish.
Problem solved with your suggestion.
