### ISSUE TITLE
[BUG] imb db2 as400 Token <END-OF-STATEMENT> was not valid.

### ISSUE THREAD

**Issue by thealexbaron** [markdirish/node-odbc#262]
**Describe your system**
* `odbc` Package Version: 2.4.2
* ODBC Driver: i Series Access ODBC Driver
* Database Name: MSTUPSBTN
* Database Version: 
* Database OS: AS400
* Node.js Version: 12.13.0
* Node.js OS: Windows

**Describe the bug**
While connecting I receive 

```
[IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token <END-OF-STATEMENT> was not valid. Valid tokens: + - AS <IDENTIFIER>.
```

**Expected behavior**
I'm expecting the query `SELECT 1` to return data "1"

**To Reproduce**
1. Connect to the db
2. try to run a query "select 1"

[SQL64.LOG](https://github.com/markdirish/node-odbc/files/8400661/SQL64.LOG)

**Comment by markdirish** [comment]
`SELECT 1` isn't a valid query for Db2 for i (the database in IBM i, formerly known as "AS/400"). You need to select _from_ something. Try"
`SELECT 1 FROM SYSIBM.SYSDUMMY1`
or
`SELECT 1 AS "fieldName" FROM SYSIBM.SYSDUMMY1`

**Comment by thealexbaron** [comment]
This was precisely the issue. Thank you.
