### ISSUE TITLE
Timeout not working on execute, also no documentation for the same. 

### ISSUE THREAD

**Issue by GajenderI** [markdirish/node-odbc#272]
https://github.com/markdirish/node-odbc/blob/a9c7ebcb5e5fab3be6c510267405321b53c6ec05/lib/Statement.js#L93

[Document link](https://github.com/markdirish/node-odbc#executecallback)

**Comment by markdirish** [comment]
Oops, it wasn't implemented inside the `ExecuteAsyncWorker`. I have a PR open now that should fix it.
