### ISSUE TITLE
Cant seem to get it to work with Electron

### ISSUE THREAD

**Issue by asherwin86** [markdirish/node-odbc#273]
**Describe your system**
* `odbc` Package Version: 2.4.4
* Node.js Version: 16.9.1
* Node.js OS: Windows
* Electron Version: 16.0.5 (node.js ver 16.9.1)

**Describe the bug**
Can't get electron app to recognise the odbc.node file.
 Error: Cannot find module '\node_modules\odbc\lib\bindings\napi-v6\odbc.node'
      at webpackEmptyContext (webpack:///./node_modules/odbc/lib_sync?:2:10)
      at Module.eval (webpack:///./node_modules/odbc/lib/odbc.js?:23:79)
      at eval (webpack:///./node_modules/odbc/lib/odbc.js?:101:30)

**To Reproduce**
Create electron app.
add odbc.
import odbc.

**Additional context**
Any help would be great. Not sure exactly why its not able to understand the odbc.node file even though it exists and node-gyp compiles odbc fine.

**Comment by MrTeapot** [comment]
Hey!

I got it working with Electron. 
It will however always depend on the user having the neccessary ODBC drivers installed on their system. 

Are you sure that you are importing the ODBC package in a Node process, and not the browser process?

**Comment by asherwin86** [comment]
I was using a templated vuejs/electron which was causing this issue.
Non templated Electron works fine.
