### ISSUE TITLE
Are integers cast to BigInt by default with node-odbc?

### ISSUE THREAD

**Issue by zeyser** [markdirish/node-odbc#277]
I'm trying to understand why I'm having _BigInt_ for every result. Does some kind of coercion happening under the hood? 
For example I make simple query with DBeaver and with node-odbc
```SELECT appId FROM applications LIMIT 1;``` where appId is _integer_ type
Result with Dbeaver: ```1```
Results with node-odbc: ```1n```
This ```n``` is added for every integer I have. 
I'm not sure that the reason is node-odbc and asking this question because I'm stuck and don't have any ideas.

I'm using ("odbc": "^2.4.4",) for nodejs(nestjs) project with next configurations inside docker
```
FROM node:14.19.3

COPY . /server

WORKDIR /server

#downloading the relevant linux driver for this docker environment
RUN tar vzxf ./docker/nodejs/odbc/vertica-client-11.1.1-0.x86_64.tar.gz && rm ./docker/nodejs/odbc/vertica-client-11.1.1-0.x86_64.tar.gz
RUN apt update && apt install -y unixodbc-dev=2.3.4-1

RUN DOWNLOAD=1 yarn install
RUN yarn global add @nestjs/cli
RUN yarn global add cross-env

ENTRYPOINT ["yarn", "start:dev"]
```
My odbc.ini file inside docker has same configurations as my odbc.ini file on host machine.

P.S. I found out that this behaviour was added in [2.1.0] - 2019-08-02 Added support for JavaScript BigInt binding to SQL_BIGINT
Can I disable somehow this behaviour?

**Comment by markdirish** [comment]
Ah, [here's why](https://www.vertica.com/docs/11.1.x/HTML/Content/Authoring/SQLReferenceManual/DataTypes/Numeric/INTEGER.htm):

> INT, INTEGER, INT8, SMALLINT, TINYINT, and BIGINT are all synonyms for the same signed 64-bit integer data type

So your `INTEGER` field is actually a `BIGINT` field.
