### ISSUE TITLE
Can I require node-odbc without installed unixodbc?

### ISSUE THREAD

**Issue by zeyser** [markdirish/node-odbc#279]
Problem:
- if unixodbc is not installed and `import odbc from 'odbc'` is used; an error appears
```
libodbc.so.2: cannot open shared object file: No such file or directory
            at Runtime._loadModule (node_modules/jest-runtime/build/index.js:893:29)
            at Object.<anonymous> (node_modules/odbc/lib/odbc.js:6:20)
```
Context:
- The error appears when I try to run tests remotely. In my case, odbc itself is mocked and not used, but the import itself is present in the files.

I'm understanding:
- that installing _unixodbc_ will most likely solve the problem, but in my case dealing with infrastructure will be more costly

Is there a way to solve this problem using the settings of the plugin itself or otherwise? What can you advise?

**Comment by amielboim** [comment]
@zeyser 
Did you find a solution to this issue? we block with the same issue...
