### ISSUE TITLE
select with character 'ñ'

### ISSUE THREAD

**Issue by yuguifly** [markdirish/node-odbc#28]
Hello I’have update odbc  from 1.4.5 to 2.1.3 and I have problem to do select with col with character ‘ñ’. I using pool connection now but the same select in version 1.4.5 without pool it Works fine but with 2.1.3 and pool has the next error
`select * from "Table" where "año"='${anho}' and "fecha"='${fecha}'`

'[Pervasive][ODBC Client Interface][LNA][Pervasive][ODBC Engine Interface]Invalid column name: \'año\'.' },
     { state: '42S22',
       code: 0,

is there some option to put an encoding or something like this?

Thank you.

**Comment by markdirish** [comment]
Hi @yuguifly ,

Could you define `'DEBUG'` in your binding.gyp like so:

```
'defines' : [
        'NAPI_EXPERIMENTAL', 'DEBUG'
],
```
And then in your `node_modules/odbc` directory, run `node-gyp rebuild`

Then, rerun your application, and it should print out a bunch of debug messages that should help me diagnose the issue. I suspect it might have something to do with UNICODE.

**Comment by yuguifly** [comment]
Hello, I think I have done the change correctly, these are the error I get now.

This error is col with ñ "campaña"

[Error: "errors": [{ "error": "[Node.js::odbc] QueryAsyncWorker::Execute: Error in ODBC function SQLExecDirect", "message": "[Pervasive][ODBC Client Interface][LNA][Pervasive][ODBC Engine Interface]Error in expression: campaña ", "SQLState": "HY000"},{ "error": "[Node.js::odbc] QueryAsyncWorker::Execute: Error in ODBC function SQLExecDirect", "message": "[Pervasive][ODBC Client Interface][LNA][Pervasive][ODBC Engine Interface]Invalid column name: 'campaña'.", "SQLState": "42S22"}]]

And this is a error where the col have a dot  the col name is “n.palet + n. linea“ 
[Error: "errors": [{ "error": "[Node.js::odbc] QueryAsyncWorker::Execute: Error in ODBC function SQLExecDirect", "message": "[Pervasive][ODBC Client Interface][LNA][Pervasive][ODBC Engine Interface]Syntax Error: select * from "Paleco00" where ""n<< ??? >>.palet + n. linea""='019197801'", "SQLState": "42000"}]]

**Comment by yuguifly** [comment]
Hello, I’have tested put in the string connection encoding=Cp1252 and encoding=UTF-8 and with this solve the problem with dot, but with “ñ” I still have the problema

**Comment by markdirish** [comment]
If you are running on Windows, it now build with `UNICODE` on by default, which I think should solve this issue.

**Comment by markdirish** [comment]
Also (I know this is probably 3 years too late), but 

```
[Pervasive][ODBC Client Interface][LNA][Pervasive][ODBC Engine Interface]Invalid column name: 'campaña'.", "SQLState": "42S22"}]]
```
and
```
Pervasive][ODBC Client Interface][LNA][Pervasive][ODBC Engine Interface]Invalid column name: 'año'.' },
{ state: '42S22',
code: 0,
```
are errors directly from the driver, and seem to indicate the database is receiving the `ñ` correctly, it just doesn't think that `ñ` is a valid character for a column name.
