### ISSUE TITLE
Linux NAPI bindings for 2.4.2

### ISSUE THREAD

**Issue by crung** [markdirish/node-odbc#280]
Hi,

We're still stuck on an old version of Linux (CentOS 7) that doesn't have the right version of GCC to run the latest version of this library. It looks like since 2.4.3 you started providing NAPI for Linux but we're stuck on 2.4.2 and  to make things worse our environment is so locked down that we can't even have node-gyp build from source.

Is there any way you can publish NAPI for 2.4.2 (Linux/Node 16)?

**Comment by ShowmanStone** [comment]
hi, i'm just in a similar situation as GCC version is not enough, how did you fix this eventually? @crung
