### ISSUE TITLE
[ASK] How to get primary key data of a table?

### ISSUE THREAD

**Issue by msojocs** [markdirish/node-odbc#281]
From some reason, I need to get primary key data of a table.
I try to search by the keyword "primary" in this repo and search engine, but I did not get useful infomations.
Does anyone know something about this ?
Thx.

**Comment by kadler** [comment]
For ODBC one would usually use SQLPrimaryKeys, but this connector doesn't have a wrapper for that function (yet?). Many databases have queries you can run or procedures you can call to get that information, though. You'd have to check with your specific database docs how to do that.

**Comment by msojocs** [comment]
> For ODBC one would usually use SQLPrimaryKeys, but this connector doesn't have a wrapper for that function (yet?). Many databases have queries you can run or procedures you can call to get that information, though. You'd have to check with your specific database docs how to do that.

Thanks for your reply.
I am trying to handle the access database (*.mdb), 
but I did not find useful infomation about this by using search engine.
Maybe it does not support to query for the primary key data.

**Comment by markdirish** [comment]
@msojocs , a `primaryKeys` function was added in version 2.4.5 and should be able to get primary keys for a table (if your driver has that functionality implemented). Thanks!
