### ISSUE TITLE
[BUG] Cannot find name 'Void'

### ISSUE THREAD

**Issue by michaeldraftz** [markdirish/node-odbc#285]
**Describe your system**
* `odbc` Package Version: 2.4.5

**Describe the bug**
Typescript type definitions have a typo (Void vs void). Causes tsc to fail.

**Expected behavior**
tsc succeeds

**To Reproduce**
1. import odbc
2. run tsc

**Code**
If applicable, add snippets of code to show:
In odbc.d.ts
Line 183: close(): Promise\<Void>

**Additional context**
 error TS2304: Cannot find name 'Void'

**Comment by PerryRaleigh** [comment]
Actually, I'm not certain I can collaborate via a fork of the repo.  Any guidance here would be greatly appreciated.

Cheers,
Perry

**Comment by markdirish** [comment]
Yep, forks + PRs are very welcome! Will be happy to review and merge if you get something created. We just ask that commits are "signed" with the DCO sign off: https://wiki.linuxfoundation.org/dco#

**Comment by PerryRaleigh** [comment]
Mark, I'm new to using the DCO sign off.  Is that just me putting the following text in my commit message?
Signed-off-by: Perry Raleigh <perry.raleigh@gmail.com>

**Comment by PerryRaleigh** [comment]
@markdirish I think I've got it.  I was just over thinking the whole thing.  Let me know if I've missed the mark (no pun intended) in my commit and pull request.

Cheers

**Comment by markdirish** [comment]
Just published a version 2.4.6, it should be fixed there!
