### ISSUE TITLE
Unsupported datatype: Hyperlink

### ISSUE THREAD

**Issue by JDEfret** [markdirish/node-odbc#29]
Hi,

I only started programming at the start of the month so apologies if any of this is incorrect.

My environment:

Windows 10 Pro version 1903 - 64bit
Node.JS version 12.9.0 - 32bit
MS Access 2013 SP1 - 32bit
.MDB database format

When querying a particular table in my MS Access database no results or errors are displayed. After a lot of investigation I found that if I delete the only field with the datatype of "Hyperlink" then everything works as expected.

I turned on debug and output stops as soon as this field (InvoicePath) with datatype Hyperlink is processed:

[SQLHENV: 02D004D0][SQLHDBC: 02D07448][SQLHSTMT: 02D077A8] ODBCConnection::BindColumns(): Running SQLDescribeCol(StatementHandle = 02D077A8, ColumnNumber = 43, ColumnName = , BufferLength = 64, NameLength = 0, DataType = 0, ColumnSize = 0, DecimalDigits = 0, Nullable = 0)
[SQLHENV: 02D004D0][SQLHDBC: 02D07448][SQLHSTMT: 02D077A8] ODBCConnection::BindColumns(): SQLDescribeCol passed: ColumnName = InvoicePath, NameLength = 11, DataType = -1, ColumnSize = 1073741823, DecimalDigits = 0, Nullable = 1

Please could you investigate?

Much appreciated and thanks

James

**Comment by markdirish** [comment]
This is interesting. Does it just hang? Or does it exit?

What it looks like in the debug output is the column is of dataType -1, which is [SQL_LONGVARCHAR](https://github.com/microsoft/ODBC-Specification/blob/master/Windows/inc/sqlext.h#L470). This is the MS Access ODBC driver telling the ODBC driver manager what the datatype is, and reading about Hyperlinks it seems like a plausible mapping.

The bigger issue is that ColumnSize is 1GB big. When the package is returning data, it gets information about the columns and allocates memory to hold each columns information. For `SQL_LONGVARCHAR`, the code allocates a buffer of ColumnSize + 1 * sizeof(SQLCHAR) (which is 1). So the package is trying to allocated a 1GB buffer of contiguous memory for your process. I'm not sure how much memory Node.js is allocated on your system, but it seems unlikely that it has 1GB contiguous memory. It _should_ be throwing a bad_alloc if that's that case... maybe I could do some more error checking in there.

When you created the Hyperlink field, did you specify a size? I haven't used MS Access in over a decade, but if you specified a max column size for that field, try to reduce it so it isn't so big. If it just defaults to that... I'm not sure what can be done.

**Comment by JDEfret** [comment]
It exits immediately.

I've just discovered that it's doing exactly the same thing for datatype "Long Text".

The "InvoicePath" field is newly created with no data entered. Changing data type to "Short Text" allows the code to run as expected. Changing data type to "Long Text" causes the same crash (I've not re-enabled DEBUG so I'm not sure if dataType is also -1).

When creating the Hyperlink field it just defaults to it - no option to specify a max column size.

Unfortunately I'm stuck with MS Access database for now as I moved the data to SQL (PostgreSQL) but the MS Access GUI fell over with numerous errors and my VBA skills are even less than my Javascript.

If you want me to do any further testing please let me know and thanks for your help so far.

**Comment by halpina** [comment]
Hi guys - by an amazing coincidence, I think I've run into the same problem today also. In my case, I found the problem for a datatype of 'Memo'  which can be up to 65k characters.

**Comment by markdirish** [comment]
I wonder if this is remedied now by the fact that `LONG` data types now use SQLGetData in chunks. Going to close because it is so old and the code has been touched, but feel free to open if it is still an issue.
