### ISSUE TITLE
[BUG] Bad encoded character on connecting HFSQL database

### ISSUE THREAD

**Issue by fybo** [markdirish/node-odbc#291]
Hi Mark,

Before everything, I want to thank you for all the hard-work you do on creating this useful project.

By the way, we've got an issue on connecting an HFSQL database from Windev by ODBC.
Actually, it runs good on most situations but we've a '�' character replacing every special characters with accent like éêàçèï

In the same time, it is well-displayed with RazorSQL by connecting on the same ODBC connector with the same driver.
Same for another projet on Visual Studio C# with the OdbcConnection class which run properly on connecting to the same ODBC connector with the same driver.

Is there a way to fix that by compiling your code differently ?
Or is that a question of deeper encoding that is not caught in the code ?

I'm running your code under Node v16.15.0.
ODBC Driver is available here : https://pcsoft.fr/st/telec/modules-communs-26/wx26_75p.htm

Best Regards,

Fybo

**Comment by kadler** [comment]
Another user found this issue as well and figured out a workaround: https://github.com/markdirish/node-odbc/issues/284#issuecomment-1234379530

**Comment by fybo** [comment]
Thank you buddy, you saved my day ! @kadler
