### ISSUE TITLE
[BUG][URGENT]datetime values not returning after upgrading odbc version 2.3.5 to 2.4.6

### ISSUE THREAD

**Issue by Rohit-Parte** [markdirish/node-odbc#294]
**Describe your system**
* `odbc` Package Version: 2.4.6
* ODBC Driver: windows
* Database Name: Sybase
* Database Version: 5.7
* Database OS: Windows
* Node.js Version: 16
* Node.js OS: Windows

**Describe the bug**
We are not getting any datetime values from database after upgrading odbc version 2.3.5 to 2.4.6. It is working perfectly fine with odbc version 2.3.5. As i checked there are some changes in datetime/timestamp. Please provide option to get datetime values from DB.

datatype for column is datetime, please refer below screenshot
![image](https://user-images.githubusercontent.com/33453608/194092703-fbbfb9ed-18ee-4b94-a5ae-98cf795e003e.png)

![image](https://user-images.githubusercontent.com/33453608/194096500-c43352ad-d503-4424-9d29-62bf5ae23dc3.png)

**Comment by kadler** [comment]
@Rohit-Parte I don't think any maintainers has access to that driver/database to recreate. Can you please provide ODBC traces of it working and failing? See https://github.com/markdirish/node-odbc#debugging for details on how to enable tracing for your platform.
