### ISSUE TITLE
Are DB2 functions supported?

### ISSUE THREAD

**Issue by MicahKimel** [markdirish/node-odbc#299]
I am attempting to use the db2 `TO_DATE` function in my sql, but it seems the `()` are interpreted wrong when using `prepare`.

`await statement.prepare("SELECT TO_DATE('20221129', 'YYYYMMDD') as mydate from mytable;");`

I get the error 
> SQL0104 - Token ; was not valid. Valid tokens: <END-OF-STATEMENT>.

Please let me know if there is a way to use functions, Thanks!!

**Comment by rcronin** [comment]
@MicahKimel - remove your semicolon and try again
