### ISSUE TITLE
Can't install ODBC 2.0.0 version of library on Windows

### ISSUE THREAD

**Issue by JTBS** [markdirish/node-odbc#3]
Hi,
Thank you for upgrading to 2.0.0 with performance fixes. I think it really helps and so far I was able to install and test new version only on Linux.

On Windows, I constantly see below error:
error C2589: '(': illegal token on right side of '::' (compiling source file ..\src\odbc_statement.cpp) 

there are same errors are on all .cpp files in build, as error is coming from odbc.h

If I fix this in my local, I will post the fix.

Thanks

**Comment by rcronin** [comment]
Also seeing this issue as well.

**Comment by markdirish** [comment]
Seems to be related to this issue: https://stackoverflow.com/questions/2561368/illegal-token-on-right-side-of

I am using std::max, which seems to not play nice with Windows. If you add `NOMINMAX` to `binding.gyp` at the 'OS=="win" check like so:

```
[ 'OS=="win"', {
          'sources' : [
            'src/strptime.c',
            'src/odbc.cpp'
          ],
          'libraries' : [
            '-lodbccp32.lib'
          ],
          'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS', 'NOMINMAX' ]
        }],
```

Does that fix it?

**Comment by JTBS** [comment]
Thanks again for getting back on this.

I got the build going fine once I removed "std::" prefix and worked on Windows.

However I could not get it working with binding.gyp approach. Not sure if I made any mistake. If you can paste whole binding.gyp that might worked for you, I can try the same [just in case if I did not get this right].

**Comment by rcronin** [comment]
@markdirish,

In odbc.h, I added the following and it compiled:

`#include <algorithm>`

And on line 149:

`int numParameters = (std::max)(this->bindValueCount, this->parameterCount);`

**Comment by markdirish** [comment]
Pushed v2.0.0-2 to NPM, should fix this issue
