### ISSUE TITLE
First Record from database is malformed / pulling incorrect value

### ISSUE THREAD

**Issue by Kess2311** [markdirish/node-odbc#300]
unixODBC version: `2.3.11` and `2.3.7`
node-odbc version: `2.4.6`
node version: `v18.8.0`

Issue:

Querying a database with `CLOB` data type. Pulling multiple fields (some `VARCHAR`, some `BIGINT`) with no issues. `CLOB` data type returning invalid result for first record. Appears to be some form of last record's value and some other records combined. All other records in result set appear to have correct values. 

Things Tried:

- querying with `isql`. It returns the valid column value
- querying in DBeaver also returns the valid column value

Any additional info I can provide / look into please let me know. Thanks!

**Comment by kadler** [comment]
Can you provide a trace using the steps in https://github.com/markdirish/node-odbc#debugging ?
