### ISSUE TITLE
Batch insert support

### ISSUE THREAD

**Issue by ErikJansenIRefact** [markdirish/node-odbc#317]
Hi,

We currently have an application which needs to insert large sets of records into a SQLServer database.
This can be accomplished either with a "Table Valued Parameter" which is passed to a stored procedure. The "Table Value Parameter" contains a set of records which can be passed from the client to the driver. It's much more efficient then inserting sets row by row.

The SQLServer odbc driver supports this variable type:
https://learn.microsoft.com/en-us/sql/relational-databases/native-client-odbc-table-valued-parameters/table-valued-parameters-odbc?view=sql-server-ver16.

The other (probably more generic approach) is to support the ODBC SQLBulkOperations function:
https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlbulkoperations-function?view=sql-server-ver16.

We are willing to assist in implementing such a feature or donate to someone who's willing to implement this.
Please let us know if this is possible.

Kind regards.

**Comment by markdirish** [comment]
Hi @ErikJansenIRefact ,

This might be a duplicate of #75, but your idea to use `SQLBulkOperations` is new, I was planning on using some batch support. This was actually the next major enhancement I wanted to implement before I got waylaid with other work. I think I actually have a half-complete branch somewhere. Let me take another peek at this and do some rough architectural sketches of what is involved.

**Comment by ErikJansenIRefact** [comment]
Hi Mark,

Would be great. In the meantime we are trying to implement SQLBulkOperations and see how it goes.

**Comment by ErikJansenIRefact** [comment]
Do not close.

**Comment by louia** [comment]
Any news on batch insert support ? @markdirish
