### ISSUE TITLE
IN() query statement not possible with parameters

### ISSUE THREAD

**Issue by p-kuen** [markdirish/node-odbc#32]
The following query throws an error:

```ts
con.query(`SELECT * FROM BDDIVE#DAT.BDKSTP WHERE kstp.KSKST IN (?)`, [[4434, 4438]])
```

It throws the error `[odbc] Error binding parameters`

**Comment by markdirish** [comment]
Which DBMS are you connecting to? Is this a standard syntax, of binding two values in an array to one parameter marker?

As currently written, the package doesn't know how to bind arrays. I'm not sure how it would work... A javascript array contains javascript values, and those values can be converted to their C values for ODBC, but there isn't really a conversion to a C type from an array itself. I don't think ODBC knows of a way to bind multiple values to one marker either.

Have you tried:

```
con.query(`SELECT * FROM BDDIVE#DAT.BDKSTP WHERE kstp.KSKST IN (?, ?)`, [4434, 4438])
```
It does seem like it would be nice and convenient to pass it a list like you have, but I'm not sure how I could get it to work in the conversions.

**Comment by Patcher56** [comment]
> Which DBMS are you connecting to?

I am connecting to a IBM iSeries ODBC database.

> Is this a standard syntax, of binding two values in an array to one parameter marker?

Yes, for example in [the mariadb package](https://www.npmjs.com/package/mariadb) it works like this:
```ts
query(
  `SELECT id, number FROM employees WHERE number IN ?`,
   [managerNumbers]
)
```

> Have you tried:

No, I did not try this, I did a workaround like this:
```ts
query(
    `SELECT KKKK, KKNA1 FROM BDDIVE#DAT.BDKKADP WHERE KKKK IN (${managerNumbers.join(',')})`
  )
```

Do you think, that your workaround is more safe?

**Comment by markdirish** [comment]
I know you said mariadb, but I found something similar in [the mysql documentation](https://www.npmjs.com/package/mysql):

> ...
> Different value types are escaped differently, here is how:
> ...
> * Arrays are turned into list, e.g. ['a', 'b'] turns into 'a', 'b'
> * Nested arrays are turned into grouped lists (for bulk inserts), e.g. [['a', 'b'], ['c', 'd']] turns into ('a', 'b'), ('c', 'd')
> ...

It is theoretically possible to implement something like that, but my concern would be expansion of the parameter markers as well as the parameters. In your query:
```
con.query(`SELECT * FROM BDDIVE#DAT.BDKSTP WHERE kstp.KSKST IN (?)`, [[4434, 4438]])
```
You have 2 values but one marker. You would have to expand the number of markers as well, otherwise there would be a marker/parameter mismatch. I am very very wary to modify queries given to the connector, since, unlike the `mysql` and `mariadb` packages, this package supports any DBMS that has an ODBC driver, and so I can't guarantee _what_ a valid query will look like.

I'll keep this open, but given that there are work-arounds, I wouldn't expect movement for a while.

**Comment by ThePrez** [comment]
@forstie, do you have any thoughts on this one?

**Comment by tibbing** [comment]
Would like to upvote this. Queries like 
```
query(
  `SELECT id, number FROM employees WHERE number IN ?`,
   [managerNumbers]
)
```
works in libraries like `mysql`/`mysql2`, `mssql` etc. The workaround suggested, joining the values to a string does at least not seem to work with a Databricks database. 

Using multiple question marks (`IN (?, ?...)`) works, but is not very clean when you have a dynamic number of values - you'd have to generate the number of questions marks n times, so the query is no longer a constant string.

**Comment by forstie** [comment]
It took a bot to spur me into action.
Whomever owns this query() function could map the values to the appropriate number of question marks in the IN list.
Further, OPEN USING SUBSET could be used to such that there's always 1000 or whatever entries in the IN list, but on each usage, the actual number of IN list entries are identified. That would bridge functional behavior and performance.
