### ISSUE TITLE
Enhancement - provide better column metadata

### ISSUE THREAD

**Issue by phpdave** [markdirish/node-odbc#332]
It would be more informative if the column data type was a string name of the type instead of an integer.  https://github.com/markdirish/node-odbc/blob/4f4f57c70f7182eb00d4b6620c5e22627ea16e98/lib/odbc.d.ts#L5

Microsoft has this on their site:
> Each DBMS defines its own SQL types. Each ODBC driver exposes only those SQL data types that the associated DBMS defines. Information about how a driver maps DBMS SQL types to the ODBC-defined SQL type identifiers and how a driver maps DBMS SQL types to its own driver-specific SQL type identifiers is returned through a call to SQLGetTypeInfo. A driver also returns the SQL data types when describing the data types of columns and parameters through calls to SQLColAttribute, SQLColumns, SQLDescribeCol, SQLDescribeParam, SQLProcedureColumns, and SQLSpecialColumns

So maybe it's just a matter of calling SQLGetTypeInfo?

**Comment by kadler** [comment]
For performance reasons, node-odbc would probably want to call SQLGetTypeInfo with `SQL_ALL_TYPES` and cache the data.

Alternatively, node-odbc could export the ODBC types which you could then check against, eg. `odbc.SQL_CHAR`, `odbc.SQL_DECIMAL`, `odbc.SQL_INTEGER`. Would that be sufficient?

**Comment by phpdave** [comment]
Both sound like a nice improvement.  I think having the string version might make the code simpler in user land.

**Comment by markdirish** [comment]
There are actually _some_ constants that are one the main exported object. If you `require('odbc')` and then print out what you get, it looks like:

```
{
  pool: [Function: pool],
  connect: [Function: connect],
  ODBCVER: 896,
  SQL_COMMIT: 0,
  SQL_ROLLBACK: 1,
  SQL_USER_NAME: 47,
  SQL_PARAM_INPUT: 1,
  SQL_PARAM_INPUT_OUTPUT: 2,
  SQL_PARAM_OUTPUT: 4,
  SQL_VARCHAR: 12,
  SQL_WVARCHAR: -9,
  SQL_INTEGER: 4,
  SQL_SMALLINT: 5,
  SQL_NO_NULLS: 0,
  SQL_NULLABLE: 1,
  SQL_NULLABLE_UNKNOWN: 2,
  SQL_TXN_READ_UNCOMMITTED: 1,
  SQL_TRANSACTION_READ_UNCOMMITTED: 1,
  SQL_TXN_READ_COMMITTED: 2,
  SQL_TRANSACTION_READ_COMMITTED: 2,
  SQL_TXN_REPEATABLE_READ: 4,
  SQL_TRANSACTION_REPEATABLE_READ: 4,
  SQL_TXN_SERIALIZABLE: 8,
  SQL_TRANSACTION_SERIALIZABLE: 8
}
```

Was it it only some of the data types? I probably just exported what I needed for certain tests I was running. Ill see if I can create a quick PR that exports the rest of the types so they are at least available. Of course, if you are given a number, and you have to check against each data type to find the correct one...

I think the best long-term solution is what @kadler indicated, to call SQLGetTypeInfo one time when the connection is made, cache it, then return on the object of the `columns` array in a new property called `typeName` which is the "Data source-dependent data-type name", which is probably what developers _actually_ want

**Comment by markdirish** [comment]
Here's what @kadler and I came up with:

1. Export all of the data types on the `odbc` main exported object. You will be able to to `odbc.SQL_CHAR` and get back `1`
2. Additionally, create an additional property on the `columns` objects returned of `dataTypeName`, which returns the _ODBC_ data type that corresponds to the integer stored in `dataType`
3. Direct people to call the existing `connection.columns()` function if they want to know the native data type name.

Shouldn't take much work, hopefully get a PR out soon
