### ISSUE TITLE
@KerimG performance concerns

### ISSUE THREAD

**Issue by ThePrez** [markdirish/node-odbc#338]
@snotmare 

How did you get that performance gain, if I may ask? I have an extremely simple query with 100 rows and 3 columns and it takes me ODBC connection a whopping 1.556s  while it's instantaneous through `Run SQL Scripts` in ACS.

_Originally posted by @KerimG in https://github.com/markdirish/node-odbc/issues/293#issuecomment-1546992653_

**Comment by KerimG** [comment]
I created a repo with my example code, maybe I'm just doing something wrong. https://github.com/KerimG/example-db2i-node-odbc

This is the output on my Windows system:

```
kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (master)
$ node src
Connecting to IBM i: 382.27ms
Query QSYS2.ACTIVE_JOB_INFO: 3.373s
undefined

kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (master)
$ node src
Connecting to IBM i: 372.445ms
Query QSYS2.ACTIVE_JOB_INFO: 3.385s

kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 381.697ms
Query QSYS2.ACTIVE_JOB_INFO: 3.450s
```

this is via ACS `Run SQL Scripts:
![image](https://github.com/markdirish/node-odbc/assets/9061713/1c581ae1-dd5c-423a-9a4a-618b39654b9d)

```
[ 05/15/2023, 09:38:41 AM ]  Run Selected...   select * from TABLE(QSYS2.ACTIVE_JOB_INFO(DETAILED_INFO=>'ALL')) X WHERE JOB_TYPE<>'SYS' LIMIT 100   Statement ran successfully   (586 ms)   
[ 05/15/2023, 09:45:05 AM ]  Run Selected...   select * from TABLE(QSYS2.ACTIVE_JOB_INFO(DETAILED_INFO=>'ALL')) X WHERE JOB_TYPE<>'SYS' LIMIT 100   Statement ran successfully   (470 ms) 
```

**Comment by kadler** [comment]
So looking at the trace, the cursor is set to a static cursor. This causes internal block fetching to not be used, so each row has to be fetched one at a time from the server, which incurs a lot of network latency overhead.

This should have been fixed by https://github.com/markdirish/node-odbc/pull/311

**Comment by KerimG** [comment]
@kadler Yeah and that change is supposedly already in v2.4.7 , according to https://github.com/markdirish/node-odbc/issues/293#issuecomment-1418372827 but no luck on my end. Is the cursor type perhaps inferred in some way from some Db2 job attribute? Maybe setting it internal block fetching explicitly would help.

**Comment by kadler** [comment]
The cursor type is explicitly being set by the application:

```
t=2298 22:46:50.693 [00]                 ODBC: 0000000000000680: odbcapi.SQLSetStmtAttr Entry
t=2298 22:46:50.693 [00]                 ODBC: odbcattr.attrSetStmtAttr Entry
t=2298 22:46:50.693 [00]                 ODBC: Attribute: 6 (SQL_ATTR_CURSOR_TYPE) Value: 0x3 3
t=2298 22:46:50.693 [00]                 ODBC: odbcattr.attrSetStmtAttr Exit rc=0
```

3 is `SQL_CURSOR_STATIC`.

So it's not just some job attribute that happens to cause it to be static, it's explicitly being set.

**Comment by KerimG** [comment]
@markdirish 

Unfortunately, that didn't make a difference

```
kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ npm i odbc@latest

changed 1 package, and audited 455 packages in 2s

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 380.08ms
Query QSYS2.ACTIVE_JOB_INFO: 3.364s

kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ npm i odbc@beta

changed 1 package, and audited 455 packages in 21s

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 376.562ms
Query QSYS2.ACTIVE_JOB_INFO: 3.295s

kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 380.554ms
Query QSYS2.ACTIVE_JOB_INFO: 3.836s
```

I added the trace to the last query.
[cwbtrace-64-node.exe-17884.log](https://github.com/markdirish/node-odbc/files/11488962/cwbtrace-64-node.exe-17884.log)

**Comment by KerimG** [comment]
That sounds great, @markdirish . Thank you. 
I am doing some more tests and maybe I should try it out on my Mac and on Linux, as well, just for good measure. What I'm a bit confused by is how @snotmare over at https://github.com/markdirish/node-odbc/issues/293#issuecomment-1547063910 seems to have gained a noticeable performance boost after upgrading to 2.4.7. 

Hey @snotmare , If possible, could you perhaps run my testcode at https://github.com/KerimG/example-db2i-node-odbc and share your trace?

**Comment by markdirish** [comment]
@snotmare is running with my prebuilt binaries that are built with the fix, but apparently it was never _really_ integrated.

**Comment by markdirish** [comment]
@KerimG I found the confusion.

Previously (and in 2.4.7) it was fixed for the prepare/bind/execute workflow, but not for calling `.query`. If you try to run:

```javascript
const statement = await connection.createStatement();
await statement.prepare('QSYS2.ACTIVE_JOB_INFO');
const results = statement.execute();
```

Does it improve performance?

**Comment by KerimG** [comment]
@markdirish you rock! That was it!

```
kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 364.232ms
Query QSYS2.ACTIVE_JOB_INFO: 459.783ms

kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 391.955ms
Query QSYS2.ACTIVE_JOB_INFO: 444.901ms

```

And without the `LIMIT 100`, which used to take 12s:

```
kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 372.377ms
Query QSYS2.ACTIVE_JOB_INFO: 2.876s
```
Thanks a ton! Will the change eventually be applied to `query()`?

**Comment by markdirish** [comment]
> Thanks a ton! Will the change eventually be applied to query()?

Hopefully today!

**Comment by markdirish** [comment]
@KerimG about 12 hours late, but 2.4.8 should now be live! Let me know if you see the same performance gains with `.query` on `odbc@latest` and we can then close this issue

**Comment by KerimG** [comment]
Hey @markdirish, this is looking great:

```
kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 389.693ms
Query QSYS2.ACTIVE_JOB_INFO LIMIT 100: 562.081ms

kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 391.046ms
Query QSYS2.ACTIVE_JOB_INFO LIMIT 100: 585.958ms

kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 389.693ms
Query QSYS2.ACTIVE_JOB_INFO LIMIT 100: 562.081ms

kg@FRACTAL MINGW64 ~/code/ibmi-odbc-example (main)
$ node src
Connecting to IBM i: 391.046ms
Query QSYS2.ACTIVE_JOB_INFO LIMIT 100: 585.958ms
```
Thank you and I'm sorry for the hassle!

**Comment by markdirish** [comment]
Glad to hear it! No hassle at all
