### ISSUE TITLE
[BUG]  CONNECTION_CLOSED_ERROR: 'Connection has already been closed!'

### ISSUE THREAD

**Issue by woodinteractive** [markdirish/node-odbc#341]
**Describe your system**
* `odbc` Package Version: ^2.4.2
* ODBC Driver: IBM i Access ODBC Driver
* Database Name: Db2
* Database Version: N/A
* Database OS: IBM i series
* Node.js Version: 16.15.1
* Node.js OS: Mac OS 13.3.1

**Describe the bug**
I am receiving the error `CONNECTION_CLOSED_ERROR: 'Connection has already been closed!'` when trying to query the db. However, I am able to call stored procedures without issue. I have tried to debug, but no output is being created. I'm a bit unsure how to proceed or fix.

**Expected behavior**
I would expect a query to return either a result or an SQL error. 

**To Reproduce**
I followed the installation directions provided for this module and the driver installation instructions from IBM's website: https://ibmi-oss-docs.readthedocs.io/en/latest/odbc/installation.html#macos

**Code**
```TS
const poolConnection: Pool = await pool(
      'DRIVER=IBM i Access ODBC Driver;SYSTEM=<SYSTEM>;UID=<USERID>;PWD=<PASSWORD>;',
    );
    console.log(poolConnection);
```

* The offending code:
```JS
Pool {
  generateConnectPromise: [Function: generateConnectPromise],
  connectionConfig: {
    connectionString: 'DRIVER=IBM i Access ODBC Driver;SYSTEM=172.16.52.1;UID=KTAWEB;PWD=kt@w3bin;',
    connectionTimeout: 0,
    loginTimeout: 0,
    fetchArray: false
  },
  waitingConnectionWork: [],
  isOpen: true,
  freeConnections: [
    Connection {
      CONNECTION_CLOSED_ERROR: 'Connection has already been closed!',
      odbcConnection: ODBCConnection {},
      nativeClose: [Function: close],
      close: [AsyncFunction (anonymous)]
    }
  ],
  connectionsBeingCreatedCount: 9,
  poolSize: 1,
  connectionEmitter: EventEmitter {
    _events: [Object: null prototype] {
      connected: [Function (anonymous)],
      connectionError: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    [Symbol(kCapture)]: false
  },
  reuseConnections: true,
  initialSize: 10,
  incrementSize: 10,
  maxSize: 9007199254740991,
  shrink: true
}
```

Calling a connection on the pool:
```TS
console.log(await poolConnection.connect());
```

```JS
Connection {
  CONNECTION_CLOSED_ERROR: 'Connection has already been closed!',
  odbcConnection: ODBCConnection {},
  nativeClose: [Function: close],
  close: [AsyncFunction (anonymous)]
}
```

When running a query from the connection or directly from the pool I get the same error: 
```TS
const connection = await poolConnection.connect();

const result = await connection.query(QueryString);
```

```TS 
const result = await poolConnection.query(QueryString)
```

```JS
Error: [odbc] Error executing the sql statement
```

**Comment by woodinteractive** [comment]
Turns out the issue was with my library and host. Unfortunately, the error messaging was extremely vague. Regardless, the issue has been resolved.

**Comment by amroczeK** [comment]
Getting a similar intermittent issue using spark driver, will investigate if the upstream service is terminating the connection prematurely.
