### ISSUE TITLE
[feature] Column's metadata should contains table name

### ISSUE THREAD

**Issue by FredoMartini** [markdirish/node-odbc#351]
Hello,

I would be nice if the column's metadata could contain the table name of each column.

Ex : 
```javascript
const result = await cnx.query(`
    SELECT table1.*, table2.*
    FROM table1
    JOIN table2 ON table2.field = table2.field
`);

console.log(result.columns[0].name); // name of the first column (OK)
console.log(result.columns[0].table); // should contain the table name

```

**Comment by kadler** [comment]
This information can be retrieved using [SQLColAttribute](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlcolattribute-function), using attribute `SQL_DESC_TABLE_NAME`.

**Comment by FredoMartini** [comment]
Hello,

Can we reopen this issue ?
