### ISSUE TITLE
[BUG] [IBMi] Unicode strings containing non-Latin Characters are Not Inserted Properly

### ISSUE THREAD

**Issue by DavidRusso** [markdirish/node-odbc#356]
**Describe your system**
* `odbc` Package Version: 2.4.8
* ODBC Driver: IBM i Access ODBC Driver
* Database Name: Db2 for i
* Database Version: 7.3
* Database OS: IBM i 7.3
* Node.js Version: 18, 20
* Node.js OS: IBM i 7.3, Windows 11

**Describe the bug**
Unicode strings containing non-Latin characters (such as Chinese) are not inserted properly into GRAPHIC/VARGRAPHIC Unicode columns.

I'm not sure if this is a bug with `odbc` itself, or with the IBM i Access ODBC driver. On IBM i, I'm using the ODBC driver from the `ibm-iaccess` package version 1.1.0.27-0 provided in the IBM i YUM repos. On Windows I'm using driver version 13.64.26.00 provided by the IBM i ACS application pack. The problem occurs the same way on either setup.

**Expected behavior**
Should be able to insert any Unicode strings.

**To Reproduce**
Run this code on either IBM i or Windows after adjusting the `host`, `user`, and `password` variables to suit:

```
const odbc = require("odbc");

const schema = "qtemp";

const host = "localhost";
const user = "myuser";
const password = "secret";

const connectionString = `Driver=IBM i Access ODBC Driver;SYSTEM=${host};UID=${user};PWD=${password};UNICODESQL=1;CMT=0`;

(async function() {

  const connection = await odbc.connect(connectionString);
  await connection.query(`drop table if exists ${schema}.bug_test`);
  await connection.query(`
    create table ${schema}.bug_test(
      value vargraphic(100) ccsid 1200
    )
  `);
  await connection.query(`insert into ${schema}.bug_test values(?)`, ["Hello, world"]);
  await connection.query(`insert into ${schema}.bug_test values(?)`, ["你好世界"]);
  console.log(await connection.query(`select * from ${schema}.bug_test`));
  await connection.close();

})();
```

You'll see that the Chinese characters get mangled.

The problem occurs at insertion time -- you can confirm this by changing the schema from QTEMP to something else and then querying the table with ACS Run SQL Scripts after running the example program.

The problem occurs the same way regardless of whether the Chinese text is supplied via parameter or embedded into the SQL statement string.

Reading data from the DB works fine -- if the table contains valid Chinese text, it comes out correctly. It just doesn't insert correctly.

**Comment by kadler** [comment]
Can you try adding `CCSID=1208` to the connection string?

**Comment by DavidRusso** [comment]
@kadler , thanks! That did the trick.

As an IBM i veteran going on 20 years, I'm embarrassed that I didn't think of that.  :-)
