### ISSUE TITLE
32 Bit Support

### ISSUE THREAD

**Issue by zachfields** [markdirish/node-odbc#358]
System:

- Windows Server 2019
- System is 64 bit, but ODBC drivers only support 32 bit
- Driver: Timberline Data

Description:
I see there used to be support for 32 bit odbc connections, but when I install node in 32bit, and try to install this node, it does not find the files for the 32 bit.

**Comment by kadler** [comment]
There aren't 32-bit pre-built binaries, so the package would need to be built from source. The following resources should get you started:

https://github.com/nodejs/node-gyp#on-windows
https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules
