### ISSUE TITLE
[BUG] Cannot call stored procedures created with a "specific" name

### ISSUE THREAD

**Issue by brandonp42** [markdirish/node-odbc#368]
**Describe your system**
* `odbc` Package Version: 2.4.8
* unixODBC version: 2.3.9-1
* ODBC Driver: IBM i Access ODBC Driver 1.1.0.27-0
* Database Name: DB2 for i
* Database Version: IBM i 7.4
* Database OS: IBM i 7.4
* Node.js Version: v18.18.2
* Node.js OS: IBM i 7.4

**Describe the bug**
When creating stored procedures with a "specific name" that is different than the regular name, it doesn't seem possible to call it from node-odbc. It either says the stored procedure doesn't exist or it says the number of parameters doesn't match.

**Expected behavior**
It should work the same way as Run SQL scripts - ie it should work.

**Code to Reproduce**
SQL to create and example output from running it:
```
drop procedure if exists NODEODBC.test_specific;
drop procedure if exists NODEODBC.testspec;

CREATE PROCEDURE NODEODBC.test_specific (
  INOUT message       varchar(128)
)
LANGUAGE SQL
SPECIFIC testspec
BEGIN
  set message = 'goodbye';
  return 42;
END;

call NODEODBC.test_specific('hi there');

-- output:
Return Code = 42
Output Parameter #1 (MESSAGE) = goodbye
```

NodeJS code example 1 and output:
```
import odbc from 'odbc';

let conn = await odbc.connect('DSN=*LOCAL');

let parameters = ['hi there'];
let result = await conn.callProcedure(null, 'NODEODBC', 'TEST_SPECIFIC', parameters);
console.log(result);

-- output:
node stored-proc-specific-name.js
node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: [odbc] CallProcedureAsyncWorker::Execute: Stored procedure 'NODEODBC.TEST_SPECIFIC' doesn't exist] {
  odbcErrors: []
}

Node.js v18.18.2
```

NodeJS code example 2 and output:
```
import odbc from 'odbc';

let conn = await odbc.connect('DSN=*LOCAL');

let parameters = ['hi there'];
let result = await conn.callProcedure(null, 'NODEODBC', 'TESTSPEC', parameters);
console.log(result);

-- output:
node stored-proc-specific-name.js
node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: [odbc] The number of parameters the procedure expects and and the number of passed parameters is not equal] {
  odbcErrors: []
}

Node.js v18.18.2
```

**Additional context**
For what it's worth, Run SQL Scripts only works with the "regular" name, it doesn't allow calling the procedure with the "specific" name. This is okay because at least it's possible to run one way or the other, but with node-odbc neither works and is a problem.

I'm not sure but this may be a bug in the actual ODBC driver. Hopefully someone can confirm...

**Comment by brandonp42** [comment]
I've spoken to IBM support about this and right now they agree that it seems to be a bug in the IBM i ODBC driver. I will update this after a fix has been provided.

**Comment by AverittLogan** [comment]
Is there a way to re-open this ticket. It looks like it is an active bug and never resolved It just didnt have comments within 3 months of its initial creation? It appears it was never resolved. Believe I have ran into the same issue recently with overloaded stored procedures.

**Comment by AverittLogan** [comment]
@kadler @bskimball

**Comment by brandonp42** [comment]
@AverittLogan this was a bug in the actual ODBC driver and IBM fixed it. You should only try to call the stored procedure with the long name. Also it’s best to explicitly call your stored procedure with the library/schema. What we do is look it up against the library list and filter by parameter count prior to the call and use that. I can’t look at my code right now but if I remember correctly the catalog view is SYSPROCS.

**Comment by AverittLogan** [comment]
@brandonp42 thanks for the info -- we'll try that out -- appreciate it!
