### ISSUE TITLE
memory problem with DATETIME

### ISSUE THREAD

**Issue by SilverIrbis** [markdirish/node-odbc#37]
Hello! Thank you a lot for this module, but there's a little problem, that I can't resolve.
Electron + node 8.9.3 + odbc 1.4.5 (newest version doesnt work with electron because of node version restriction), I succesfully connected to Interbase 2009 database, but there's a problem, when I'm try to get datetime field - application just consume about 2Gb of memory and crashes. Just SELECT, nothing else.
No problem with other types - string and numbers returning into result pretty fine, but looks like there's a problem with datetime. Not sure if everything ok with code, but how it goes now:

```
let odbc = window.require('odbc')()
let constr = 'DRIVER=Firebird/InterBase(r) driver; UID=SYSDBA; PWD=masterkey; DBNAME=localhost:c:\\Firebird\\database.ibs;charset=win1251'
let connection = odbc.openSync(constr);
let query = "select S_DURATION from SPR where S_KEY = 464"
let stmt = odbc.querySync(query)
```

I have no idea, why this happens. Does it has any solution or suggestion about it and how to fix it?

Thanks for your time a lot.

UPD: solved it with cast datatypes, yet the problem with timestamp stay the same.

**Comment by markdirish** [comment]
Well, this is almost 3 years old (that's 21 years in code-years), so I'm going to close. This repository is exclusively for the 2.x version of the package, and Node.js 8 is no longer supported so I hope the OP has moved on to at least Node.js 12!
