### ISSUE TITLE
Error: not found: gmake

### ISSUE THREAD

**Issue by maxkisung** [markdirish/node-odbc#38]
Getting gmake not found on ibm when running "npm install odbc". 

gyp ERR! build error
gyp ERR! stack Error: not found: gmake
gyp ERR! stack     at getNotFoundError (/QOpenSys/pkgs/lib/nodejs10/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/QOpenSys/pkgs/lib/nodejs10/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/QOpenSys/pkgs/lib/nodejs10/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs10/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs10/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs10/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)

**Comment by markdirish** [comment]
You should be able to `yum install gmake` and then have better luck when trying to install this npm package, but this is really a temporary fix. What I _should_ really do is make it so the pre-built binaries are downloaded, and only compiles from source as a last resort. Unfortunately getting the continuous-integration in place is a bit of work, but I would love to have it done ASAP.

**Comment by maxkisung** [comment]
-bash-4.4$ yum install gmake
ibm                                                                                                                                                                                             | 2.2 kB  00:00:00     

Setting up Install Process
No package gmake available.
Error: Nothing to do

**Comment by maxkisung** [comment]
tried 
yum install make-4.2.1-4.aix6.1.ppc.rpm
with the rpm from https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha

getting -

Setting up Install Process
Examining make-4.2.1-4.aix6.1.ppc.rpm: 1:make-4.2.1-4.ppc
Marking make-4.2.1-4.aix6.1.ppc.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package make.ppc 1:4.2.1-4 will be installed  
--> Processing Dependency: AIX-rpm >= 5.3.0.0 for package: 1:make-4.2.1-4.ppc
--> Processing Dependency: /sbin/install-info for package: 1:make-4.2.1-4.ppc
--> Processing Dependency: info for package: 1:make-4.2.1-4.ppc
--> Processing Dependency: gettext for package: 1:make-4.2.1-4.ppc
--> Processing Dependency: libc.a(shr.o) for package: 1:make-4.2.1-4.ppc     
--> Processing Dependency: libintl.a(libintl.so.8) for package: 1:make-4.2.1-4.ppc
--> Processing Dependency: /sbin/install-info for package: 1:make-4.2.1-4.ppc
--> Finished Dependency Resolution
Error: Package: 1:make-4.2.1-4.ppc (/make-4.2.1-4.aix6.1.ppc)
           Requires: libintl.a(libintl.so.8)
Error: Package: 1:make-4.2.1-4.ppc (/make-4.2.1-4.aix6.1.ppc)
           Requires: gettext
Error: Package: 1:make-4.2.1-4.ppc (/make-4.2.1-4.aix6.1.ppc)
           Requires: AIX-rpm >= 5.3.0.0
Error: Package: 1:make-4.2.1-4.ppc (/make-4.2.1-4.aix6.1.ppc)
           Requires: libc.a(shr.o)
Error: Package: 1:make-4.2.1-4.ppc (/make-4.2.1-4.aix6.1.ppc)
           Requires: info
Error: Package: 1:make-4.2.1-4.ppc (/make-4.2.1-4.aix6.1.ppc)
           Requires: /sbin/install-info
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest


i thought i'd stop here since i don't know what i'm doing.

**Comment by maxkisung** [comment]
ok that worked.  thank you!

yum install make-gnu-4.2-0.ppc64
