### ISSUE TITLE
New feature request:  streaming results

### ISSUE THREAD

**Issue by AlessioQ** [markdirish/node-odbc#41]
I would propose a way to 'stream' the query result without load all results at once.
It's mandatory for query that returns many many records...

In the previus versione of odbc, I use the db.queryResult function that return a delegate with the .fetch method...
Something similira to this should be perfect.

Thanks,
Alessio

**Comment by philippefutureboy** [comment]
I support this feature too :) 👍

**Comment by AlessioQ** [comment]
Hi,
any news about stream (or cursor) capabilities in node-odbc 2?
I need for this feature in order to migrate to new version.

Thanks for all great work done!
Alessio

**Comment by markdirish** [comment]
It will require a bit of a retooling, but I definitely think that it is something that will come for 3.0.0. There are two ways to implement (both of which should eventually be added):

(incoming brain dump)

* The first is what you are asking, where I return some sort of object (maybe a `cursor`) that can call fetch to return rows one at a time. Maybe also a function signature `fetch(count: number)`, where you can fetch up to `count` number of rows at a time using `SQL_ATTR_ROW_ARRAY_SIZE`. It will be up to the user to close the cursor after they are done (or maybe auto-close when `SQLFetch` returns `SQL_NO_DATA`. This would require API changes and quite a bit of internal changes, but I'm working on 3.0.0 in my spare time and having a fetch system like this is something I have tried to account for.

* The second is to use `SQLGetData` to fetch large variable-length data in chunks. Maybe you have a huge binary field, and don't want to wait until it all is retrieved into the C layer (streaming it or something). This will require a lot of thinking how to make the API as simple as possible, but I think it is secondary to the first implementation.

You might be thinking: "Neat! When can we expect it?" And I really have no clue. I wear a few hats, and right now I am wearing a `node-odbc` hat, but adding functionality like this and testing it for 3.0.0 (in addition to other internal changes I have planned) requires a lot of work. Definitely high priority though.

**Comment by AlessioQ** [comment]
thanks Mark,

in my modest opinion the solution 1 should be enough (or at least the first goal).
Thanks in advance for your great work!

**Comment by bencmbrook** [comment]
Hey @markdirish would also love this feature, and may be able to contribute if you need some extra hands here

**Comment by markdirish** [comment]
Hi @bencmbrook ,

This feature was actually added in 2.4.0 as a "cursor". Check out the [documentation here](https://github.com/markdirish/node-odbc#Cursor). Since this issue is one of the older ones, I missed it in my cleanup! Feel free to open another issue if you have a problem with the Cursor class.

**Comment by bencmbrook** [comment]
Ah, nice, thanks @markdirish! Looks great. Is it possible to use the Cursor API with [`.execute()`](https://github.com/markdirish/node-odbc#executecallback) on a Statement object?

**Comment by markdirish** [comment]
Not currently, I was working on where exactly all of the "queryOptions" should be in the statement prepare/bind/execute workflow. Just on execute? That seems logical, I'm just not sure if there will be things added later that should happen earlier in the workflow.

**Comment by bencmbrook** [comment]
Any option would work, but I do like it on `execute` since it affects the return value of that function, and best-matches the existing pattern from `connection.query`

### Connection.query

```js
// Returns result
const result = await connection.query('SELECT * FROM MY_TABLE');

// Returns cursor
const cursor = await connection.query('SELECT * FROM MY_TABLE', { cursor: true, fetchSize: 3 });
```

### Statement.execute

```js
// Returns result
const result = await myStatement.execute();

// Returns cursor
const cursor = await myStatement.execute({ cursor: true, fetchSize: 3 });
```

Would it make sense to pop open a new issue for this?

**Comment by markdirish** [comment]
Sure, that would be great
