### ISSUE TITLE
Add Prebuilt binaries

### ISSUE THREAD

**Issue by abmusse** [markdirish/node-odbc#45]
It would be awesome if we had pre-built binaries instead of building from source each time.

**Comment by abmusse** [comment]
We could use some CI like Jenkins or TravisCI. Also run tests to confirm build was ***really*** successful.

**Comment by markdirish** [comment]
Going to be an on-going effort, but considering the problems and extra hoops that Windows users have to jump through, I would at least like to get Windows 32-bit and 64-bit x86 binaries built for 2.3.0.

Will look into making GitHub actions for building said binaries

**Comment by markdirish** [comment]
This has been in for some time. Windows binaries are now built, and looking at getting Mac binaries in the pipe as well. Still have to build IBM i binaries by hand, however.
