### ISSUE TITLE
Failing to establish a connection to a 32 bit driver

### ISSUE THREAD

**Issue by alilland** [markdirish/node-odbc#47]
OS - Windows 10, Powershell
DB - Actian SQL

I'm getting an error message from the ODBC Driver manager indicating that the `node-odbc` driver is attempting to make connections using 64 bit ODBC. Unfortunately the database driver for my database only supports 32 bit.

I did attempt running powershell and cmd as 32 bit but was still unsuccessful

Are there any examples for connecting to 32 bit?

```javascript
'use strict'

const { series } = require('gulp')
const odbc = require('odbc')

const connection = async done => {
  try {
    console.log('connecting to ODBC driver')
    const conn = await odbc.connect('DSN=SOME_ODBC_NAME')
    console.log('connection established')
    // close connection
    conn.close(msg => {
      console.log('closed connection')
      done()
    })
  } catch (err) {
    console.log('error', err)
  }
}

module.exports = series(
  connection
)
```

```powershell
PS C:\Users\alilland\Documents\dev\forecast-scraper> yarn run devGulp other:odbc                                                                                                                                                             yarn run v1.19.1
$ set NODE_ENV=development& gulp other:odbc
[13:50:41] Using gulpfile ~\Documents\dev\forecast-scraper\gulpfile.js
[13:50:41] Starting 'other:odbc'...
[13:50:41] Starting 'connection'...
connecting to ODBC driver
error [Error: [odbc] Error connecting to the database] {
  odbcErrors: [
    {
      state: 'IM014',
      code: 0,
      message: '[Microsoft][ODBC Driver Manager] The specified DSN contains an architecture mismatch between the Driver and Application'
    }
  ]
}
[13:50:41] Finished 'connection' after 4.71 ms
[13:50:41] Finished 'other:odbc' after 6.71 ms
Done in 1.21s.
PS C:\Users\alilland\Documents\dev\forecast-scraper> 
```

**Comment by markdirish** [comment]
And you are sure your DSN is defined in the 32-bit ODBC Data Sources program (and not the 64-bit one)?

From reading, it also seems that the entire application stack needs to be in 32-bit, so are you running a 32-bit Node.js process as well? I don't know if there is anything inherent in the `odbc` package that is 64-bit, but if you confirm that none of the above issues are causing your problem, I can dig a little deeper.

**Comment by alilland** [comment]
@markdirish it looks like I was calling `node-odbc` with a 64 bit node stack, I downgraded to 32 bit and was able to successfully establish a connection. It looks like I have a new issue, but I will go ahead and open that up under a different thread. thanks!
