### ISSUE TITLE
2nd conn.Close causes process to exit.

### ISSUE THREAD

**Issue by JTBS** [markdirish/node-odbc#5]
I am testing latest 2.0.0 version - without connection Pool. Just connect and execute query.

My scenario: 
**(This issue looks like specific to Multiple DB Connections using 2 Promises. If I execute ONLY one query at a time, close connection is fine. No issues)**

Two DB connections executing two queries at same times and Promise.All waits for both
Both queries complete and I am seeing results read from both.
First DB Connection close works without issues
Second DB conneciton.close command breaks the process - terminating and returning code: 3221225477
FYI; I commented out connection.close and any number of times I am able to run queries.. (This is without using any Connection Pool).

But my concern is if I don't call Close, too many connection will be left open and soon that will be problem.

Below is sample code I am using.. please let me know if you see any issues:

Current code uses callback approach - so left it that way

**odbc.connect**(connString, function(err, conn) {
     **conn.query**(queryText, [], function(err, data) {
    // Check errors etsc

   // Close connection
  //  If I comment, I see no issues with 2 connection/query scenario
 // When there is error, process exits and don't see any additional messages
   **conn.close**((err) => {
  		if (err) {
  			console.log('executeODBCQuery: Connection closed. (ERROR)');
  		} else {
  			console.log('executeODBCQuery: Connection closed');
  		}
  	});
});
});

**Comment by markdirish** [comment]
I'm not sure I follow. Could you post an example with both connections using Promise.All? Something like the minimum amount to get the package to break.

Thanks

**Comment by JTBS** [comment]
markdirish,
Thanks for follow up.
Below is closet sample code I can share:

const workers = [];
workers.push(executeODBCQuery(hostName, dbName, query)) // This created new Connection and executes query - No reuse
Promise.all(workers)
.then(function(data) {
	let resultData = {
		count: 0,
		select: []
	};

	data.map((_) => {
		resultData.count += _.count;		
	});

	resolve(resultData);
})
.catch(function(err) {
	console.log(err);
	reject(err);
});

NOTE: Once Query is executed, if you close DB connection - first one will close fine.. on 2nd Close - even though its NEW 2nd connection - process breaks.

If I don't touch Close - all works great

Thanks for your help.

**Comment by markdirish** [comment]
Issue is 3 years old, we have tests that test this very scenario, and I am 99% sure it is no longer an issue. Closing, but of course feel free to reopen if you still notice its an issue.
