### ISSUE TITLE
node-gyp compile failure during install 

### ISSUE THREAD

**Issue by lburkamper** [markdirish/node-odbc#51]
Receiving the error below while attempting to install on IBM i. Also tried using node v10 instead of node v12, similar error with dependency on odbc.o.d.raw. What am I missing? unixodbc and unixodbc-devel are installed (2.3.4-3), i access ODBC driver is installed, and ‘Development tools’ are installed. 

gmake: Entering directory '/seneca/odbctest/node_modules/odbc/build'
CXX(target) Release/obj.target/odbc/src/odbc.o
In file included from /home/LUANN/.cache/node-gyp/12.13.0/include/node/node_api.h:10:0,
from /seneca/odbctest/node_modules/node-addon-api/napi.h:4,
from ../src/odbc.cpp:19:
/home/LUANN/.cache/node-gyp/12.13.0/include/node/js_native_api.h:39:22: fatal error: opening dependency file ./Release/.deps/Release/obj.target/odbc/src/odbc.o.d.raw: No such file or directory
#define EXTERN_C_END }

We had successfully installed on another server for dev/test and are now trying to install on the clients prod server so the app can be deployed there. Can't figure out what is different?

**Comment by lburkamper** [comment]
Can anyone tell me what is supposed to provide the odbc.o.d.raw file that can't be found? A prior error identified that 5770SS1 option 13 System Openness Includes was missing, so that was recently installed from V7R3 release media. Could there be a problem because option 13 was installed after several TRs/CUM PTFs, and there were fixes to SOI that now need to be reapplied? Grasping at straws.

Note: I've temporarily worked around this issue by downgrading to node v10 and copying a compiled version of odbc from another server on which it had installed correctly (on v10). It works but the other server doesn't belong to the client so this can't be a permanent solution. Still need help fixing this.

**Comment by markdirish** [comment]
Hi LuAnn,

Good to hear from you, just wish it was under better circumstances! I meant to look into this last night, but there was no internet at my house for some reason...

Taking a look at this now

**Comment by markdirish** [comment]
Ok! Could you run:
```
yum list installed coreutils-gnu
```
And see what it outputs? If it gives 8.25-3, you will need to run:
```
yum downgrade coreutils-gnu
```
And make sure that it lists version at 8.25-2. Then hit `y`. 

I ran into this issue on one of my systems but not the other. It looks like we shipped a less-than-happy version of coreutils that is breaking random things in random places... anyways, it was breaking `touch`, which is supposed to create that `odbc.o.d.raw` file in the build process. With the lower version, touch should work (and so this build shouldn't break!).

I'll wait til you say everything is green before closing the issue.

**Comment by lburkamper** [comment]
Hi Mark - yes, it is 8.25-3. However when I try to downgrade I get the message: "Only Upgrade available on package: coreutils-gnu-8.25-4.ppc64   Nothing to do".

**Comment by markdirish** [comment]
ftp://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo/ppc64/

The repo above show we are shipping `-2` and `-4`

Maybe try running:
```
yum clean metadata
```
before running the downgrade command

**Comment by lburkamper** [comment]
The message is now "No package coreutils-gnu-8.25-2 available"?

**Comment by lburkamper** [comment]
Looking at the repo, the versions are labeled with ibmi7.1 and ibmi7.2. Is my 7.3 server not able to see 8.52-2 because it is ibmi7.1 or does that not matter.

**Comment by markdirish** [comment]
The metadata in our repo wasn't synced correctly. In 10-15 minutes, it should be back up and ready for a
```
yum clean metadata
yum downgrade coreutils-gnu-8.25-2
```

**Comment by lburkamper** [comment]
OK I'll check in a while and try again and let you know. Thanks.

**Comment by lburkamper** [comment]
That worked! Thanks so much Mark, this issue is now closed.
