### ISSUE TITLE
Pool maxSize documented but not implemented

### ISSUE THREAD

**Issue by dknapp47** [markdirish/node-odbc#52]
First of all - great package :). This has worked nicely to connect to an iSeries database.

The maxSize property of the pool configuration is documented but does not appear to be implemented. It appears that new connections will be opened with no limits. We would love to have the maxSize property implemented where query would wait until a free connection is available. Short of that, it would probably be good to indicate that maxSize is no implemented in the documentation.

**Comment by grugknuckle** [comment]
After looking at this [file](https://github.com/markdirish/node-odbc/blob/ca5c37727522ea309f90327d59b0eb2938da8969/lib/Pool.js#L211), it seems like the `increasePoolSize` method (on line 211), should first check that 
```javascript
pool.maxSize >= pool.freeConnections.length + count
```
or something, before opening an new connection.

**Comment by markdirish** [comment]
Should be implemented now!

**Comment by ssukienn** [comment]
Correct me if I'm wrong but `shrink` is still not implemented, the field is not used at least.
