### ISSUE TITLE
Working with DBF file

### ISSUE THREAD

**Issue by smiley159** [markdirish/node-odbc#53]
I have a DBF file that contain "thai" character encoded with TIS-620. I am currently able to read the file but the thai characters were not decoded correctly (� got this) . Can anyone please guide me on how to fix this. Thank you!

**Comment by worksofliam** [comment]
@smiley159 this is a known issue and I think this is happening at an ODBC level and is not related to node-odbc.

I am opening a PMR with IBM sometime soon.

**Comment by markdirish** [comment]
@smiley can you try the following for me?:

* Make sure your DSN has the `CCSID=1208` to make sure data transferred through ODBC is in UTF8 (which, along with UTF16, are the only encodings that the JavaScript environment can make strings from).
* Download the 2.3.0 branch, would should have fixes for UTF8 multi-byte characters to fix � for non-ASCII characters: `npm install markdirish/node-odbc#2.3.0`.

Let me know if that fixes it, and if not I can delve deeper.

**Comment by smiley** [comment]
@markdirish Wrong @smiley, you meant @smiley159

**Comment by markdirish** [comment]
Thank you. Strange that sometimes I can @ people in no way related to this package, and other times I can't... 

@smiley159  can you try the following for me?:

* Make sure your DSN has the CCSID=1208 to make sure data transferred through ODBC is in UTF8 (which, along with UTF16, are the only encodings that the JavaScript environment can make strings from).
* Download the 2.3.0 branch, would should have fixes for UTF8 multi-byte characters to fix � for non-ASCII characters: npm install markdirish/node-odbc#2.3.0.

Let me know if that fixes it, and if not I can delve deeper.

**Comment by kadler** [comment]
@markdirish If they have data in TIS-620, then they're definitely not using the Db2 for i database (only supports EBCDIC and UTF-8).

**Comment by kadler** [comment]
Looks like DBF files are for [dBase](https://en.wikipedia.org/wiki/.dbf)

**Comment by kadler** [comment]
I suspect this is related to https://github.com/markdirish/node-odbc/issues/46#issuecomment-619067979

ie. we need to build with `UNICODE` on Windows.

**Comment by markdirish** [comment]
Should be fixed now that `UNICODE` is default on Windows installations.
