### ISSUE TITLE
Opaque Error Messages

### ISSUE THREAD

**Issue by otang** [markdirish/node-odbc#55]
Hello. The error messages from ODBC are quite uninformative. SQL syntax errors are very vague and don't describe where the error occurred or hint to what may be the problem.

### Example error
```
Error: [odbc] Error executing the sql statement
```

How can we access more information about the errors?

**Comment by markdirish** [comment]
Hi @otang,

If the issue originated on the database (or ever in the ODBC connection manager or driver), there should be an `odbcErrors` array on the Error object. Each object on this array should contain:

* `message`
* `code`
* `state`

as returned from the ODBC function `SQLGetDiagRec`. If there isn't an odbcErrors property on the error, then the error likely originated form some JavaScript / C++ error, possible during data conversion. If that's the case, I would love to know about it. In the binding.gyp file, add `DEBUG` to the `defines` list, then recompile. Now when you run your program, youll get a _ton_ of output. This output is helpful to let me know how to fix the issue.

Hopefully that fixes your issues, but also know that I'm not 100% satisfied with how I report errors either... still going through redesigns for a big release/rewrite in early 2020.

**Comment by otang** [comment]
@markdirish thanks, we will try that! Another thing we noticed is many segfaults, seemingly caused also by malformed queries. Is this something you're aware of and is there a better solution for avoiding them?

**Comment by otang** [comment]
@markdirish yea that property, `odbcErrors` doesn't seem to include anything meaningful. Does the v1 release give easier access to errors?

**Comment by markdirish** [comment]
v1 gets errors through the same ODBC functions and in the same situtations, it just places the first ODBC error it encounters as the main "Error" and any other ODBC errors as sub errors. So in essence they _should_ be the same. 

Are you seeing anything in odbcErrors at all? If there is any information there, that is the only information that is returned from your driver or DBMS for the given error. Unfortunately I can't diagnose the database issue: this connector can connect to many DBMSs, and relies on them to give meaningful error information.

Now the segfaults are something that I would hope _wouldn't_ happen in any case and show that something isn't right. What OS, database, and driver are you using?
