### ISSUE TITLE
Auto generated ids

### ISSUE THREAD

**Issue by snotmare** [markdirish/node-odbc#57]
Hello!

We are attempting to switch away from the jdbc and idb connectors in favor of odbc to connect to a DB2 database. I'm looking for a way to get the id value from an auto generated identity column after I execute an insert statement. Is there a way to do that?

For example, one of our tables has an identify column defined like this...
`RECORD_ID FOR COLUMN RCID       DECIMAL(9, 0) GENERATED BY DEFAULT AS IDENTITY ( 
	START WITH 1 INCREMENT BY 1 
	NO MINVALUE NO MAXVALUE 
	NO CYCLE ORDER 
	CACHE 10 ) 
	, `

With the IDB connector, I can get the the new identity value this way...
`results[0][IdbConnection.GENERATED_ID_FIELD]`

The results I get back from statement.execute() looks like this...
`[ statement: 'insert into table(column) values(?) ',
  parameters: [ 'It worked!' ],
  return: undefined,
  count: 1,
  columns: [] ]`

**Comment by markdirish** [comment]
Hi @snotmare ,

I would like to know more about the queries you are running on `idb-connector` and `odbc`. I have recreated this table and I am trying to get the same output but not having success. When I run with `odbc`, I get the result object as you do, but when I run with `idb-connector`, I only get `null` back form INSERT statements.

Either way, I'm not sure there is an 'ODBC way' to get an inserted ID, so it will have to be done by modifying the query. The best way to get the inserted ID from a select statement it to nest it in a `SELECT FROM FINAL TABLE` statement:

```
SELECT * FROM FINAL TABLE(INSERT INTO MYABLE (NAME) VALUES ('Mark'))
```

If you execute the above statement, it will return the inserted row in the result set. This will allow you to get the generated ID through `result[0].RECORD_ID`.

I hope that helps!

**Comment by snotmare** [comment]
Ok, I owe you an apology. Turns out we are running this sql statement immediately following an insert...
`select identity_val_local() as id from sysibm.sysdummy1`

This gives me a result with the id I just generated. This issue can be closed.
