### ISSUE TITLE
Error binding parameters on stored procedure call

### ISSUE THREAD

**Issue by snotmare** [markdirish/node-odbc#62]
Hello! I am running into an error and am having trouble getting enough information to troubleshoot it...
`Error: [odbc] Error binding parameters to the procedure`

I am running this on an IBMi with the following driver...
```
[IBM i Access ODBC Driver]                   
Description=IBM i Access ODBC Driver         
Driver=/QOpenSys/pkgs/lib/libcwbodbc.so      
Threading=0                                  
DontDLClose=1                                
UsageCount=1
```

My javascript code looks like this...
`let result = await connection.callProcedure(null, null, 'GPR5016SP', ['RE', 'Y', '', 'GPACMID', '', '', '', 0, 0]);`

Our system is automatically building the library list for me, so I get the same error whether I qualify the library or not...
`let result = await connection.callProcedure(null, 'DUNC', 'GPR5016SP', ['RE', 'Y', '', 'GPACMID', '', '', '', 0, 0]);`

This is the definition of the stored procedure...
```
	INOUT GACT CHAR(2) , 
	IN IGNO CHAR(1) , 
	IN CUSR CHAR(10) , 
	IN NAME CHAR(10) , 
	IN LIBRARY CHAR(10) , 
	IN "TYPE" CHAR(10) , 
	IN CHARVALUE VARCHAR(2000) , 
	IN DECIMALVALUE DECIMAL(31, 9) , 
	IN INCREMENTVALUE DECIMAL(31, 9) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE RPGLE 
	SPECIFIC DUNC/GPR5016SP 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'DUNC/GPR5016P' 
	PARAMETER STYLE GENERAL ; 
  
COMMENT ON SPECIFIC PROCEDURE DUNC/GPR5016SP 
	IS 'Dynamic Data Area Access' ; 
  
LABEL ON SPECIFIC PROCEDURE DUNC/GPR5016SP 
	IS 'Dynamic Data Area Access' ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE DUNC/GPR5016SP 
TO PUBLIC ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE DUNC/GPR5016SP 
TO QPGMR WITH GRANT OPTION ;
```

I am able to run simple SQL statements. I've tried insert, update, delete, and select, but I have not tried SQL with functions yet. So far SQL works fine.

I can also run this same SQL and stored procedure call when running node on my PC. The driver I'm using from my pc is...
`iSeries Access ODBC Driver`

Our system admin does not see any attempt to make a call when looking through job logs. So, it appears that something within the driver or the odbc code is throwing this error.

What can we do to get more information and narrow down a cause? Is there any specific configuration we should look at? Am I making the javascript call incorrectly?

Thank you for your help!

**Comment by kadler** [comment]
@markdirish can you look at this one?

**Comment by markdirish** [comment]
Hey @snotmare, 

Sorry for the delayed response, I can take a look at this tomorrow. I've noticed a number of issues with stored procedures so hopefully we can get this working a little smoother.

**Comment by snotmare** [comment]
No problem, thank you for your time! We currently use https://www.npmjs.com/package/jdbc for our PCs and https://www.npmjs.com/package/idb on power. We'd love to be able to make this switch!!

**Comment by markdirish** [comment]
Just a little update, I have recreated the issue with a blank stored procedure (SQL, not External) that has the same parameter signature. Works on my Linux machine, doesn't work on my IBM i. I suspect that means it is a driver issue and not an issue with this package, but I will continue digging to see what I can turn up!

**Comment by markdirish** [comment]
It appears that the driver on IBM i is not returning the proper information in calls to `SQLProcedureColumns`:

IBM i:
```
[TODO][SQLHSTMT: 1805f7390] ODBC::BindParameters(): Calling SQLBindParameter(StatementHandle = 1805f7390, ParameterNumber = 0, InputOutputType = 0, ValueType = -8, ParameterType = 0, ColumnSize = 0, DecimalDigits = 0, ParameterValuePtr = 180475650, BufferLength = 6, StrLen_or_IndPtr = 180475e98)
```

Compared to Linux, which returns values for InputOutputType, ParameterType, ColumnSize, and DecimalDigits:
```
[TODO][SQLHSTMT: 0x7f64780009d0] ODBC::BindParameters(): Calling SQLBindParameter(StatementHandle = 0x7f64780009d0, ParameterNumber = 0, InputOutputType = 2, ValueType = -8, ParameterType = 1, ColumnSize = 2, DecimalDigits = 0, ParameterValuePtr = 0x38a2a10, BufferLength = 6, StrLen_or_IndPtr = 0x38a29f8)
```

Next step is to take a look at the IBM i ODBC driver (not open source) to see why this is the case. I will update when I have identified the problem and when it has been fixed.

**Comment by worksofliam** [comment]
It looks like `Pool.query` also does not return the output parameters from the stored procedure in the `parameters` property. I am assuming this issue is related.

**Comment by holterandreasb** [comment]
In case your node.js application is already running on IBM i, I would recommend to use the official npm packages from IBM. In your case you should take a look at idb-connector or idb-pconnector:
https://www.npmjs.com/package/idb-connector
https://www.npmjs.com/package/idb-pconnector

We're using the idb-pconnector package and experience no trouble at all calling stored procedures on our IBM i system.

**Comment by snotmare** [comment]
Thanks @holterandreasb , that's actually what we use today. It has its own set of issues, so we are hoping to switch to odbc.

**Comment by markdirish** [comment]
@kadler and I have tracked down the issue. The data on the procedure columns (things like in/out type, the data type, the number of decimal digits) are stored internally as a `SQLSMALLINT`. In the logic for retrieving them, it tells ODBC to target a `SQL_C_LONG` (4 bytes), then casts it back to `SQLSMALLINT` (2 bytes) instead of `SQLINTEGER`. This is wrong but works fine on little-endian systems (it working fine on Windows and Linux), but breaks on big-endian systems (IBM i), which are just retrieving the wrong 2 bytes.

Luckily, because this is a node-odbc issue I can get a fix out quick. I have a lot of work I want to do before pushing out a release version 2.3.0, so this change will probably get pushed to NPM under a `beta` tag, but can be downloaded and used.

I will try to get something out tonight, or tomorrow at the latest. Will update this thread when something is available.

**Comment by snotmare** [comment]
Sounds great @markdirish , thanks!

**Comment by markdirish** [comment]
Ok @snotmare, it should be pushed up now. The release number is 2.3.0-beta.0. To download it, you will have to tell npm to install the `beta` tag (It defaults to `latest`):

```
npm install odbc@beta
```

Just testing on my 7.3 box, and seems to work much better!

**Comment by snotmare** [comment]
@markdirish I was able to try the beta version on both my pc and our power i. I can call procedures now, woo! Unfortunately, some SQL statements no longer work :/. 

I'm not sure if you want this to be in a separate bug now or maybe this isn't even a bug in your 2.3.0 release. It appears that binding parameters in where clauses no longer work. I can run an insert statement just fine...
`insert into wopmlst(mstext) values(?)`

...but select statements can't find the row (no error that I can see)...
`select mstext from wopmlst where msrcid = ?`

...and updates/delete statements give me an error...
> Error: [odbc] Error executing the statement
> at odbcStatement.execute (/QOpenSys/pkgs/lib/nodejs10/lib/node_modules/odbc/lib/Statement.js:77:20)

When do you think your 2.3.0 release will be ready? We should probably wait for it to come out.

**Comment by ThePrez** [comment]
@snotmare , what commitment control and isolation levels are you using? Did you explicitly commit after the insert?

**Comment by snotmare** [comment]
@ThePrez , we do not specify commitment control or do any explicit commits in our code. I confirmed with our system admin that he is not setting anything on his end either. It must be using the default, though I'm not sure what that is.

From node, our connection string looks like this...
`Driver=IBM i Access ODBC Driver; Naming=1; System=[redacted]; Uid=[redacted]; Pwd=[redacted]`

...and this from my pc...
`Driver=iSeries Access ODBC Driver; Naming=1; System=[redacted]; Uid=[redacted]; Pwd=[redacted]`

**Comment by kadler** [comment]
@snotmare FYI, you should use "IBM i Access ODBC Driver" for future proofing. The "iSeries Access ODBC Driver" is only registered on Windows and will be removed in the future.

This does not affect the issue you're having at all (they're just aliases of the same driver), but it will help future proof your application.

**Comment by snotmare** [comment]
@kadler, does the "IBM i Access ODBC Driver" work on pcs? Last time I tried it, I couldn't get it to work. However, if you think it should, I can try it again.

**Comment by markdirish** [comment]
It should work on Windows, Linux, and IBM i (different versions of the driver). Instructions can be found here: https://github.com/IBM/ibmi-oss-examples/blob/master/odbc/odbc.md#installation-on-windows

I wonder if you now use the 2.3.0 branch on this repo, if you are able to get better error messages. There was a problem before where the ODBC error messages were being deleted off the error object. If it is a problem _with_ the C code, you might now. But if its an ODBC problem, and you are using Promises, you should be able to get better error output now.

**Comment by kadler** [comment]
@snotmare the "IBM i Access ODBC Driver" is registered by the installer for the last few years now. If you have not updated your driver recently, perhaps that's the problem.

Once you're at the new enough level, you can also use cwbodbcreg.exe to switch your existing DSNs to use "IBM i Access ODBC Driver" with `cwbodbcreg /all V7R1`. For testing, you can also unregister older names with `cwbodbcreg /del V5R1` and `cwbodbcreg /del V5R2`.
