### ISSUE TITLE
"Communication link failure" state:"08S01" on a connection pool

### ISSUE THREAD

**Issue by am2222** [markdirish/node-odbc#63]
Hi,
I have question about using `connectionpool` on my server.
I have defined a global variable named connection pool and when I want to query database I use it to query. that works fine but there is a problem that I think after a while being idle the server closes the connections and I face this error.` "Communication link failure" state:"08S01"` which the cause is explained here.
https://www.ibm.com/support/pages/odbc-client-connections-dropping-intermittently-error-communication-link-failure

Is there any way to workaround this problem in node-odbc?

**Comment by worksofliam** [comment]
I am getting this issue too and it's urgent. Even with connectionTimeout as `0`, after some idle time it seems to disconnect the connections. I went ahead and built node-odbc with `DEBUG` mode so we could see the log. You can also see a log of the `pool` object before the debug output.


```
0|app      | Pool {
0|app      |   isOpen: true,
0|app      |   freeConnections: [
0|app      |     Connection { odbcConnection: ODBCConnection {} },
0|app      |     Connection { odbcConnection: ODBCConnection {} },
0|app      |     Connection { odbcConnection: ODBCConnection {} },
0|app      |     Connection { odbcConnection: ODBCConnection {} },
0|app      |     Connection { odbcConnection: ODBCConnection {} },
0|app      |     Connection { odbcConnection: ODBCConnection {} },
0|app      |     Connection { odbcConnection: ODBCConnection {} },
0|app      |     Connection { odbcConnection: ODBCConnection {} },
0|app      |     Connection { odbcConnection: ODBCConnection {} },
0|app      |     Connection { odbcConnection: ODBCConnection {} }
0|app      |   ],
0|app      |   connectionString: 'Driver=IBM i Access ODBC Driver;System=xxx;UID=xxx;Password=xxx',
0|app      |   initialSize: 10,
0|app      |   incrementSize: 10,
0|app      |   maxSize: null,
0|app      |   shrink: true,
0|app      |   connectionTimeout: 0,
0|app      |   loginTimeout: 0
0|app      | }
0|app      |
0|app      | [SQLHENV: 0x4bad8c0][SQLHDBC: 0x7fe28c0173e0] ODBCConnection::Query()
0|app      | [SQLHENV: 0x4bad8c0][SQLHDBC: 0x7fe28c0173e0] ODBCConnection::QueryAsyncWorker::Execute(): Running SQL '
0|app      |       select 
0|app      |       --REDACTED--
0|app      |     '
0|app      | [SQLHENV: 0x4bad8c0][SQLHDBC: 0x7fe28c0173e0] ODBCConnection::QueryAsyncWorker::Execute(): Running SQLAllocHandle(HandleType = SQL_HANDLE_STMT, InputHandle = 0x7fe28c0173e0, OutputHandlePtr = 0x4e5a560)
```

There is a **long** pause here before this error comes out:

```
0|app  | [SQLHENV: 0x4bad8c0][SQLHDBC: 0x7fe28c0173e0] ODBCConnection::QueryAsyncWorker::Execute(): Running SQLAllocHandle(HandleType = SQL_HANDLE_STMT, InputHandle = 0x7fe28c0173e0, OutputHandlePtr = 0x4e5a560)
0|app  | [SQLHENV: 0x4bad8c0][SQLHDBC: 0x7fe28c0173e0][SQLHSTMT: 0x7fe2a0021240] ODBCConnection::QueryAsyncWorker::Execute(): SQLPrepare returned -1
0|app  | ODBC::GetSQLError : handleType=3, handle=0x7fe2a0021240
0|app  | ODBC::GetSQLError : called SQLGetDiagField; ret=0, statusRecCount=1
0|app  | ODBC::GetSQLError : calling SQLGetDiagRec; i=0, statusRecCount=1
0|app  | ODBC::GetSQLError : errorMessage=[IBM][System i Access ODBC Driver]Communication link failure. comm rc=8413 - CWBCO1054 - A user-specified time-out occurred while sending or receiving data, errorSQLState=08S01
0|app  | [SQLHENV: 0x4bad8c0][SQLHDBC: 0x7fe28c0173e0] ODBCConnection::Close()
```

**Comment by am2222** [comment]
@worksofliam so is it a kind of bug or we need to do some special kind of configurations?

**Comment by worksofliam** [comment]
Not sure. Waiting for a maintainer to suggest something :)

**Comment by richardschoen** [comment]
@worksofliam Did you try changing the TCP keepalive settings with CHGTCPA as I suggested ?

**Comment by markdirish** [comment]
https://github.com/markdirish/node-odbc/blob/ca5c37727522ea309f90327d59b0eb2938da8969/src/odbc.cpp#L291

On line 291 of `src/odbc.cpp`, if you change the truth check to `if (options->connectionTimeout >= 0) {`, does that solve the issue? Reading the ODBC documentation, it seems that 0 should be the default, and not setting it should result in the same behaviour as 0, but I could be mistaken.

If that doesn't solve the issue, I think it wouldn't be an issue with the Node.js odbc connector, but with some underlying layer. Could be the driver, but could also be the TCP settings as Richard pointed out. You can use `CFGTCP` and then do option 3 (`Change TCP/IP attributes`) and see what the values for `TCP keep alive`

It seems that TCP keep alives are an issue for other ODBC drivers as well. For example, the Simba Greenplum ODBC driver has DSN options to set TCP keep alive time https://www.simba.com/products/Greenplum/doc/ODBC_InstallGuide/mac/content/odbc/re/configuring/tcpkeepalives.htm. This functionality isn't available on the IBM i ODBC driver, but just shows that TCP timeouts are a thing that can affect ODBC connectivity

**Comment by am2222** [comment]
@markdirish so we just need to set ODBC timeout in driver setting?

**Comment by richardschoen** [comment]
@am2222 The ODBC timeout may work for the client side, but I don't know if the ODBC connections in a connection pool will send keep-alives which means the connections to the DB2 server jobs for each connection can still die even though they may stay active on the i. If you're running a remote server like I believe Liam is, I think the IBMi TCP keep-alive setting (on CHGTCPA) will be very important to set because of WAN/VPN connectivity and potential router timeout issue..  I think the default IBMi keepalive may be 120 minutes. I changed mine to 2 and it resolved issues I was having with JDBC and other connections types like RDI so I'm guessing it will help for you as well.

**Comment by worksofliam** [comment]
@markdirish I am going to make that change, but where is `SQL_ATTR_CONNECTION_TIMEOUT ` coming from? I can't find it in [the IBM i docs](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/cli/rzadpfnsconx.htm) for `SQLSetConnectAttr` - unless it's from somewhere else?

**Comment by markdirish** [comment]
These are the Db2 CLI docs, which is 90-95% the same as ODBC, but for some reason don't seem to have this timeout...

The option can be found at the ODBC docs (which are annoyingly merged with SQL Server docs): https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetconnectattr-function?view=sql-server-ver15

**Comment by markdirish** [comment]
Any changes should just have to be done in JavaScript: Connections have a .connected property that calls SQLGetConnectAttr with the SQL_ATTR_CONNECTION_DEAD option. Returns true if SQL_ATTR_CONNECTION_DEAD returns false (since it makes much more sense for .connected to return true if its... connected). I imagine the code would just check:

 ```
if(!connection.connected) {
// close connection
// open a new connection and add it to pool
}
```

**Comment by worksofliam** [comment]
To me, it looks like `connection.connected` is actually just hanging for an indefinite amount of time if the connection does not exist.

![image](https://user-images.githubusercontent.com/3708366/73870195-a225f400-4819-11ea-8e82-190f60483b65.png)

It's been hanging for 10 minutes now.

![image](https://user-images.githubusercontent.com/3708366/73870203-a5b97b00-4819-11ea-902a-91a2bf19d96f.png)

Some say it's still waiting for a response to this day

**Comment by markdirish** [comment]
@worksofliam 

That sort of makes sense, but I thought it would be smart enough to work around it.

`SQL_ATTR_CONNECTION_DEAD`, according to the ODBC spec, supposed to be a quick check of the last state of the connection. So for most drivers, it doesn't even check the connection, it just checks if you closed it. The previous maintainers of our ODBC driver decided to make ours not follow that, and instead actually send out a packet to see if it is dead. But it seems like it can't actually communicate over a dead connection and is just hanging... I would think it would be smart enough to timeout quickly and say "ok, no connection available", but apparently not. Will look into it more

Ok so maybe I have been understanding connection timeout ALL WRONG. It might be the time and query (or function) waits to complete before giving up:

"An SQLUINTEGER value corresponding to the number of seconds to wait for any request on the connection to complete before returning to the application. The driver should return SQLSTATE HYT00 (Timeout expired) anytime that it is possible to time out in a situation not associated with query execution or login.

If ValuePtr is equal to 0 (the default), there is no timeout."

So... maybe try setting it to like 5, and see if that helps your hang (with your .connected code)

**Comment by am2222** [comment]
@markdirish Hi,
I am using netezza odbc driver, it works fine but I still have this issue with connection pool, IS there any way to check if connections are dead renew pool?

**Comment by NattyNarwhal** [comment]
Just to revisit this, PHP uses in [procedural ODBC](https://github.com/php/php-src/blob/master/ext/odbc/php_odbc.c#L2297-L2299) and [PDO_ODBC](https://github.com/php/php-src/blob/master/ext/pdo_odbc/odbc_driver.c#L392) uses if the data source is read-only; it seems to be the most consistent check, unfortunately. (Procedural ODBC used it for a long time, and I added it to PDO_ODBC based on that.) However, I'm not sure of the methodology used to determine that, so it could be worth looking into alternatives.

**Comment by kadler** [comment]
@NattyNarwhal AFAICT they only use SQL_DATA_SOURCE_READ_ONLY since they want to support ODBC 2-only drivers and SQL_ATTR_CONNECTION_DEAD is ODBC 3.5 (and the comments claim some drivers implement it improperly, which for sure the IBM i Access driver did until the most recent fixpack -- though for our driver SQL_ATTR_CONNECTION_DEAD was in the same boat, problem-wise)

**Comment by richardschoen** [comment]
@kadler Do you think if they update their PASE ODBC driver the issue could go away by using the dead connection check ?

**Comment by kadler** [comment]
As long as the socket is still up, the dead connection check will still report it's good. That is all the ODBC spec says that should happen. If the remote job is dead, though, the socket should get disconnected.

However, if the connection has died between last use, that won't be known at check time, only once the connection is returned to the application and is attempted to be used. Of course, that's how the ODBC spec defines it to work.

> A driver must implement this option efficiently or it will impair the connection pooling performance. Specifically, a call to get [SQL_ATTR_CONNECTION_DEAD] should not cause a round trip to the server. Instead, a driver should just return the last known state of the connection. The connection is dead if the last trip to the server failed, and not dead if the last trip succeeded.

https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/driver-manager-connection-pooling?view=sql-server-ver15

**Comment by richardschoen** [comment]
So Liam's scenario could still occur or will a low query timeout at least reduce latency now ?  

My lowly brain is just trying to understand if the latest stuff actually made anything better.  In my case that's why I have chosen not to use pooling.

I would think a short ping to the server with a short timeout would be a good thing in the dead connection check. 

Just trying to get it right :-)

**Comment by phpdave** [comment]
This issue still seems to be occurring.  Is the workaround to use connection instead of pools?

**Comment by richardschoen** [comment]
I never did achieve clarity on this after my comment from May 26. Maybe @markdirish and @kadler can provide a thought process on whether pooled connections are good or bad. I'm still thinking there may be some issues. 

@phpdave did you change yo non-pooled connections ?  Describe what issue you're seeeing.

**Comment by kadler** [comment]
I think this is basically the same issue as #255 and Mark's suggestion here would be helpful: https://github.com/markdirish/node-odbc/issues/63#issuecomment-581983751

This prevents handing out "known bad" connections, however there could still be issues:
- SQL_ATTR_CONNECTION_DEAD returns the last known connection state. If the socket has been disconnected since it was last used, you still have a problem
- retrieving SQL_ATTR_CONNECTION_DEAD on IBM i Access drivers prior to SP26 can cause hangs since it tries to ping the server*

*if the socket is still up, but the server job is unresponsive for some reason it will hang indefinitely unless socket timeouts are enabled (and socket timeouts were only supported on Windows prior to SP26)

To make this more foolproof, we could add some kind of check on top. Maybe you could register a callback which would be run prior to giving back a connection. From there you could run a validation query or something. Of course, for IBM i if the server job is unresponsive this will still hang without timeouts set.

**Comment by jdukleth** [comment]
Is this issue solved? I am running into it on Node/IBM i as well.

**Comment by phpdave** [comment]
This is what they did in PHP to fix this.  https://github.com/php/php-src/commit/f3a14d1b1ad6cd60570b264f913536c4b28bc10f 

Not sure where in this repo this would go

**Comment by kadler** [comment]
I think changing the default to `SQL_CD_TRUE` would be good. Not sure the benefit of checking the return value, unless you're going to call SQLGetDiagRec or something. Either the call succeeded and set the value appropriately or the call failed and we just assume it's dead.

**Comment by phpdave** [comment]
Ah! sorry you're right this code looks right.  I'll have to keep looking around to try and figure out why I'm getting 

```
State 08S01 Code 10054 [IBM][System i Access ODBC Driver]Communication link failure. comm rc=10054 - CWBC01047 - The IBM i server application disconnected the connection.
```

After the application is running for an entire day and request is made the next day.

**Comment by phpdave** [comment]
Maybe the issue is here:
https://github.com/markdirish/node-odbc/blob/69f49bd4703e569ef01693f4d9241bcdeffa5b00/lib/Pool.js#L253

I think an assumption is being made that the connection that's being popped is a good connection, and perhaps ```connection.connected``` should be checked on the popped connection.  This will make sure the connection is good and if its not, to create a new connection.   

Unless the developer using the node-odbc pool is expected to try catch when they run pool.query and catch the connection error message 
```
State 08S01 Code 10054 [IBM][System i Access ODBC Driver]Communication link failure. comm rc=10054 - CWBC01047 - The IBM i server application disconnected the connection.
```
Then reinstantiate the pool.  Which seems odd to me since I feel the pool should be gracefully handling dead connections without the developer needing to do anything.

```js
 pool = await odbc.pool({
    connectionString,
    initialSize: 5,
    maxSize: 10,
  });
```

**Comment by phpdave** [comment]
Just wanted to mention that TIMEOUTidle appears to have been creating the issue when an stunnel is being used to secure the odbc.  Setting TIMEOUTidle to a high number alleviates the issue until the IBM i is IPL'd.  Also to reproduce the issue one should be able to set that to a low number and see the issue.  

For a handling an IPL this code might work to handle recreating the stunnel and connection
```js
import odbc from 'odbc';
import config from '../config/config';

let pool: odbc.Pool = null;

async function connect(connectionString: string) {
  pool = await odbc.pool({
    connectionString,
    initialSize: 5,
    maxSize: 10,
  });
}

async function query(sql: string, params: any[]) {
    let isTunnelUp = false;
    let result;
    try {
        result = await pool.query(sql, params);
    } catch (error) {
        if (error.odbcErrors[0].message.includes('The IBM i server application disconnected the connection')) {
            console.log('The IBM i server application disconnected the connection and we reconnected the pool and ran the query');
            
            // check if stunnel is up
            const { exec } = require('node:child_process');
            exec('service stunnel4 status', (error, stdout, stderr) => {
                if (error) {
                    console.error(`exec error: ${error}`);
                    return;
                }
                // look at the output for it being up or down
                if (stdout.includes(': running'))
                {
                    isTunnelUp = true;
                }
            });

            if(!isTunnelUp)
            {
                //restart stunnel
                exec('service stunnel4 start', (error, stdout, stderr) => {
                    if (error) {
                    console.error(`exec error: ${error}`);
                    return;
                    }
                    console.log(`stdout: ${stdout}`);
                    console.error(`stderr: ${stderr}`);
                });
            }
            
            config.initializeEnvironment();
            //recreate pool connections
            connect(config.getConnectionString());
            //rerun query on hopefully good new connections
            result = await pool.query(sql, params);
        } else {
            throw error;
        }
    }
}
```

**Comment by rcronin** [comment]
Any updates on this? 

Does anyone have a pattern/method to deal with an IPL or sudden connection loss when using a connection pool?

**Comment by brandonp42** [comment]
FWIW I'm also running into this issue on my Windows development PC from WSL Ubuntu.

**Comment by richardschoen** [comment]
Not sure if this is relevant, but wanted to document it here on this issue as well:  
  
If you get a chance send us screen dumps for:  
```
DSPCLS QSYS/QPWFSERVER
```  
**capture the screen output and post here**   

Also:
```
DSPSBSD QUSRWORK 
Opt 10 - Prestart job entries
Opt 5 on QZDSAOINIT
```
**capture the screen output and post here**  

Main parms I'm looking to see are: ```Maximum number of jobs``` and ```Maximum number of uses```.
My values for both are ```*NOMAX```, but some instances of max number of uses are set to 200 or some other value which might be forcing the connection to reset on you after xxxx uses.

**Comment by jdukleth** [comment]
> FWIW I'm also running into this issue on my Windows development PC from WSL Ubuntu.

I recently started to think it was something to do with WSL too. We have 3 developers all running WSL Ubuntu and the disconnects happen for all of us but once we put code into production (regular Ubuntu) it does not have this issue. Stable as can be.

**Comment by richardschoen** [comment]
Interesting.  Are you using the default Ubuntu image with WSL ? 

I am willing to try recreating the issue if someone can provide a sample app that's pre-built with some data that I can run against WSL that fails consistently.

**Comment by jdukleth** [comment]
We're using version 2 of WSL with the default Ubuntu image.

Steps to reproduce:

- Install WSL2 Ubuntu default image on your Windows 10/11 box
- Install Node and NPM (we install with NVM)
- `git clone https://github.com/jdukleth/ibmi-express-odbc-skeleton.git`
- `cd ibmi-express-odbc-skeleton`
- `npm i`
- change the `IBM_HOSTNAME` variable in `.env` file to be your IBM i ODBC DSN
- `npm run dev`
- visit `localhost:3030/test` in browser or PostMan (you'll see some random IBM i subsystem rows if successful)
- wait 2+ hours of inactivity for the issue to occur (we haven't been able to pin down the exact time. sometimes we come back the next day and its disconnected, sometimes it seems to happen within an hour. usually after 3 hours of inactivity it will be disconnected)
- visit `localhost:3030/test` in browser or PostMan again and if it hangs then it has happened and you can go back to your terminal to see the 08S01 error

**Comment by richardschoen** [comment]
@jdukleth One other question.  Are you simply installing and running the node app from the Ubuntu/WSL2 command line or are you logging into a GUI desktop and opening a terminal and running the app ?

On mine I installed xrdp so I can RDP to a desktop.

**Comment by richardschoen** [comment]
@jdukleth - I induced the error right away by hammering the IBM i communications thread jobs just to see what happens. The browser hangs indefinitely.  

Is this what you were seeing ?

**Comment by richardschoen** [comment]
OK this doesn't solve the issue with a busted connection link, but it does prevent your app from locking up when that happens allowing you to potentially regenerate your pool.

I am not a Node expert, but you had no error handling, so I added a ```try/catch``` which in my example returns a ```Database error``` string on errors.  

I'm guessing on DB error you were not returning a response thus simulating an app lockup when in reality you just needed to handle the error that occurred.

I'm thinking that if you get a deadpool connection, you can possibly call a method to regenerate the pool or revert to a single use connection perhaps. 

Food for thought.

```
import { db2Query } from '../../../utils/db2Database.js'

export const test = async () => {
  
  try {
    const sql = getSql()
    const params = []
    const results = await db2Query(sql, params)

    return results
  } catch(e) {  
	return "Database error"  
  }
}

const getSql = () => {
  return `
    SELECT * FROM qiws.qcustcdt
    LIMIT 5
  `
}
```

**Comment by jdukleth** [comment]
> @jdukleth One other question. Are you simply installing and running the node app from the Ubuntu/WSL2 command line or are you logging into a GUI desktop and opening a terminal and running the app ?
> 
> On mine I installed xrdp so I can RDP to a desktop.

It's all command-line Ubuntu. We don't use Linux GUI anywhere.

How did you hammer the connection to get it to cause it? Was it the same error? Spamming it doesn't seem to do it on my end.

We are handling the responses better in our actual app but once the connection is dead we end up having to restart our `npm run dev` locally to fix it. Your suggestion to have code to automatically regenerate the connection is good, we'll probably do that, thanks.

It would be good to solve the core issue but if this is only happening inside WSL (is anyone having it happen elsewhere?) then it's not a big problem. I doubt people are running WSL in production.

**Comment by richardschoen** [comment]
I just ended the 10 QZDSAOINIT connection jobs on the IBM i with ENDJOB. 

That's when the app locked up and I noticed there was no try/catch. 

At least with try/catch the app shouldn't lock up while waiting for a response.

**Comment by alanseiden** [comment]
@markdirish We spoke at PowerUp about this issue and you invited me to tag you on it. The essence is that clients connecting from off the IBM i (Linux, Windows, etc.) time out and lose connection. People are currently coding around it to catch the error, disconnect and reconnect.

**Comment by diego-palumbo** [comment]
Hello, 
We suddenly started experimenting this error in production and we are not able to find cause of this problem.
Anyone has an update about this issue and how is solved ?

**Comment by alanseiden** [comment]
@diego-palumbo Did restarting your Node application resolve the errors? Just wondering if it's a random error or something more lasting. Also, are you connecting from something like Linux or is your Node application running directly on IBM i?

**Comment by Michelp76** [comment]
This is how we implemented it
Heavily inspired by phpdave's answer here : 
[https://github.com/IBM/node-odbc/issues/63#issuecomment-1268999937](url)

```Node
   static async query<T>(statement: string, bindingsValues: (number | string)[] = []) {
    let result;
    try {
      result = await this.pool.query(statement, bindingsValues);
    } catch (error: any) {
     // Handles the "rc=10054 - CWBCO1047" error
      if (error.odbcErrors[0].code == 8405) {
        console.log(`Connection lost : ${error}`)
        // Reconnexion
        await this.connect(connectionString);
        console.log('Running query on new pool');
        // Launches the initial query
        result = await this.pool.query(statement, bindingsValues);
      }
    } finally {
      return result;
    }
  }
```

Works perfectly and keeps the server alive
Wondeful thanks

**Comment by snotmare** [comment]
Good morning @markirish !

We are also seeing this error with our connections. Our server admin doesn't see anything from his end showing power i dropping the connections.

Were you able to identify a bug in the driver or the odbc npm package that may be causing this disconnect?
Is there any information I could collect that would help track this down?

We can make adjustments to our connection pool to handle dropped connections like this, but it would still be good to find the root cause and correct it. Let me know how I can help!

**Comment by kadler** [comment]
@snotmare that package looks quite interesting. Might be worth us deprecating the built-in pooling and instead recommending that package instead and providing some examples to use it.

**Comment by snotmare** [comment]
@richardschoen That's too bad about Mark, he was good to work with.
@kadler Thanks for the recommendation on the keep alive.

To answer the above questions, we are currently running node servers on an ibm i (power i) platform natively. Our application servers are on one partition while our database is in another. We are exploring containers right now and will possibly switch.

I did some quick performance testing on our validation logic. It appears to add about 5ms to the SQL call in a development environment. That's pretty minimal IMO for gaining stability.

Here is the relevant code from our connection class and how it uses a pool. This is written in typescript. Here are some notes...
- The code below uses some of our other built in classes that I've not shared. You should be able to get an idea of what they are doing though.
- The connection key is a way for us to dynamically restart all connections from within code. We have a use case where we'd like to do this without restarting the server or having our system admin blow away the connections manually.


```
import { createPool, Factory, Options, Pool } from 'generic-pool';
import { connect, Connection } from 'odbc';
import { SqlConnection } from './sql-connection.js';

export class OdbcConnection extends SqlConnection {
	private static readonly SELECT_VALIDATE = 'values 1';

	private pool: Pool<Connection>;
	private _connectionKey: number;

	protected override init(options: SqlConnection.InitOptions) {
		let factory: Factory<Connection> = {
			create: async () => {
				try {
					let connectionString =
						`Driver={IBM i Access ODBC Driver}; ` +
						`Naming=1; ` +
						`System=${options.dbName}; ` +
						`DFTPKGLIB=SQLPKG; ` +
						`PKG=SQLPKG,2,1,0,512; ` +
						`CCSID=1208; ` + //Character encoding for UTF-8
						`BLOCKSIZE=512; ` +
						`CMT=0; ` + //Commmitment set to immediate
						`Uid=${options.accountId}; ` +
						`Pwd=${options.accountPw}`;
						//; SSL=1

					let connection = <OdbcConnection.ValidConnection>await connect(connectionString);
					connection.connectionKey = this.connectionKey;

					return connection;
				} catch(error) {
					ServerInjector.logger.error('Error creating a connection');
					ServerInjector.logger.error(JSON.stringify(error));

					//Return undefined. This causes a downstream error and stops the connection attempt. If this throws an error, the pool will try to create connections
					//every second and fill the logs.
					return undefined;
				}
			},
			destroy: (connection: OdbcConnection.ValidConnection) => {
				return connection.close();
			},
			validate: connection => {
				return this.validate(<OdbcConnection.ValidConnection>connection);
			}
		};

		let poolOptions: Options = {
			max: options.poolMax,
			min: options.poolMin,
			testOnBorrow: true,
			acquireTimeoutMillis: options.poolWaitMillis, // waits this long if no connection is available
			softIdleTimeoutMillis: options.poolSoftIdleTimeoutMillis, // evicts only if we have more than the min connections
			idleTimeoutMillis: options.poolIdleTimeoutMillis, // evicts any idle no matter what
			evictionRunIntervalMillis: options.poolEvictionRunIntervalMillis,
			numTestsPerEvictionRun: options.poolNumTestsPerRun // determines haw many idle connections to test for with each run
		};

		poolOptions = OptionUtils.default(poolOptions, {
			max: 10,
			min: 1,
			softIdleTimeoutMillis: 30 * 1000,
			idleTimeoutMillis: 1000 * 60 * 60 * 12,
			evictionRunIntervalMillis: 30 * 1000
		});

		poolOptions = OptionUtils.default(poolOptions, {
			numTestsPerEvictionRun: (poolOptions.max - poolOptions.min) / 2 //Slowly decrease connection pool as needed
		});

		this.pool = createPool(factory, poolOptions);
	}

	private get connectionKey(): number {
		return this._connectionKey = ObjectUtils.default(this._connectionKey, () => Date.now());
	}

	private clearConnectionKey() {
		this._connectionKey = undefined;
	}

	async resetPool(): Promise<void> {
		this.clearConnectionKey();
	}

	private async getConnection(): Promise<Connection> {
		let connection = await this.pool.acquire();

		if(!connection) {
			throw new Error('Failed to get a connection');
		}

		if(this.pool.available === 0 && this.pool.size === this.pool.max) {
			ServerInjector.logger.info('All connections are in use.');
		}

		return connection;
	}

	private async releaseConnection(connection: Connection): Promise<void> {
		if(connection) {
			return this.pool.release(connection);
		}
	}

	private async validate(connection: OdbcConnection.ValidConnection): Promise<boolean> {
		try {
			if(connection.connectionKey !== this.connectionKey) {
				return false;
			}

			if(connection.lastChecked
			&& Date.now() - connection.lastChecked <= this.options.poolValidateInterval) {
				return true;
			}

			let statement = await connection.createStatement();
			await statement.prepare(OdbcConnection.SELECT_VALIDATE);
			await statement.execute();
			connection.lastChecked = Date.now();

			return true;
		} catch(error) {
			return false;
		}
	}
}

export namespace OdbcConnection {
	export interface ValidConnection extends Connection {
		lastChecked: number;
		connectionKey: number;
	}
}
```
