### ISSUE TITLE
odbcErrors 30126, 30207 on Select when nothing found

### ISSUE THREAD

**Issue by jasonwardell** [markdirish/node-odbc#66]
Based on parameters passed if there is data returned from the database it succeeds but if we pass parameters where there is no data it errors with odbcErrror codes 30126, 30207. The error message passed back is very vague and generic "Error executing the statement". 

Example Query:
SELECT *
FROM tableName
WHERE PART = ?;

If the part is found it returns data successfully and there are no issues. If the part is not found instead of returning an empty array it throws the error above. I am running version 2.2.2. I can't even find any information about these error codes and what they mean?

**Comment by markdirish** [comment]
If you could, what Database and ODBC driver are you using? The codes are native codes for your system, but there should be an associated message that gives more information. Looking for ODBC and error 30126, I see an IBM error of `[IBM][System i Access ODBC Driver]Column 3: Character data right truncation. {22001,NativeErr = 30126}[IBM]`, but I don't know why right truncation would be an issue here.

There was a bug where, when using Promises, the native odbc errors would be deleted from the error object: https://github.com/markdirish/node-odbc/pull/72. It should be fixed on the `2.3.0` branch (but isn't on npm yet). Downloading
```
npm install markdirish/node-odbc#2.3.0
```
and then running your queries again, seeing what is returned in the `odbcErrors` property of the Error object, should get more actionable error messages.

**Comment by jasonwardell** [comment]
Mark 
We are using DB2 for the IBM i and we are using the IBM i Access ODBC Driver. Thank you for the update on the module it does now show us more helpful information that allowed us to debug the problem. The problem was with our view.

**Comment by markdirish** [comment]
Glad I could help! Closing for now, feel free to reopen if it ends up being an issue on my end.
