### ISSUE TITLE
Node-Odbc on linux with Azure Always encrypted doesn't work for insert sql 

### ISSUE THREAD

**Issue by jocund** [markdirish/node-odbc#69]
**Environment:** Version of node-odbc is v6.13.4. It came with direct "npm install odbc". Also, node version is 10.19 running on linux setup. 

- Insert Query looks like below (I'm also including select query that works for Always encrypted columns). Note: "Always encrypted on" using Azure key vault is the way the DB columns are encrypted.  

var db = require("odbc");
var connectionString = "Driver={ODBC Driver 13 for SQL Server};Server=<Server_name_here>;Database=<datbase_name_here>;Uid=<UID_name_here>;Pwd=<pwd_name_here>;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;ColumnEncryption=Enabled;KeyStoreAuthentication=KeyVaultClientSecret;KeyStorePrincipalId=<ID_here>;KeyStoreSecret=<Secret_key_here>;"

**//Select Query on encrypted DB column works! Able to receive decrypted data** 
const connection = await db.connect(connectionString);
const query = await connection.query ('SELECT * FROM Patients.Encrypted')
console.log(query); //Success

**//Insert Query that works on non-encrypted column** 
const connection = await db.connect(connectionString);
const query = await connection.query ('INSERT INTO Patients.NonEncrypted (SSN, FirstName, LastName) VALUES(?, ?, ?)',['123','John','Doe'])
console.log(query);	//Success		

**//Insert Query that fails on encrypted column** 
const connection = await db.connect(connectionString);
const query = await connection.query ('INSERT INTO Patients.Encrypted (SSN, FirstName, LastName) VALUES(?, ?, ?)',['123','John','Doe'])
console.log(query);	//Failure [odbc] Error getting information about parameters

 **//Insert Query that fails on encrypted column with binding option (MS says it's mandatory to bind parameters)** 
const connection = await db.connect(connectionString);
const statement = await connection.createStatement();
await statement.prepare('INSERT INTO Patients.Encrypted (SSN, FirstName, LastName) VALUES(?, ?, ?)');
await statement.bind([{ sql_type: 1, value: '123-45-6789', precision: 0 }, { sql_type: 12, value: 'John', precision: 0 },{ sql_type: 12, value: 'Doe', precision: 0 }]);
const query = await statement.execute();
console.log(query); //Failure [odbc] Error binding parameters to the statement
await statement.close();

This is the summary of the issue. node-odbc library is able to pull from encrypted columns but I've not yet got success in push/insert to encrypted columns. Any guidance is much appreciated. I think I'm going wrong in creating correct parameters for bind but need someone to let me know how this is done. 

https://docs.microsoft.com/en-us/sql/connect/odbc/using-always-encrypted-with-the-odbc-driver?view=sql-server-ver15

**Comment by kadler** [comment]
The current version of node-odbc is 2.2.2. How do you have 6.3.4?

**Comment by jocund** [comment]
Sorry, that was a typo. I'm using 2.2.2. However, the problem stated is correct. Is there a way I can do parametrized submission using node-odbc?

**Comment by jocund** [comment]
@kadler Please let me know

**Comment by markdirish** [comment]
`[odbc] Error getting information about parameters` occurs when an error is returned from a loop that calls `SQLDescribeParam` for each parameter passed in. 

The native error returned from your driver should be passed on the error object as well (though you might have to download `npm install odbc@beta`, as it was broken for promises before `2.3.0-beta`. You can also rewrite your code to use callback functions, then you should be able to see it). To get it, look for an `odbcErrors` object on the error that is returned. It should be an array of objects that have a `message`, `code` and `state` field. That should be able to tell us more information.

It could be something dealing with encryption, or it could be something more innocuous, but this native error will tell us a lot more.

As a side note, you posted two ways of trying to insert that failed. The first one looks like correct syntax:
```
const connection = await db.connect(connectionString);
const query = await connection.query ('INSERT INTO Patients.Encrypted (SSN, FirstName, LastName) VALUES(?, ?, ?)',['123','John','Doe'])
console.log(query); //Failure [odbc] Error getting information about parameters
```

The second one is passing an array of objects, which isn't supported on this package (yet?).
```
await statement.bind([{ sql_type: 1, value: '123-45-6789', precision: 0 }, { sql_type: 12, value: 'John', precision: 0 },{ sql_type: 12, value: 'Doe', precision: 0 }]);
```
`statement.bind` will use the data retrieved during `statement.prepare` to determine precision, sql_type, etc. No need to pass that information, but eventually we may add a way to overwrite the default with an explicit type.

**Comment by markdirish** [comment]
Going to close the stale issue, feel free to reopen with more information on the native error that is returned.
