### ISSUE TITLE
much slower than version 1.4.6

### ISSUE THREAD

**Issue by jdbi336534** [markdirish/node-odbc#74]
I am using version 2.2.2, I found that this version is much slower than version 1.4.6, especially when executing multiple sql in a transaction, I do not know whether it is really slow or I use it incorrectly。

**Comment by jdbi336534** [comment]
Method 1: First initialize the connection pool, I will execute pool.connection () before each transaction;
Method 2: First initialize the connection pool and pool.connection (), each transaction uses the connection generated by pool.connection
As a result, I found that method two is faster than method one, but it is still very slow to execute multiple sql in a transaction. How can I optimize it?

**Comment by jdbi336534** [comment]
I was wrong, my database network problem

**Comment by markdirish** [comment]
Glad that it wasn't the package! In general, this package should be much faster using `SQLBindCol` and `SQLFetch` instead of `SQLGetData`, but there are a few cases where `SQLGetData` is probably faster (large binary/character fields).
