### ISSUE TITLE
Batch insert support 

### ISSUE THREAD

**Issue by buro1983** [markdirish/node-odbc#75]
I am trying to insert multiple records in a single insert statement. I am musing prepare statement but 
I am not able to find any way to do the batch insertion using this library. Can you anyone please point me out how do I achieve the batch insertion using node odbc library.

**Comment by markdirish** [comment]
There is a good overview of batch insert available in the ODBC docs: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/batches-of-sql-statements?view=sql-server-ver15

If your driver/DBMS allows explicit batches, that might be the best solution. It will only send the statements once, saving some network time.

Other than that, a node `odbc` package way of doing it might be:
```
const parameters = [ 
[ 123, "Mark", "Irish"],
[ 456, "George", "Washington"]
];
await statement.prepare('INSERT INTO MYTABLE VALUES (?, ? ,?);
for (let i = 0; i < parameters.length; i++) {
  await statement.bind(parameters);
  const result = await statement.execute();
}
```
This will send traffic for each statement, and isn't "TRUE" batching, but will be a little easier for you.

In the future, it would be good to implement some of the things on this page: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/executing-batches?view=sql-server-ver15 , namely using `SQLGetInfo` to get `SQL_BATCH_SUPPORT`, `SQL_PARAM_ARRAY_ROW_COUNTS`, and `SQL_PARAM_ARRAY_SELECTS`. 

If the driver doesn't support those things, we could still implement "false" batching by allowing users to pass an array of arrays for parameters, and execute them one at a time like the loop above.

**Comment by snotmare** [comment]
Not sure if this helps in your case, but there is a nifty SQL trick you can use that will insert multiple rows to the same table. Consider this SQL...

```
select id, name, status
from final userTable (
insert into userTable (id, name, status)
values (?, ?), (?, ?), (?, ?)
)
```

I free-handed the sql, but it should be pretty close. This will insert 3 rows into a 3 column table. In my example, id is an auto-incrementing identity column. The generated id will be returned in the select (along with any other default values defined on the table that you select).

Just make sure you bind the parameters in the correct order for each row you're inserting.

**Comment by markdirish** [comment]
Not stale
