### ISSUE TITLE
Critical: 2.0 version data read: Float and Date values from same queries are not showing up same as Version 1.4.6 

### ISSUE THREAD

**Issue by JTBS** [markdirish/node-odbc#8]
I have two instances running on same machine, pointing to same DB and SAME code-base - ONLY exception is one uses ODBC 1.4.6 and other uses ODBC 2.0.0.

I am doing this to test new version. Performance is consistently 50% better even when I tested iwht 10MB of data returned through queries.

**Issue: Main issue is FLOAT values returned by ODBC 2.0.0 driver are not correct**. All other values match including dates/strings/numbers on same record.. 

Below is example:

**Float samples**
**ODBC 1.4.6**:  [507.365, 504.167]
**ODBC 2.0.0**: [1.83187975902498e-76, 4.2778154908686205e-33]

**Date samples** : (Issue with dates is HOURS is always showing in LOCAL/EST with 2.0 version)
**ODBC 1.4.6**:  [2016-02-22T05:29:41.000Z]
**ODBC 2.0.0**: [2016-02-22 **00**:29:41.0000000] - Please see how ONLY hours part is wrong

**ODBC 1.4.6**: "2017-02-06T19:29:51.000Z"
**ODBC 2.0.0**: "2017-02-06 14:29:51.0000000"

NOTE: As you see difference here is HOURS is -5H difference from OLDER version. Suggesting that new 2.0.0 version is converting always values to LOCAL/EST timezone

**Above are sample from one or two records but this is the case throughout.**

**Environment**: Node 8.16.0 [for both on same machine and pointing to same DB/queries etc]

This is critical issue as data needs to be 100% accurate with new version. Really appreciate any help on this.

**Comment by markdirish** [comment]
Ok, so I've investigated the timestamp issue, and I think the right solution is to leave it as it is.

Justification:

In ODBC 1.4.6, when a SQL_DATETIME or SQL_TIMESTAMP field is returned, the package would take the String returned, and call the C functions `mktime`, `timelocal`, or `gmtime` depending on what OS you were running and what functions you had available to you.

In the examples you posted for 1.4.6, what is happening is the database is returning '2017-02-06 14:29:51.0000000' (actually returns a struct, but for simplicity's sake), and then calling `timelocal`, which says "I want this in UTC, and what I am giving is in my local time". Of course, there is no guarantee that the timestamp is really in your local time, as in most DBMS timestamps are stored without timezone data. And indeed, I can't find any example of ODBC itself having any knowledge of timezones.

If I leave it as is, what happens is the ODBC driver is told to return the timestamp in a String. If the driver/DBMS has a way to track timezone, it should return the timezone in the String. If the driver/DBMS has no concept of timezone, it will return as you show in ODBC 2.0.0. So results may not be consistent across different drivers, which may return data in different formats (and even the same driver with different settings enabled), but the returned data will be more accurate.

**Comment by JTBS** [comment]
Thank you. I will test more.. but I agree that driver should not do any conversion and return what is returned in DB as-is.  But it is important to highlight this change in your Read me as you don't want people to find this out by surprise. You will just help them upfront this way to avoid noise.

Really appreciate you taking care of this issue. Thanks.
