### ISSUE TITLE
why there is no version 2.2.2 release on github?

### ISSUE THREAD

**Issue by jdbi336534** [markdirish/node-odbc#83]
Hello, why is the version 2.2.2 on npm, but the release on github is 2.1.0? Can you release version 2.2.2 on github?

**Comment by markdirish** [comment]
Hi @jdbi336534 

Obviously this was nearly a year ago... but I didn't have a good system for creating releases back then. I now have a GitHub Action that spins out Releases when a version tag is pushed. I am not going to create releases for previous missed versions, but all future versions should have their own tag.
