### ISSUE TITLE
Issues using req.body.value in Insert Statement. 

### ISSUE THREAD

**Issue by CodeBroJohn** [markdirish/node-odbc#84]
I have a value being sent via a post to my route. 

The post route include a query like the following: 

INSERT INTO test.amessages(STATUS) VALUES(${req.body.value})

When I do this it doesnt work as expected, however if I replace ${req.body.value} with 'text', it works as expected. 

Is it possible to pass req.body values to the sql statement with node-odbc? 

Before I do the sql statement, I can do a console.log(req.body.value) and I get the expected value.

**Comment by markdirish** [comment]
I assume you are using `express` or something similar.

Is the value of `req.body.value` a string? It should work just fine if you are passing a variable in the query, my only thoughts are:

1. If your query is `INSERT INTO test.amessages(STATUS) VALUES(${req.body.value})`, you end up getting `INSERT INTO test.amessages(STATUS) VALUES(text)` when you really want `INSERT INTO test.amessages(STATUS) VALUES('text')` (note the `'` quotes, but which types of quotes depends on your DMBS)
2. You aren't using the right quotations for the template literal (but the fact that you are using `${}` tells me that you probably are).

If neither of those are the case, could you include some code, maybe printing the value of `req.body.value` right before the query?

**Comment by CodeBroJohn** [comment]
I am indeed using express. 

The body of the request looks like the following:
{
    "value": "Test"
}

Given that it is possible that maybe db2 doesnt like the double quotes? 

This is how the route looks: 

router.post('/',
[
    check('value', 'Value is required!')
        .not()
        .isEmpty(),
],
async (req, res) => {
    const validationErrors = validationResult(req);
    if (!validationErrors.isEmpty()) {
        return res.status(400).json({ validationErrors: validationErrors.array() });
    }
    else {
        try {
            await odbc.connect(cn, (error, connection) => {
                console.log(req.body.value)
                connection.query(
                    "INSERT INTO test.amessages(STATUS) VALUES(req.body.value)",
                    (error, result) => {
                        if (error) {
                            throw error;
                        }
                        return res.status(200).json({ result });
                    }
                );
            });

        }
        catch (error) {
            console.error(error);
            return res.status(500).json({ msg: 'Server Error' });
        }
    }
});

The console.log that prints req.body.value before doing the INSERT prints Test with no quotes or anything.

**Comment by CodeBroJohn** [comment]
Hey @markdirish I was able to solve this by moving req.body values to a parameter array and then adding them to the INSERT query as ? in the order they occur in the array. Appreciate your time!

**Comment by markdirish** [comment]
> Given that it is possible that maybe db2 doesnt like the double quotes?

Nope, that's just JavaScript's way of showing you that's a string. The `"`s aren't really there.

The issue I see in the code is that you are running a query with a plain string wrapped in double quotes `"`:
```
connection.query(
  "INSERT INTO test.amessages(STATUS) VALUES(req.body.value)",
  (error, result) => {
    if (error) {
      throw error;
    }
    return res.status(200).json({ result });
  }
);
```
In JavaScript, strings (wrapped in either single or double quotes) won't do variable value replacement. So your query will look exactly as you typed it.

What you need is a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). So instead of:
```
 "INSERT INTO test.amessages(STATUS) VALUES(req.body.value)"
```
You'd have
```
`INSERT INTO test.amessages(STATUS) VALUES(${req.body.value})`
```
I thought this is what you had before. *But even this won't solve your problems*, because, since you are inserting a string in your query, you need to wrap that string in single quotes:
```
`INSERT INTO test.amessages(STATUS) VALUES('${req.body.value}')`
```
In Db2, when dealing with string values, they must be wrapped in single quotes. Double quotes are used for identifiers.

**Comment by markdirish** [comment]
> Hey @markdirish I was able to solve this by moving req.body values to a parameter array and then adding them to the INSERT query as ? in the order they occur in the array. Appreciate your time!

This works because parameters are bound in a different way than simply inserting values, so there is no need to wrap in single quotes
