### ISSUE TITLE
Feature request: support unnamed columns

### ISSUE THREAD

**Issue by cebaa** [markdirish/node-odbc#87]
First, thanks for the awesome job you're doing with this project, it helps me tremendously!

The actual feature request:

```
[
  { '': 2 },
  statement: 'select max(1), max(2)',
  parameters: undefined,
  return: undefined,
  count: -1,
  columns: [ { name: '', dataType: 4 }, { name: '', dataType: 4 } ]
]
```

Since both columns have no name, only one is key is created and the second one overwrites the first.

My suggestion is to auto-name (or potentially add the options argument for this to be user-controlled) missing keys - .e.g as `_1`, `_2`, ... or something along those lines, making it essentially equivalent to this:

```
[
  { _1: 1, _2: 2 },
  statement: 'select max(1) _1, max(2) _2',
  parameters: undefined,
  return: undefined,
  count: -1,
  columns: [ { name: '_1', dataType: 4 }, { name: '_2', dataType: 4 } ]
]
```

**Comment by markdirish** [comment]
Interesting. I will have to think of the best way to have user's indicate how they want keys to be generated, but in the meantime it shouldn't be difficult to check whether the column name is blank, and if so, generate a name like `_00000`, `_00001`, etc.

**Comment by markdirish** [comment]
Alright, I've pushed a fix to a new branch. You can download with:
```
npm install markdirish/node-odbc#2.3.0-unnamed-columns`
```
That should generate column names if the column name returned has no length. Let me know if it works (my DBMS of choice doesn't allow unnamed columns, it auto generates them for me).

Other solutions that might work (depending on whether you like how this is implemented now):

1. You can modify your queries to use the `AS` keyword: `select max(1) as "1", max(2) as "2"` (your syntax may vary).
2. This connector has a (apparently hidden) feature that allows results to be returned as an Array instead of an object/dictionary. To activate this behavior, your connection needs to be given a connection object with the property `fetchArray: true`:

```
const odbc = require('odbc');

async function test() {
  try {
    const connectionobj = {
      connectionString: 'DSN=MyDSN',
      fetchArray: true
    }
    const connection = await odbc.connect(connectionobj);
    const result = await connection.query(`SELECT '1' FROM SYSIBM.SYSDUMMY1`);
    console.log(result);
  } catch (error) {
    console.error(error);
  }
}

test();
```
Let me know what you think!

**Comment by cebaa** [comment]
Thanks for a quick turnaround @markdirish!

>  I will have to think of the best way to have user's indicate how they want keys to be generated

Perhaps adding a column naming function (i.e. column index => column name or even better (column name, column index) => column name) for these would be best, but that may require changing the API, so not sure if that's desirable.

I'm also not sure how often this is going to be used and how much it complicates things on your end. It might not be worth the additional effort, especially given the other options.

> npm install markdirish/node-odbc#2.3.0-unnamed-columns

This looks good to me:

```
[
  { _00000: 1, _00001: 2 },
  statement: 'select max(1), max(2)',
  parameters: undefined,
  return: undefined,
  count: -1,
  columns: [ { name: '_00000', dataType: 4 }, { name: '_00001', dataType: 4 } ]
]
```

I'd just make them shorter (i.e. _0 instead of _00000), as it's unlikely you'd have 10k columns in a select :) While a bit less likely with longer identifiers, clashes with user-supplied columns are possible either way:

```
[
  { _00000: 2 },
  statement: 'select max(1) _00000, max(2) _00000',
  parameters: undefined,
  return: undefined,
  count: -1,
  columns: [ { name: '_00000', dataType: 4 }, { name: '_00000', dataType: 4 } ]
]
```

> 1. You can modify your queries to use the AS keyword: select max(1) as "1", max(2) as "2" (your syntax may vary).

Yeah, that was what I was using so far.

> 2. This connector has a (apparently hidden) feature that allows results to be returned as an Array instead of an object/dictionary. To activate this behavior, your connection needs to be given a connection object with the property fetchArray: true:

This works great as well:

```
[
  [ 1, 2 ],
  statement: 'select max(1), max(2)',
  parameters: undefined,
  return: undefined,
  count: -1,
  columns: [ { name: '_00000', dataType: 4 }, { name: '_00001', dataType: 4 } ]
]
```

All three approaches are good from my perspective, including keeping it as you implemented it in this version.
