### ISSUE TITLE
Fix build warnings

### ISSUE THREAD

**Issue by markdirish** [markdirish/node-odbc#88]
I have been ignoring build warnings, but as the package moves to use GitHub actions to test and deploy, I would like that output to be as clean as possible. In `2.3.0`, there are 2 types of warnings:

1. Issue when passing `isolationLeve` to `SQLSetConnectAttr`. Casting a 32-bit integer to a 64-bit `SQLPOINTER` causes the warning: 

```
../src/odbc_connection.cpp: In member function ‘virtual void SetIsolationLevelAsyncWorker::Execute()’:
../src/odbc_connection.cpp:102:22: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         (SQLPOINTER) isolationLevel, // ValuePtr
```
Fix: cast to `uintptr_t` before casting to `SQLPOINTER`

2. Since moving to binding everything not to `SQLCHAR []`s, but instead using the correct C types, `QueryData->boundRow[i]` now can point to several different C types. Data type for the bound row was therefore changed to a `void *`, but deleting a `void *` causes a warning: 
```
In file included from ../src/odbc_statement.cpp:22:0:
../src/odbc.h: In member function ‘void QueryData::clear()’:
../src/odbc.h:210:34: warning: deleting ‘void*’ is undefined [enabled by default]
         delete[] this->boundRow[i];
```
Fix: check the target_type of the column to know what the underlying C type is, and cast to that pointer type before deleting.

**Comment by kadler** [comment]
While this would be good to fix, it's not a "problem" as all the types are trivially destructible.

> A trivial destructor is a destructor that performs no action. Objects with trivial destructors don't require a delete-expression and may be disposed of by simply deallocating their storage. All data types compatible with the C language (POD types) are trivially destructible. 

https://en.cppreference.com/w/cpp/language/destructor
