### ISSUE TITLE
Node.js Version Requirement

### ISSUE THREAD

**Issue by CodeBroJohn** [markdirish/node-odbc#90]
I have moved my node.js application from windows 10 to ubuntu 18.04. For that version of ubuntu the default repositories version of node.js is 8.10.0. 

When I try to install odbc i get the warning that the package wants node >= 8.16.0. 

I also get: Failed at the odbc@2.2.2 install script 'node-gyp configure build'.

Is this a result of using node 8.10.0?

**Comment by kadler** [comment]
This is from the package.json: https://github.com/markdirish/node-odbc/blob/master/package.json#L33

@markdirish is this due to NAPI requirements?

**Comment by markdirish** [comment]
Version matrix: https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix

It looks like at some point I decided to use N-API v4 features. Off the top of my head I am not sure exactly what they are. Looking at the node-addon-api file [napi-inl.h](https://github.com/nodejs/node-addon-api/blob/master/napi-inl.h), it looks like v4 wraps around `AsyncProgress` classes and the `Date` class, neither of which are used by `odbc`.

You could try to change the version in the `package.json` to `">=8.10.0"` then run `npm install` again, and see if that fixes the issue. It looks like N-API was released as experimental until v3 in `v8.11.2`, but it _might_ still run.

**Comment by CodeBroJohn** [comment]
I will give that a shot. So far what I have did is changed the package version to 2.0.0, Have not checked to see if everything works as expected but I do get this warning. 

(node:10398) Warning: N-API is an experimental feature and could change at any time.

**Comment by CodeBroJohn** [comment]
Changing to an older version did not help, and changing the engine node to ">=8.10.0" suppressed that error, but odbc still did not install, same error: 
Failed at the odbc@2.2.2 install script 'node-gyp configure build'.
