### ISSUE TITLE
Error text buffer conflict in ODBCAsyncWorker::GetODBCErrors()

### ISSUE THREAD

**Issue by gordonthorpe** [markdirish/node-odbc#94]
ODBCAsyncWorker::GetODBCErrors() declares a local stack buffer, errorMessage[], to receive the error text returned by SQLGetDiagRec().  A reference to this buffer is saved in an ODBCError structure which is subsequently assigned to the array of errors returned by the function.

There are two problems with this code:

1. SQLGetDiagRec() is called in a loop to process multiple error conditions.  The local buffer is used during each loop iteration and each subsequent error overwrites the message text of previous errors.
2. When the array of ODBCError structures is returned from the function, the errorMessage reference in each ODBCError goes out of scope.  The stack memory previously allotted to errorMessage can then be overwriten by stack operations.

**Comment by markdirish** [comment]
Merged into master with this PR: https://github.com/markdirish/node-odbc/pull/95

Not yet published, but will close when published in the latest version.

**Comment by markdirish** [comment]
2.4.0 is now published and this should be fixed. Feel free to open if it still seems broken!
