### ISSUE TITLE
Add precision and scale to columns in query results

### ISSUE THREAD

**Issue by snotmare** [markdirish/node-odbc#98]
Hello! This is a feature request.

We are looking at the 2.3.0 version and are close to being able to use this in our production system. We use DB2 on a power i.

When running a query, we would like to use the columns array to understand more about the data types we're getting back. Right now it returns the column name and data type. Could you please also add precision and scale? I believe JDBC reuses precision on char fields for length, so that could work. Or, if you prefer to add a length property for char fields, that could work also.

Thanks a bunch!

**Comment by markdirish** [comment]
It should just be a matter of copying that data (which is already obtained from `SQLDescribeCol`) to the column object. The terms "precision" and "scale" will probably be "columnSize" and "decimalDigits" since those are the terms used by ODBC 3.x

**Comment by markdirish** [comment]
Pushing out 2.3.2 today, going to try to get this in there

**Comment by markdirish** [comment]
Well that was incredibly easy:
```
  statement: 'SELECT * FROM MIRISH.ODBC_TEST',
  parameters: undefined,
  return: undefined,
  count: -1,
  columns: [ { name: 'DECFIELD',
      dataType: 3,
      columnSize: 5,
      decimalDigits: 3,
      nullable: true } ] ]
```
this field is `DECIMAL(5,3)`

**Comment by markdirish** [comment]
Should now be live in 2.3.2!
