### ISSUE TITLE
Stored procedure issues

### ISSUE THREAD

**Issue by snotmare** [markdirish/node-odbc#99]
ODBC: 2.3.0
Driver:
[IBM i Access ODBC Driver]                   
Description=IBM i Access ODBC Driver         
Driver=/QOpenSys/pkgs/lib/libcwbodbc.so      
Threading=0                                  
DontDLClose=1                                
UsageCount=1

System:
- Windows 10 for local development
- Power i

There are 3 issues I'd like to report concerning stored procedures. One question I have is, what can we provide you so you can recreate the issue in your environment? We are using RPG service programs. Would you like us to create a service program and stored procedure to call? Let me know and we'd be happy to do what we can.

1. (Feature) Can stored procedures return result columns the same way SQL results do? We'd need name, data type, precision, and scale.

2. Stored procedures do not always return output parameters correctly. Sometimes I get output parameters, sometimes I do not. The intermittent nature of this issue reminds me of this one: https://github.com/markdirish/node-odbc/issues/58

3. When we do get output parameters (defined as IN/OUT), they are not the correct value. I'm expecting a value such as "OX", but I get "O" instead.

What can I do to help you with these issues?
Thanks all for your work on this. We're looking forward to using odbc!

**Comment by markdirish** [comment]
If you could create the service program and stored procedure, that would probably help in diagnosing the issue. Maybe the most minimal program/procedure that still demonstrates the issues. You can post here or send to mirish@ibm.com if you want. As for your issues:

1. I can look into it, it will require a little bit of work as it requires another API call (`SQLProcedureColumns`) and it returns a bit of data to sift through. It should have everything you want though (scroll down from [HERE](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlprocedurecolumns-function?view=sql-server-ver15#comments) to see all 19 columns of data it returns for each column in the procedure.

2. I really really hate bugs that are intermittent, seems like some sort of race condition then. I can look into it if you send me a short sample program/procedure.

3. Are you sending anything *IN* with your in-out parameters? Sending in `undefined` or `null`? And are the results always just 1 character, or are the n-1 characters (where you expect n characters)

Will try to tackle all of the procedure issues as my next major push on this package.

**Comment by snotmare** [comment]
Thanks @markdirish 

We'll get you a sample service program and SP to recreate the issue.

I appreciate all the work you guys put into this. The SQL side seems pretty solid from what I can tell. We have some edge cases that don't work with the IDB connector but work fine with ODBC.

**Comment by snotmare** [comment]
Hello! I have a sample program for you. This is one that does not return output parameters, and fortunately it seems to be consistently not working :). I haven't seen anything where it returns a partial output parameter, so I'll keep watching for that.

Service program CVRODBCP
```
**free
  //-----------------------------------------------------------------------*
  // COMPILE options:
  // *_> CRTSQLRPGI obj(@5/@4) +
  // *_>   srcfile(@2/@1) srcmbr(*OBJ) +
  // *_>   objtype(*PGM) +
  // *_>   option(*SYS *EVENTF) +
  // *_>   rpgppopt(*LVL1) +
  // *_>   closqlcsr(*ENDACTGRP) +
  // *_>   dbgview(*SOURCE)
  // *_> CRTSTORPRC objlib(@5) +
  // *_>   proc(CVRODBCSP) +
  // *_>   srcf(QSQLSRC)
  //-----------------------------------------------------------------------*

  ctl-opt dftactgrp(*NO) actgrp('QILE');

  //entry parameters
  dcl-pi cvrodbcp;
    e1GAct char(2);
    e1Igno char(1) const;
    e1Result packed(1);
  end-pi;

  // errors
  dcl-ds m2errDs dim(5) qualified inz;
    m2type char(1);
    m2mstx char(50);
    m2pgnm char(10);
  end-ds;
  dcl-s m2ErrCnt int(5) inz;

  // result set
  dcl-ds resultSet dim(5) qualified inz;
    firstName char(50);
    lastName char(100);
  end-ds;
  dcl-s resultSetCount int(5);

  //*************************************************************************
  // Mainline
  //*************************************************************************

  select;
  when e1GAct = 'MD';  // Metadata
   // NOOP
  when e1gact = 'RE';  // Read
    loadResultSet();
  other;
    loadErrors();
  endsl;

  exsr $setResultSets;

  *inLR = *on;
  return;

  //*************************************************************************
  // Set the result set(s)
  //*************************************************************************
  begsr $setResultSets;

    if m2ErrCnt = 0;
      // return names
      exec sql set result sets array :resultSet for :resultSetCount rows;
      if resultSetCount = %elem(resultSet);
        e1gact = 'MX';
      else;
        e1gact = 'OK';
      endif;
      e1Result = 1;
    else;
      // return error(s)
      exec sql set result sets array :m2ErrDs for :m2ErrCnt rows;
      e1gact = 'ER';
      e1Result = 0;
    endif;

  endsr;

  //-----------------------------------------------------------------------
  // Procedure: loadResultSet
  // Purpose:   load the return result set
  // Returns:   boolean
  // Required Parameters:
  //   none
  // Optional Parameters:
  //   none
  //-----------------------------------------------------------------------
  dcl-proc loadResultSet;
  dcl-pi *n ind;
  end-pi;

    resultSetCount += 1;
    resultSet(resultSetCount).firstName = 'Foo';
    resultSet(resultSetCount).lastName = 'Bar';

    resultSetCount += 1;
    resultSet(resultSetCount).firstName = 'Fizz';
    resultSet(resultSetCount).lastName = 'Buzz';

    return *on;

  end-proc loadResultSet;

  //-----------------------------------------------------------------------
  // Procedure: loadErrors
  // Purpose:   load errors
  // Returns:   boolean
  // Required Parameters:
  //   none
  // Optional Parameters:
  //   none
  //-----------------------------------------------------------------------
  dcl-proc loadErrors;
  dcl-pi *n ind;
  end-pi;

    m2ErrCnt += 1;
    m2errDs(m2ErrCnt).m2type = 'G';
    m2errDs(m2ErrCnt).m2mstx = 'Invalid Get Action';

    return *on;

  end-proc loadErrors;
```

Stored procedure CVRODBCSP
```
SET PATH=*LIBL;
SET SCHEMA=&LIB;

CREATE OR REPLACE PROCEDURE &LIB/CVRODBCSP (
    INOUT gact           CHAR(2)
  , IN    igno           CHAR(1)
  , OUT   result         DECIMAL(1,0)
  )
  DYNAMIC RESULT SETS 1
  LANGUAGE RPGLE
  SPECIFIC &LIB/CVRODBCSP
  NOT DETERMINISTIC
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  EXTERNAL NAME &LIB/CVRODBCP
  PARAMETER STYLE GENERAL;

COMMENT ON SPECIFIC PROCEDURE &LIB/CVRODBCSP IS 'ODBC Test SP';
LABEL   ON SPECIFIC PROCEDURE &LIB/CVRODBCSP IS 'ODBC Test SP';
```

We called this 3 different ways...

```
let result = await connection.callProcedure(null, null, 'CVRODBCSP', ['RE', 'Y', null]);
let result = await connection.callProcedure(null, null, 'CVRODBCSP', ['MD', 'Y', null]);
let result = await connection.callProcedure(null, null, 'CVRODBCSP', ['XX', 'Y', null]);
```

All 3 calls return results correctly, it's just that they don't provide the output values for the 1st (INOUT) and 3rd (OUT) parameters.

**Comment by snotmare** [comment]
@markdirish Can we reopen this issue please?
